const $=(s)=>document.querySelector(s); let interpretation=null; let result=null; let payload=null; let preview=null; let remembered=null;
const labels={ELIGIBLE_CONFIRMED:"Passt nach bestätigten Angaben",UNCONFIRMED_FALLBACK:"Könnte passen – wichtige Angabe fehlt",NOT_CONFIGURED:"Regel noch nicht freigegeben",INELIGIBLE:"Passt nicht zu einer zwingenden Bedingung"};
const words={"context.intent.food":"Essen","context.intent.drinks":"Etwas trinken","context.intent.coffee":"Kaffee","context.intent.conversation":"In Ruhe reden","context.intent.conflicting":"Widersprüchliche Absichten","context.occasion.first-date":"Erstes Date","context.occasion.family":"Familie","context.mood.quiet":"ruhig","context.mood.cozy":"gemütlich","context.mood.lively":"lebhaft",LOCATION_SCOPE:"Zielgebiet",ACCESSIBILITY:"Rollstuhlgerechter Zugang",BUDGET_MAXIMUM:"Maximales Budget",DISTANCE_MAXIMUM:"In der Nähe",AGE_OR_LEGAL:"Altersregel",OPENING_CURRENT:"Jetzt geöffnet",KITCHEN_CURRENT:"Küche geöffnet",MOOD:"gewünschte Stimmung",EXPLORATION:"etwas Neues",FAMILIARITY:"etwas Vertrautes",MIDDAY:"Mittag",EVENING:"Abend",MORNING:"Morgen"};
const reverse=Object.fromEntries(Object.entries(words).map(([key,value])=>[value,key])); const human=(value)=>words[value]||value; const code=(value)=>reverse[value]||value;
const api=async(path,body)=>{const options=body===undefined?{}:{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)};const response=await fetch(path,options);const value=await response.json();if(!value.ok)throw new Error(value.message||value.code);return value.data};
const list=(id,value)=>{$(id).value=(value||[]).map(human).join("\n")}; const lines=(id)=>$(id).value.split(/\n|,/).map(value=>code(value.trim())).filter(Boolean);
const escapeHtml=(value)=>String(value).replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);
function currentPayload(extra={}){return{text:$("#task").value,tracking:$("#tracking").checked,deviceCity:$("#device-city").value,userMode:"NEUTRAL_MISSING",...extra}}
function corrections(){return{primaryIntent:code($("#primary").value)||null,secondaryIntent:code($("#secondary").value)||null,occasion:code($("#occasion").value)||null,moods:lines("#moods"),targetCity:$("#target-city").value||null,dateTime:{...interpretation.dateTime,dayPhase:code($("#day-phase").value)||null},budget:{...interpretation.budget,state:$("#budget").value?"KNOWN":"UNKNOWN",amount:$("#budget").value?Number($("#budget").value):null,currency:$("#budget").value?"CHF":null},stayDuration:$("#duration").value||null,hardConstraints:lines("#hard"),softPreferences:lines("#soft")}}
async function loadCohort(){const c=await api("/api/cohort");$("#source-badge").textContent=c.source==="FOUNDER_WORLD_COHORT"?"Founder World Cohort":"Synthetische Testwelt";const imported=c.importedAt?`Lokal aktiviert: ${new Date(c.importedAt).toLocaleString("de-CH")}`:"Kein Founder-Cohort importiert.";$("#source-summary").innerHTML=`<strong>${c.source==="FOUNDER_WORLD_COHORT"?"Echte lokale Founder-Testdaten":"Synthetische Testwelt"}</strong><p>${c.spotCount} Spot${c.spotCount===1?"":"s"}: ${c.names.map(escapeHtml).join(", ")}</p><p>${escapeHtml(imported)} Manifest: ${c.manifestValid?"vollständig gültig":"ungültig"}.</p>${c.singleSpot?'<p class="limitation">Der aktuelle Founder Cohort enthält nur einen Spot. Für einen aussagekräftigen Kandidatenvergleich sollten in World Knowledge weitere geprüfte Spots zum Founder Cohort hinzugefügt und erneut exportiert werden.</p>':""}`;}
$("#cohort-file").onchange=async(event)=>{try{const file=event.target.files?.[0];if(!file)return;const artifact=JSON.parse(await file.text());const data=await api("/api/cohort/preview",{artifact});preview={artifact,previewHash:data.previewHash};$("#preview-content").innerHTML=`<p><strong>${data.spotCount} Spot${data.spotCount===1?"":"s"}</strong>: ${data.names.map(escapeHtml).join(", ")}</p><p>Exportstand: ${escapeHtml(new Date(data.exportedAt).toLocaleString("de-CH"))}. Manifest vollständig gültig.</p>${data.singleSpot?'<p class="limitation">Ein Spot kann technisch geprüft werden, ist aber kein belastbarer Kandidatenvergleich.</p>':""}`;$("#cohort-preview").hidden=false;$("#notice").textContent="Datei geprüft. Der Import erfolgt erst nach deiner Bestätigung."}catch(error){preview=null;$("#cohort-preview").hidden=true;$("#notice").textContent=`Cohort nicht übernommen: ${error.message}`}};
$("#confirm-import").onclick=async()=>{try{if(!preview)throw new Error("Bitte zuerst eine gültige Datei auswählen.");await api("/api/cohort/import",preview);preview=null;$("#cohort-preview").hidden=true;await loadCohort();$("#notice").textContent="Founder World Cohort lokal aktiviert. World Knowledge wurde nicht verändert."}catch(error){$("#notice").textContent=error.message}};
$("#synthetic").onclick=async()=>{await api("/api/cohort/synthetic",{});await loadCohort();$("#notice").textContent="Bewusst zur synthetischen Testwelt gewechselt."};
$("#reset").onclick=async()=>{if(!confirm("Nur den lokalen Decision-Lab-Cohort zurücksetzen? World Knowledge bleibt unverändert."))return;await api("/api/cohort/reset",{});await loadCohort();$("#notice").textContent="Lokaler Lab-Zustand zurückgesetzt; keine World- oder User-Daten wurden verändert."};
document.querySelectorAll(".preset").forEach(button=>button.onclick=()=>{$("#task").value=button.dataset.text;$("#notice").textContent="Vorbereitete Aufgabe geladen und frei korrigierbar."});
$("#resolve").onclick=async()=>{try{payload=currentPayload();interpretation=await api("/api/resolve",payload);$("#primary").value=human(interpretation.primaryIntent||"");$("#secondary").value=human(interpretation.secondaryIntent||"");$("#occasion").value=human(interpretation.occasion||"");list("#moods",interpretation.moods);$("#target-city").value=interpretation.targetCity||"";$("#day-phase").value=human(interpretation.dateTime.dayPhase||"");$("#budget").value=interpretation.budget.amount??"";$("#duration").value=interpretation.stayDuration||"";list("#hard",interpretation.hardConstraints);list("#soft",interpretation.softPreferences);$("#understood").innerHTML=`<h3>Was Backyrd verstanden hat</h3><p>${[interpretation.primaryIntent,interpretation.occasion,...interpretation.moods].filter(Boolean).map(human).map(escapeHtml).join(" · ")||"Absicht noch unklar"}</p><p>Zielort: ${escapeHtml(interpretation.targetCity||"nicht bekannt")} · Budget: ${interpretation.budget.amount?`${interpretation.budget.amount} CHF${interpretation.budget.perPerson?" pro Person":""}`:"nicht angegeben"}</p>`;$("#unclear").textContent=interpretation.unresolvedTerms.length?`Unklar: ${interpretation.unresolvedTerms.join(", ")}`:"Keine still verworfenen Begriffe.";$("#interpretation").hidden=false;$("#notice").textContent="Interpretation ist lokal prüfbar und noch nicht ausgewertet."}catch(error){$("#notice").textContent=error.message}};
function render(r){const groups=$("#candidate-groups");groups.innerHTML="";const counts=Object.fromEntries(Object.keys(labels).map(key=>[key,r.candidates.filter(candidate=>candidate.tier===key).length]));$("#summary").innerHTML=`<div class="summary">${Object.entries(counts).map(([key,count])=>`<div class="metric"><strong>${count}</strong>${labels[key]}</div>`).join("")}</div><p>${r.worldCohort.source==="SYNTHETIC_FALLBACK"?"Synthetische Testwelt – kein Founder Cohort gebunden.":"Founder World Cohort – lokal importiert und vollständig gebunden."}</p>${r.worldCohort.spotBindings.length===1?'<p class="limitation">Ein einzelner Spot ist technisch auswertbar, aber kein belastbarer Ranking- oder Vergleichstest.</p>':""}`;for(const [tier,title]of Object.entries(labels)){const rows=r.candidates.filter(candidate=>candidate.tier===tier);const section=document.createElement("div");section.className="group";section.innerHTML=`<h3>${title} <span class="count">${rows.length}</span></h3><div class="cards">${rows.map(candidate=>`<article class="card ${tier==="ELIGIBLE_CONFIRMED"?"confirmed":tier==="UNCONFIRMED_FALLBACK"?"fallback":"ineligible"}"><h4>${escapeHtml(candidate.label)}</h4><p>${candidate.reasons.map(reason=>escapeHtml(reason.statementDe)).join(" ")}</p><ul>${candidate.unknownHardConstraints.map(item=>`<li>Unbekannt: ${escapeHtml(human(item))} – weder Ja noch Nein</li>`).join("")}${candidate.failedHardConstraints.map(item=>`<li>Zwingende Bedingung nicht erfüllt: ${escapeHtml(human(item))}</li>`).join("")}</ul><button class="secondary reject" data-id="${escapeHtml(candidate.candidateId)}">Dieser Spot passt nicht</button></article>`).join("")}</div>`;groups.append(section)}$("#expert-data").textContent=JSON.stringify(r,null,2);$("#results").hidden=false;document.querySelectorAll(".reject").forEach(button=>button.onclick=()=>{payload={...payload,rejectedCandidateIds:[...(payload.rejectedCandidateIds||[]),button.dataset.id]};$("#notice").textContent="Nur für diese Decision markiert; kein User-Intelligence-Write."});if(remembered){$("#comparison").hidden=false;$("#comparison").textContent=`Direkter Vergleich: vorher ${remembered.candidates.length} Kandidaten, jetzt ${r.candidates.length}. Die Result-Identitäten sind ${remembered.resultHash===r.resultHash?"gleich":"verschieden"}.`}}
$("#evaluate").onclick=async()=>{try{payload={...currentPayload(),corrections:corrections()};result=await api("/api/evaluate",payload);render(result)}catch(error){$("#notice").textContent=error.message}};
$("#replay").onclick=async()=>{try{const replay=await api("/api/replay",{...payload,result});$("#notice").textContent=replay.resultHash===result.resultHash?"Replay byte-identisch bestätigt.":"Replay abweichend"}catch(error){$("#notice").textContent=error.message}};
$("#alternative").onclick=async()=>{try{payload={...currentPayload({alternativeRequested:true}),corrections:corrections()};result=await api("/api/evaluate",payload);render(result);$("#notice").textContent="Alternative angefordert – kein negatives Signal erzeugt."}catch(error){$("#notice").textContent=error.message}};
$("#compare").onclick=()=>{remembered=result;$("#notice").textContent="Dieses Ergebnis ist für den nächsten direkten Vergleich gemerkt."};
$("#context-flip").onclick=()=>{remembered=result;$("#task").value="Ich suche heute Abend in Zürich eine lebhafte Bar mit Freunden.";$("#notice").textContent="Context Flip geladen. Bitte Situation erneut verstehen und auswerten."};
$("#expert").onclick=()=>{$("#expert-data").hidden=!$("#expert-data").hidden};
loadCohort().catch(error=>{$("#source-summary").textContent=`Lokaler Cohort-Zustand ungültig: ${error.message}`});
