const $=(s)=>document.querySelector(s); let interpretation=null; let result=null; let payload=null; let preview=null; let remembered=null;
const labels={ELIGIBLE_CONFIRMED:"Bestätigt passend",UNCONFIRMED_FALLBACK:"Könnte passen – wichtige Angabe fehlt",NOT_CONFIGURED:"Regel noch nicht freigegeben",INELIGIBLE:"Passt nicht zu einer zwingenden Bedingung",REJECTED:"Für diese Anfrage abgewählt"};
const words={"context.intent.food":"Essen","context.intent.drinks":"Etwas trinken","context.intent.coffee":"Kaffee","context.intent.conversation":"In Ruhe reden","context.intent.conflicting":"Widersprüchliche Absichten","context.occasion.first-date":"Erstes Date","context.occasion.family":"Familie","context.mood.quiet":"ruhig","context.mood.cozy":"gemütlich","context.mood.lively":"lebhaft",LOCATION_SCOPE:"Zielgebiet",ACCESSIBILITY:"Rollstuhlgerechter Zugang",BUDGET_MAXIMUM:"Maximales Budget",DISTANCE_MAXIMUM:"In der Nähe",AGE_OR_LEGAL:"Altersregel",OPENING_CURRENT:"Jetzt geöffnet",KITCHEN_CURRENT:"Küche geöffnet",MOOD:"gewünschte Stimmung",EXPLORATION:"etwas Neues",FAMILIARITY:"etwas Vertrautes",MIDDAY:"Mittag",EVENING:"Abend",MORNING:"Morgen",family:"Familie","partner-date":"Date oder Partner",friends:"Freunde",alone:"allein",SHORT:"kurz",MEDIUM:"mittel",LONG:"lang","blocking-world-conflict":"Zu diesem Spot liegen widersprüchliche Angaben vor.","rejected-in-current-session":"Für diese Anfrage bereits abgewählt.","soft-mood-world-evidence-not-available":"Zur gewünschten Stimmung liegen noch keine bestätigten Angaben vor."};
const reverse=Object.fromEntries(Object.entries(words).map(([key,value])=>[value,key])); const human=(value)=>words[value]||value; const code=(value)=>reverse[value]||value;
const dimensionNames={primaryIntent:"Hauptabsicht",secondaryIntent:"Nebenabsicht",occasion:"Anlass",moods:"Stimmung",targetCity:"Zielort",dateTime:"Zeit",group:"Begleitung",budget:"Budget",hardConstraints:"zwingende Bedingungen",softPreferences:"weiche Wünsche"};
const api=async(path,body)=>{const options=body===undefined?{}:{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)};const response=await fetch(path,options);const value=await response.json();if(!value.ok)throw new Error(value.message||value.code);return value.data};
const list=(id,value)=>{$(id).value=(value||[]).map(human).join("\n")}; const lines=(id)=>$(id).value.split(/\n|,/).map(value=>code(value.trim())).filter(Boolean);
const escapeHtml=(value)=>String(value).replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);
const humanError=(error)=>{const message=String(error?.message||error||"Unbekannter Fehler");if(/replay.*mismatch/.test(message))return"Der Replay stimmt nicht mit der aktuellen Aufgabe überein. Bitte erneut auswerten.";if(/unknown_field|unknown contract|contractVersion/.test(message))return"Diese Datei verwendet keinen unterstützten Founder-Cohort-Vertrag.";if(/scope/.test(message))return"Der Export besitzt nicht den erlaubten lokalen Founder-Evaluation-Scope.";if(/registry/.test(message))return"Die World-Knowledge-Registry dieses Exports wird vom Lab nicht unterstützt.";if(/snapshot|manifest|hash|integrity|binding/.test(message))return"Die Datei ist verändert oder ihre World-Snapshot-Bindung ist nicht vollständig gültig.";return message.replaceAll("_"," ")};
const setStatus=(message)=>{$("#action-status").textContent=message;$("#notice").textContent=message};
const invalidateInterpretation=(message)=>{interpretation=null;result=null;payload=null;$("#evaluate").disabled=true;$("#interpretation").hidden=true;$("#results").hidden=true;if(message)setStatus(message)};
const evaluationGaps=()=>{if(!interpretation)return["Situation wurde noch nicht verstanden."];const gaps=[];if(!code($("#primary").value))gaps.push("Hauptabsicht fehlt. Ergänze im Freitext oder im Feld „Hauptabsicht“, wonach du suchst.");if(!$("#target-city").value)gaps.push("Zielort fehlt. Ergänze eine Stadt im Freitext oder im Feld „Zielort“; ein Gerätestandort wird nicht automatisch zur Authority.");return gaps};
function updateEvaluability(){const gaps=evaluationGaps();$("#evaluate").disabled=gaps.length>0;$("#unclear").textContent=gaps.length?`Noch nicht auswertbar:\n${gaps.map(item=>`• ${item}`).join("\n")}\nOhne Hauptabsicht und autorisierten Zielort wäre eine pauschale Kandidatenauswertung nicht sinnvoll.`:interpretation?.unresolvedTerms.length?`Noch unklar: ${interpretation.unresolvedTerms.join(", ")}. Bitte korrigieren oder bewusst offen lassen.`:"Auswertbar. Keine erforderliche Angabe wurde still verworfen.";return gaps}
function currentPayload(extra={}){return{text:$("#task").value,tracking:$("#tracking").checked,deviceCity:$("#device-city").value,userMode:"NEUTRAL_MISSING",...extra}}
function corrections(){return{primaryIntent:code($("#primary").value)||null,secondaryIntent:code($("#secondary").value)||null,occasion:code($("#occasion").value)||null,moods:lines("#moods"),targetCity:$("#target-city").value||null,dateTime:{...interpretation.dateTime,dayPhase:code($("#day-phase").value)||null},budget:{...interpretation.budget,state:$("#budget").value?"KNOWN":"UNKNOWN",amount:$("#budget").value?Number($("#budget").value):null,currency:$("#budget").value?"CHF":null},stayDuration:$("#duration").value||null,group:{...interpretation.group,companionType:code($("#companion").value)||null,minimumAge:$("#minimum-age").value?Number($("#minimum-age").value):null,adultPresent:$("#adult-present").checked},hardConstraints:lines("#hard"),softPreferences:lines("#soft")}}
async function loadCohort(){const c=await api("/api/cohort");$("#source-badge").textContent=c.source==="FOUNDER_WORLD_COHORT"?"Founder World Cohort":"Synthetische Testwelt";const imported=c.importedAt?`Lokal aktiviert: ${new Date(c.importedAt).toLocaleString("de-CH")}`:"Kein Founder-Cohort importiert.";$("#source-summary").innerHTML=`<strong>${c.source==="FOUNDER_WORLD_COHORT"?"Echte lokale Founder-Testdaten":"Synthetische Testwelt"}</strong><p>${c.spotCount} Spot${c.spotCount===1?"":"s"}: ${c.names.map(escapeHtml).join(", ")}</p><p>${escapeHtml(imported)} Manifest: ${c.manifestValid?"vollständig gültig":"ungültig"}.</p>${c.singleSpot?'<p class="limitation">Der aktuelle Founder Cohort enthält nur einen Spot. Für einen aussagekräftigen Kandidatenvergleich sollten in World Knowledge weitere geprüfte Spots zum Founder Cohort hinzugefügt und erneut exportiert werden.</p>':""}`;}
$("#cohort-file").onchange=async(event)=>{try{const file=event.target.files?.[0];if(!file)return;setStatus(`Datei „${file.name}“ ausgewählt. Der Export wird lokal geprüft …`);const artifact=JSON.parse(await file.text());const data=await api("/api/cohort/preview",{artifact});preview={artifact,previewHash:data.previewHash};$("#preview-content").innerHTML=`<p><strong>${data.spotCount} Spot${data.spotCount===1?"":"s"}</strong>: ${data.names.map(escapeHtml).join(", ")}</p><p>Exportstand: ${escapeHtml(new Date(data.exportedAt).toLocaleString("de-CH"))}. Manifest vollständig gültig.</p>${data.singleSpot?'<p class="limitation">Ein Spot kann technisch geprüft werden, ist aber kein belastbarer Kandidatenvergleich.</p>':""}`;$("#cohort-preview").hidden=false;setStatus("Datei geprüft. Der Import erfolgt erst nach deiner Bestätigung.")}catch(error){preview=null;$("#cohort-preview").hidden=true;setStatus(`Cohort nicht übernommen: ${humanError(error)}`)}};
$("#confirm-import").onclick=async()=>{try{if(!preview)throw new Error("Bitte zuerst eine gültige Datei auswählen.");setStatus("Founder Cohort wird lokal aktiviert …");await api("/api/cohort/import",preview);preview=null;$("#cohort-preview").hidden=true;await loadCohort();invalidateInterpretation();setStatus("Founder World Cohort lokal aktiviert. World Knowledge wurde nicht verändert.")}catch(error){setStatus(humanError(error))}};
$("#synthetic").onclick=async()=>{setStatus("Wechsel zur synthetischen Testwelt …");await api("/api/cohort/synthetic",{});await loadCohort();invalidateInterpretation();setStatus("Bewusst zur synthetischen Testwelt gewechselt. Founder- und Fixture-Spots werden nicht gemischt.")};
$("#reset").onclick=async()=>{if(!confirm("Nur den lokalen Decision-Lab-Cohort zurücksetzen? World Knowledge bleibt unverändert."))return setStatus("Zurücksetzen abgebrochen.");setStatus("Lokaler Testzustand wird zurückgesetzt …");await api("/api/cohort/reset",{});await loadCohort();invalidateInterpretation();setStatus("Lokaler Lab-Zustand zurückgesetzt; keine World- oder User-Daten wurden verändert.")};
document.querySelectorAll(".preset").forEach(button=>button.onclick=()=>{$("#task").value=button.dataset.text;invalidateInterpretation("Vorbereitete Aufgabe geladen und frei korrigierbar. Bitte Situation verstehen.")});
$("#task").addEventListener("input",()=>invalidateInterpretation("Aufgabe geändert. Bitte die Situation erneut verstehen."));
$("#resolve").onclick=async()=>{try{
  if(!$("#task").value.trim())throw new Error("Bitte beschreibe zuerst deine Decision-Aufgabe.");
  setStatus("Situation wird lokal und ohne externe Dienste verstanden …");payload=currentPayload();interpretation=await api("/api/resolve",payload);
  $("#primary").value=human(interpretation.primaryIntent||"");$("#secondary").value=human(interpretation.secondaryIntent||"");$("#occasion").value=human(interpretation.occasion||"");list("#moods",interpretation.moods);$("#target-city").value=interpretation.targetCity||"";$("#day-phase").value=human(interpretation.dateTime.dayPhase||"");$("#budget").value=interpretation.budget.amount??"";$("#duration").value=interpretation.stayDuration||"";$("#companion").value=human(interpretation.group.companionType||"");$("#minimum-age").value=interpretation.group.minimumAge??"";$("#adult-present").checked=interpretation.group.adultPresent;list("#hard",interpretation.hardConstraints);list("#soft",interpretation.softPreferences);
  const group=[interpretation.group.companionType?human(interpretation.group.companionType):null,interpretation.group.minimumAge!==null?`genanntes Alter ${interpretation.group.minimumAge}`:null,interpretation.group.adultPresent?"erwachsene Begleitung":null].filter(Boolean).join(", ")||"nicht angegeben";
  const binding=interpretation.targetCity?`Zielort ${interpretation.targetCity} (zwingende Zielbindung)`:"keine ausdrücklich harte Bedingung erkannt";
  const hard=[binding,...interpretation.hardConstraints.map(human)].filter(Boolean).join(", ");
  $("#understood").innerHTML=`<h3>Was Backyrd verstanden hat</h3><div class="knowledge-box"><p><strong>Absicht:</strong> ${escapeHtml([interpretation.primaryIntent,interpretation.secondaryIntent].filter(Boolean).map(human).join(" + ")||"noch unklar")}</p><p><strong>Anlass und Stimmung:</strong> ${escapeHtml([interpretation.occasion,...interpretation.moods].filter(Boolean).map(human).join(", ")||"nicht angegeben")}</p><p><strong>Begleitung:</strong> ${escapeHtml(group)}</p><p><strong>Ziel:</strong> ${escapeHtml(interpretation.targetCity||"nicht bekannt")} · <strong>Zeit:</strong> ${escapeHtml(interpretation.dateTime.dayPhase?human(interpretation.dateTime.dayPhase):"nicht angegeben")} · <strong>Budget:</strong> ${interpretation.budget.amount?`${interpretation.budget.amount} CHF${interpretation.budget.perPerson?" pro Person":""}`:"nicht angegeben"}</p><p><strong>Zwingend:</strong> ${escapeHtml(hard)}</p><p><strong>Wunsch:</strong> ${escapeHtml(interpretation.softPreferences.length?interpretation.softPreferences.map(human).join(", "):"keine weichen Wünsche erkannt")}</p></div>`;
  $("#interpretation").hidden=false;const gaps=updateEvaluability();setStatus(gaps.length?"Situation ist noch nicht auswertbar. Ergänze die unten konkret genannten Pflichtangaben.":"Situation erkannt und auswertbar. Bitte prüfe und korrigiere sie vor der Auswertung.");
}catch(error){setStatus(humanError(error))}};
document.querySelectorAll("#interpretation input, #interpretation textarea, #interpretation select").forEach(control=>control.addEventListener("input",()=>{if(interpretation)updateEvaluability()}));
const displayGroup=(candidate)=>candidate.rejectionClass==="SITUATIONAL_REJECT"?"REJECTED":candidate.tier;
const coverageText=(candidate)=>({CONFIRMED:"Kernabsicht bestätigt",UNKNOWN:"Kernabsicht unbekannt – weder Ja noch Nein",NOT_CONFIGURED:"Zuordnung zur Kernabsicht noch nicht freigegeben",INCOMPATIBLE:"Kernabsicht nachweislich nicht erfüllt",NOT_APPLICABLE:"Keine Kernabsicht gebunden"})[candidate.coreIntentCoverage.state];
const founderReason=(reason)=>({
  "core-intent-confirmed":"Die Kernabsicht ist durch geprüfte Angaben zum Spot bestätigt.",
  "core-intent-unknown":"Für die Kernabsicht fehlt eine benötigte Angabe; unbekannt ist weder Ja noch Nein.",
  "core-intent-mapping-not-configured":"Die Zuordnung der Spot-Angaben zur Kernabsicht ist noch nicht freigegeben.",
  "core-intent-required":"Ohne eine klare Kernabsicht ist keine bestätigte Auswertung möglich.",
  "core-intent-incompatible":"Geprüfte Angaben belegen, dass der Spot die Kernabsicht nicht erfüllt.",
  "secondary-intent-mapping-not-configured":"Die Nebenabsicht bleibt sichtbar; ihre Zuordnung zu Spot-Angaben ist noch nicht freigegeben.",
  "soft-mood-evidence-unavailable":"Zur gewünschten Stimmung liegen noch keine bestätigten Angaben vor.",
  "situational-reject":"Dieser Spot wurde nur für diese Anfrage und Situation abgewählt; das ist keine objektive Unvereinbarkeit.",
  "user-projection-read-without-authority":"Minimierte Nutzerinformationen sind vorhanden, entscheiden hier aber weder über Ausschluss noch Reihenfolge.",
})[reason.reasonCode]||reason.statementDe.replaceAll("World-Auswertung","Auswertung der geprüften Spot-Angaben").replaceAll("World-Fakten","Spot-Angaben").replaceAll("World Knowledge","Weltwissen").replaceAll("Candidate-Auswertung","Kandidatenauswertung").replaceAll("Context","Situation");
const visibleReasons=(candidate)=>candidate.reasons.filter(item=>item.reasonCode!=="world-snapshot-authorized").map(founderReason);
function renderComparison(before,after){
  const dimensions=["primaryIntent","secondaryIntent","occasion","moods","targetCity","dateTime","group","budget","hardConstraints","softPreferences"];
  const changed=dimensions.filter(key=>JSON.stringify(before.interpretation[key])!==JSON.stringify(after.interpretation[key]));
  const unchangedCore=before.interpretation.primaryIntent===after.interpretation.primaryIntent;
  const unchangedHard=JSON.stringify(before.interpretation.hardConstraints)===JSON.stringify(after.interpretation.hardConstraints)&&before.interpretation.targetCity===after.interpretation.targetCity;
  const rows=after.candidates.map(candidate=>{const previous=before.candidates.find(item=>item.candidateId===candidate.candidateId);const oldReasons=previous?visibleReasons(previous):[];const nextReasons=visibleReasons(candidate);const added=nextReasons.filter(item=>!oldReasons.includes(item));const removed=oldReasons.filter(item=>!nextReasons.includes(item));return`<tr><th>${escapeHtml(candidate.label)}</th><td>${escapeHtml(previous?labels[displayGroup(previous)]:"nicht enthalten")}</td><td>${escapeHtml(labels[displayGroup(candidate)])}</td><td>${previous&&displayGroup(previous)===displayGroup(candidate)?"unverändert":"verändert"}</td><td>${escapeHtml(added.join(" · ")||"kein neuer Grund")}</td><td>${escapeHtml(removed.join(" · ")||"kein Grund entfallen")}</td></tr>`}).join("");
  $("#comparison").hidden=false;$("#comparison").innerHTML=`<h3>Direkter Vergleich je Spot</h3><p><strong>Kernabsicht:</strong> ${unchangedCore?"unverändert":"verändert"} · <strong>Zielort und zwingende Bedingungen:</strong> ${unchangedHard?"unverändert":"verändert"}</p><p><strong>Geänderte Situationsangaben:</strong> ${escapeHtml(changed.length?changed.map(key=>dimensionNames[key]).join(", "):"keine")}. Dies ist keine Aussage über eine bessere Reihenfolge oder Qualität.</p><div class="table-wrap"><table><thead><tr><th>Spot</th><th>Vorher</th><th>Jetzt</th><th>Status</th><th>Grund hinzu</th><th>Grund entfallen</th></tr></thead><tbody>${rows}</tbody></table></div>`;
}
function render(r){
  const groups=$("#candidate-groups");groups.innerHTML="";const counts=Object.fromEntries(Object.keys(labels).map(key=>[key,r.candidates.filter(candidate=>displayGroup(candidate)===key).length]));
  $("#summary").innerHTML=`<div class="summary">${Object.entries(counts).map(([key,count])=>`<div class="metric"><strong>${count}</strong>${labels[key]}</div>`).join("")}</div><p>${r.worldCohort.source==="SYNTHETIC_FALLBACK"?"Synthetische Testwelt – kein Founder Cohort gebunden.":"Founder World Cohort – lokal importiert und vollständig gebunden."}</p>${r.worldCohort.spotBindings.length===1?'<p class="limitation">Ein einzelner Spot ist technisch auswertbar, aber kein belastbarer Reihenfolge- oder Vergleichstest.</p>':""}<div class="claim-boundary"><strong>Was Backyrd ausdrücklich nicht behauptet:</strong> Unbekannte Angaben sind weder Ja noch Nein. Diese Auswertung ist keine freigegebene Produktsortierung und speichert nichts im langfristigen Nutzerwissen.</div>`;
  for(const [groupKey,title]of Object.entries(labels)){const rows=r.candidates.filter(candidate=>displayGroup(candidate)===groupKey);const section=document.createElement("div");section.className="group";section.dataset.group=groupKey;section.innerHTML=`<h3>${title} <span class="count">${rows.length}</span></h3><div class="cards">${rows.map(candidate=>`<article class="card ${groupKey==="ELIGIBLE_CONFIRMED"?"confirmed":groupKey==="UNCONFIRMED_FALLBACK"?"fallback":"ineligible"}" data-candidate-id="${escapeHtml(candidate.candidateId)}"><h4>${escapeHtml(candidate.label)}</h4><p class="core-intent">${escapeHtml(coverageText(candidate))}</p><p>${visibleReasons(candidate).map(escapeHtml).join(" ")}</p><ul><li>Zielort: ${candidate.confirmedHardConstraints.includes("LOCATION_SCOPE")?"bestätigt":candidate.failedHardConstraints.includes("LOCATION_SCOPE")?"nicht erfüllt":"unbekannt"}</li>${candidate.confirmedHardConstraints.filter(item=>item!=="LOCATION_SCOPE").map(item=>`<li>Bestätigt: ${escapeHtml(human(item))}</li>`).join("")}${candidate.unknownHardConstraints.map(item=>`<li>Unbekannt: ${escapeHtml(human(item))} – weder Ja noch Nein</li>`).join("")}${candidate.failedHardConstraints.filter(item=>item!=="LOCATION_SCOPE").map(item=>`<li>Zwingende Bedingung nicht erfüllt: ${escapeHtml(human(item))}</li>`).join("")}${candidate.matchedSoftPreferences.map(item=>`<li>Weicher Wunsch belegt: ${escapeHtml(human(item))}</li>`).join("")}${candidate.limitations.map(item=>`<li>Einschränkung: ${escapeHtml(human(item))}</li>`).join("")}</ul><button class="secondary reject" data-id="${escapeHtml(candidate.candidateId)}">Dieser Spot passt nicht</button></article>`).join("")}</div>`;groups.append(section)}
  $("#expert-data").textContent=JSON.stringify(r,null,2);$("#results").hidden=false;document.querySelectorAll(".reject").forEach(button=>button.onclick=async()=>{try{setStatus("Die Auswahl wird nur für diese Anfrage gespeichert …");payload={...payload,rejectedCandidateIds:[...new Set([...(payload.rejectedCandidateIds||[]),button.dataset.id])]};result=await api("/api/evaluate",payload);render(result);setStatus("Für diese Anfrage abgewählt; keine objektive Unvereinbarkeit und keine langfristige Nutzerpräferenz gespeichert.")}catch(error){setStatus(humanError(error))}});if(remembered)renderComparison(remembered,r);
}
$("#evaluate").onclick=async()=>{try{if(!interpretation)throw new Error("Bitte zuerst die Situation verstehen und prüfen.");const gaps=updateEvaluability();if(gaps.length)throw new Error("Die Situation ist noch nicht auswertbar. Ergänze Hauptabsicht und Zielort in den angezeigten Feldern.");setStatus("Founder-Spots werden gegen die geprüfte Situation ausgewertet …");payload={...currentPayload(),corrections:corrections()};result=await api("/api/evaluate",payload);render(result);setStatus("Auswertung abgeschlossen. Bestätigtes, Unbekanntes und nicht konfigurierte Regeln sind getrennt sichtbar.")}catch(error){setStatus(humanError(error))}};
$("#replay").onclick=async()=>{try{setStatus("Replay wird vollständig neu aufgebaut …");const replay=await api("/api/replay",{...payload,result});setStatus(replay.resultHash===result.resultHash?"Replay byte-identisch bestätigt.":"Replay abweichend – Ergebnis nicht bestätigt.")}catch(error){setStatus(humanError(error))}};
$("#alternative").onclick=async()=>{try{const before=result;setStatus("Weitere Alternative wird ohne negative Aussage über einen Spot geprüft …");payload={...currentPayload({alternativeRequested:true}),corrections:corrections()};result=await api("/api/evaluate",payload);render(result);const same=before&&before.candidates.map(displayGroup).join("|")===result.candidates.map(displayGroup).join("|");setStatus(`Weitere Alternative angefordert. Die sichtbaren Gruppen ${same?"bleiben ohne freigegebene Sortierlogik unverändert":"haben sich durch gebundene Fakten verändert"}; kein Spot wird dadurch negativ bewertet und keine langfristige Nutzerpräferenz gespeichert.`)}catch(error){setStatus(humanError(error))}};
$("#compare").onclick=()=>{remembered=result;setStatus("Dieses Ergebnis ist für den nächsten direkten Vergleich gemerkt.")};
$("#context-flip").onclick=()=>{if(!result||result.interpretation.primaryIntent!=="context.intent.drinks"||result.interpretation.targetCity!=="Basel"||!result.interpretation.moods.includes("context.mood.quiet")){$("#task").value="Ich möchte heute Abend in Basel ruhig etwas trinken, bei einem Date.";invalidateInterpretation("Kontrollierte Ausgangslage geladen: etwas trinken in Basel, ruhig beim Date. Bitte verstehen und auswerten; danach den Context Flip erneut wählen.");return}remembered=result;$("#task").value="Ich möchte heute Abend in Basel lebhaft etwas trinken, mit Freunden.";invalidateInterpretation("Kontrollierter Context Flip geladen: Kernabsicht, Zielort und harte Bedingungen bleiben gleich; Stimmung und Begleitung ändern sich.")};
$("#expert").onclick=()=>{$("#expert-data").hidden=!$("#expert-data").hidden;setStatus($("#expert-data").hidden?"Expertensicht geschlossen.":"Expertensicht geöffnet: technische Identitäten und Codes sind jetzt sichtbar.")};
loadCohort().then(()=>setStatus("Lokale Testwelt geladen. Wähle eine Aufgabe oder importiere einen Founder Cohort.")).catch(error=>{$("#source-summary").textContent=`Lokaler Cohort-Zustand ungültig: ${humanError(error)}`;setStatus("Lokaler Cohort-Zustand konnte nicht sicher geladen werden.")});
