\set ON_ERROR_STOP on
begin;
create function pg_temp.mu(p text)returns uuid language sql immutable as $$select(substr(md5(p),1,8)||'-'||substr(md5(p),9,4)||'-4'||substr(md5(p),14,3)||'-8'||substr(md5(p),18,3)||'-'||substr(md5(p),21,12))::uuid$$;
create function pg_temp.ok(p boolean,m text)returns void language plpgsql as $$begin if p is not true then raise exception 'Admin Metric V2 failed: %',m;end if;end$$;
create function pg_temp.actor(u uuid)returns void language plpgsql as $$begin perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);perform set_config('request.jwt.claim.sub',u::text,true);perform set_config('request.jwt.claim.role','authenticated',true);end$$;

do $$declare a uuid:=pg_temp.mu('metric-admin');u uuid:=pg_temp.mu('metric-user');begin
 insert into auth.users(instance_id,id,aud,role,email,encrypted_password,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)values
 ('00000000-0000-0000-0000-000000000000',a,'authenticated','authenticated','metric-admin@invalid','','{}','{}',now()-interval'60 days',now()),
 ('00000000-0000-0000-0000-000000000000',u,'authenticated','authenticated','metric-user@invalid','','{}','{}',now()-interval'60 days',now());
 update public.profiles set is_admin=true where id=a;insert into public.admin_users(user_id,role)values(a,'super_admin');perform pg_temp.actor(u);
end$$;
set local role authenticated;
do $$declare denied boolean:=false;begin
 begin perform public.admin_founder_overview_v2(now()-interval'7 days',now()+interval'1 minute');exception when insufficient_privilege then denied:=true;end;perform pg_temp.ok(denied,'normal user read Overview');
 denied:=false;begin perform public.founder_launch_overview_v2();exception when insufficient_privilege then denied:=true;end;perform pg_temp.ok(denied,'normal user read Founder Launch V2');
 denied:=false;begin perform public.admin_growth_intelligence_v2(now()-interval'7 days',now()+interval'1 minute');exception when insufficient_privilege then denied:=true;end;perform pg_temp.ok(denied,'normal user read Growth');
 denied:=false;begin perform public.admin_users_intelligence_v2(now()-interval'7 days',now()+interval'1 minute',10,0,null);exception when insufficient_privilege then denied:=true;end;perform pg_temp.ok(denied,'normal user read Users');
 denied:=false;begin perform public.admin_decision_intelligence_v2(now()-interval'7 days',now()+interval'1 minute',10);exception when insufficient_privilege then denied:=true;end;perform pg_temp.ok(denied,'normal user read Decisions');
 denied:=false;begin perform public.admin_moments_intelligence_v2(now()-interval'7 days',now()+interval'1 minute');exception when insufficient_privilege then denied:=true;end;perform pg_temp.ok(denied,'normal user read Moments');
 denied:=false;begin perform public.admin_partners_intelligence_v2(now()-interval'7 days',now()+interval'1 minute',10,null);exception when insufficient_privilege then denied:=true;end;perform pg_temp.ok(denied,'normal user read Partners');
 denied:=false;begin perform public.get_spot_claim_queue_v3(null,10);exception when insufficient_privilege then denied:=true;end;perform pg_temp.ok(denied,'normal user read Claims');
 denied:=false;begin perform public.admin_get_taxonomy_overview_v2();exception when insufficient_privilege then denied:=true;end;perform pg_temp.ok(denied,'normal user read Taxonomy metrics');
 denied:=false;begin perform public.admin_concepts_overview_v2();exception when insufficient_privilege then denied:=true;end;perform pg_temp.ok(denied,'normal user read Mood metrics');
 denied:=false;begin perform public.admin_get_spot_owner_moderation_queue_v2(null,10);exception when insufficient_privilege then denied:=true;end;perform pg_temp.ok(denied,'normal user read Trust moderation');
 denied:=false;begin perform 1 from public.admin_product_spot_universe_v2 limit 1;exception when insufficient_privilege then denied:=true;end;perform pg_temp.ok(denied,'normal user read internal Product view');
end$$;
reset role;select pg_temp.actor(pg_temp.mu('metric-admin'));set local role authenticated;

do $$
declare u uuid:=pg_temp.mu('metric-user');f uuid:=pg_temp.mu('metric-fixture');p uuid:=pg_temp.mu('metric-product');df uuid:=pg_temp.mu('metric-fixture-decision');dp uuid:=pg_temp.mu('metric-product-decision');postf uuid:=pg_temp.mu('metric-fixture-post');postp uuid:=pg_temp.mu('metric-product-post');cat uuid;tax uuid;concept bigint;
 fr timestamptz:=now()-interval'7 days';tt timestamptz:=now()+interval'1 minute';
 b1 jsonb;b2 jsonb;b3 jsonb;b4 jsonb;b5 jsonb;b6 jsonb;b7 jsonb;b8 jsonb;b9 jsonb;
 f1 jsonb;f2 jsonb;f3 jsonb;f4 jsonb;f5 jsonb;f6 jsonb;f7 jsonb;f8 jsonb;f9 jsonb;
 p1 jsonb;p2 jsonb;p3 jsonb;p4 jsonb;p5 jsonb;p6 jsonb;p7 jsonb;p8 jsonb;p9 jsonb;
 raw_reviews bigint;raw_events bigint;raw_claims bigint;raw_tax bigint;raw_moods bigint;raw_mod bigint;raw_decisions bigint;raw_impressions bigint;raw_posts bigint;raw_feed bigint;raw_reactions bigint;raw_comments bigint;raw_favorites bigint;raw_user_events bigint;base_tax_metric bigint;base_mood_metric bigint;
begin
 select id into cat from public.categories order by id limit 1;select id into tax from public.taxonomy_nodes order by id limit 1;select id into concept from public.mood_concepts order by id limit 1;
 b1:=public.founder_core_kpis_v2(tt);b2:=public.admin_founder_overview_v2(fr,tt);b3:=public.admin_growth_intelligence_v2(fr,tt);b4:=public.admin_users_intelligence_v2(fr,tt,1000,0,null);b5:=public.admin_user_detail_intelligence_v2(u,fr,tt);b6:=public.admin_decision_intelligence_v2(fr,tt,100);b7:=public.admin_moments_intelligence_v2(fr,tt);b8:=public.admin_partners_intelligence_v2(fr,tt,500,null);b9:=public.admin_spot_quality_v2(1000,0,null,'all');
 select count(*)into raw_reviews from public.reviews;select count(*)into raw_events from public.analytics_events;select count(*)into raw_claims from public.spot_claims;select count(*)into raw_tax from public.spot_taxonomies;select count(*)into raw_moods from public.spot_mood_concepts;select count(*)into raw_mod from public.spot_owner_change_events;
 select count(*)into raw_decisions from public.decision_sessions;select count(*)into raw_impressions from public.decision_impressions;select count(*)into raw_posts from public.social_posts;select count(*)into raw_feed from public.social_feed_events;select count(*)into raw_reactions from public.social_post_reactions;select count(*)into raw_comments from public.social_comments;select count(*)into raw_favorites from public.favorites;select count(*)into raw_user_events from public.user_events;
 if tax is not null then select spots_count into base_tax_metric from public.admin_get_taxonomy_overview_v2()where id=tax;end if;if concept is not null then select spots_count into base_mood_metric from public.admin_concepts_overview_v2()where id=concept;end if;
 insert into public.spots(id,name,address,city,country,lat,lng,status,category_id,data_origin,owner_id)values(f,'Metric Fixture','Fixture 1','Basel','Schweiz',47.55,7.59,'approved',cat,'FIXTURE',u);
 insert into public.reviews(spot_id,user_id,text,city,data_origin,review_origin)values(f,u,'fixture history','Basel','FIXTURE','FIXTURE');
 insert into public.analytics_events(user_id,event_name,spot_id,occurred_at)values(u,'spot_detail_opened',f,now()),(u,'decision_spot_impression',f,now()),(u,'feed_post_shared',f,now());
 insert into public.decision_sessions(id,user_id,city,created_at)values(df,u,'Basel',now());insert into public.decision_impressions(decision_id,spot_id,rank)values(df,f,1);
 insert into public.user_events(user_id,event_type,entity_type,entity_id)values(u,'spot_opened','spot',f);insert into public.favorites(user_id,spot_id)values(u,f);
 insert into public.social_posts(id,user_id,spot_id,caption)values(postf,u,f,'fixture post');insert into public.social_feed_events(user_id,post_id,spot_id,event_type)values(u,postf,f,'post_open');insert into public.social_post_reactions(post_id,user_id,reaction_type)values(postf,u,'like');insert into public.social_comments(post_id,user_id,body)values(postf,u,'fixture comment');
 insert into public.spot_claims(spot_id,user_id,status,submitted_at)values(f,u,'pending',now());insert into public.spot_owner_change_events(spot_id,changed_by,change_area,moderation_status)values(f,u,'profile','pending');
 if tax is not null then insert into public.spot_taxonomies(spot_id,taxonomy_node_id)values(f,tax);end if;if concept is not null then insert into public.spot_mood_concepts(spot_id,concept_id)values(f,concept);end if;
 f1:=public.founder_core_kpis_v2(tt);f2:=public.admin_founder_overview_v2(fr,tt);f3:=public.admin_growth_intelligence_v2(fr,tt);f4:=public.admin_users_intelligence_v2(fr,tt,1000,0,null);f5:=public.admin_user_detail_intelligence_v2(u,fr,tt);f6:=public.admin_decision_intelligence_v2(fr,tt,100);f7:=public.admin_moments_intelligence_v2(fr,tt);f8:=public.admin_partners_intelligence_v2(fr,tt,500,null);f9:=public.admin_spot_quality_v2(1000,0,null,'all');
 perform pg_temp.ok(f1->>'basel_launch_ready_spots'=b1->>'basel_launch_ready_spots'and f1->>'decisions_week'=b1->>'decisions_week','Fixture changed Founder');perform pg_temp.ok(f2#>>'{kpis,reviews}'=b2#>>'{kpis,reviews}'and f2#>>'{kpis,spot_opens}'=b2#>>'{kpis,spot_opens}'and f2#>>'{decision,sessions}'=b2#>>'{decision,sessions}','Fixture changed Overview');perform pg_temp.ok(f3#>>'{summary,active_users}'=b3#>>'{summary,active_users}','Fixture changed Growth');perform pg_temp.ok(f4#>>'{summary,active}'=b4#>>'{summary,active}','Fixture changed Users');perform pg_temp.ok(f5#>>'{metrics,spot_opens}'=b5#>>'{metrics,spot_opens}'and f5#>>'{metrics,reviews}'=b5#>>'{metrics,reviews}'and f5#>>'{metrics,decisions}'=b5#>>'{metrics,decisions}'and f5#>>'{metrics,favorites}'=b5#>>'{metrics,favorites}','Fixture changed User detail');perform pg_temp.ok(f6#>>'{summary,impressions}'=b6#>>'{summary,impressions}','Fixture changed Decisions');perform pg_temp.ok(f7#>>'{summary,shares}'=b7#>>'{summary,shares}'and f7#>>'{summary,posts}'=b7#>>'{summary,posts}'and f7#>>'{summary,likes}'=b7#>>'{summary,likes}'and f7#>>'{summary,comments}'=b7#>>'{summary,comments}','Fixture changed Moments');perform pg_temp.ok(f8#>>'{summary,partner_spots}'=b8#>>'{summary,partner_spots}','Fixture changed Partners');perform pg_temp.ok(f9->>'total'=b9->>'total','Fixture changed Quality');
 perform pg_temp.ok(not exists(select 1 from public.admin_review_spots_v2()where id=f),'Fixture changed Reviews');perform pg_temp.ok(not exists(select 1 from public.get_spot_claim_queue_v3(null,200)where spot_id=f),'Fixture changed Claims');perform pg_temp.ok(not exists(select 1 from public.admin_get_spot_owner_moderation_queue_v2(null,1000)where spot_id=f),'Fixture changed moderation');
 if tax is not null then perform pg_temp.ok((select spots_count from public.admin_get_taxonomy_overview_v2()where id=tax)=base_tax_metric,'Fixture changed taxonomy metric');end if;if concept is not null then perform pg_temp.ok((select spots_count from public.admin_concepts_overview_v2()where id=concept)=base_mood_metric,'Fixture changed mood metric');end if;
 insert into public.spots(id,name,address,city,country,lat,lng,status,category_id,data_origin,owner_id)values(p,'Metric Product','Product 1','Basel','Schweiz',47.56,7.60,'approved',cat,'REAL',u);
 insert into public.reviews(spot_id,user_id,text,city,data_origin,review_origin)values(p,u,'product history','Basel','REAL','STANDARD_REVIEW');insert into public.analytics_events(user_id,event_name,spot_id,occurred_at)values(u,'spot_detail_opened',p,now()),(u,'decision_spot_impression',p,now()),(u,'feed_post_shared',p,now());
 insert into public.decision_sessions(id,user_id,city,created_at)values(dp,u,'Basel',now());insert into public.decision_impressions(decision_id,spot_id,rank)values(dp,p,1);
 insert into public.user_events(user_id,event_type,entity_type,entity_id)values(u,'spot_opened','spot',p);insert into public.favorites(user_id,spot_id)values(u,p);
 insert into public.social_posts(id,user_id,spot_id,caption)values(postp,u,p,'product post');insert into public.social_feed_events(user_id,post_id,spot_id,event_type)values(u,postp,p,'post_open');insert into public.social_post_reactions(post_id,user_id,reaction_type)values(postp,u,'like');insert into public.social_comments(post_id,user_id,body)values(postp,u,'product comment');
 insert into public.spot_claims(spot_id,user_id,status,submitted_at)values(p,u,'pending',now());insert into public.spot_owner_change_events(spot_id,changed_by,change_area,moderation_status)values(p,u,'profile','pending');if tax is not null then insert into public.spot_taxonomies(spot_id,taxonomy_node_id)values(p,tax);end if;if concept is not null then insert into public.spot_mood_concepts(spot_id,concept_id)values(p,concept);end if;
 p1:=public.founder_core_kpis_v2(tt);p2:=public.admin_founder_overview_v2(fr,tt);p3:=public.admin_growth_intelligence_v2(fr,tt);p4:=public.admin_users_intelligence_v2(fr,tt,1000,0,null);p5:=public.admin_user_detail_intelligence_v2(u,fr,tt);p6:=public.admin_decision_intelligence_v2(fr,tt,100);p7:=public.admin_moments_intelligence_v2(fr,tt);p8:=public.admin_partners_intelligence_v2(fr,tt,500,null);p9:=public.admin_spot_quality_v2(1000,0,null,'all');
 perform pg_temp.ok((p1->>'basel_launch_ready_spots')::int=(f1->>'basel_launch_ready_spots')::int+1 and(p1->>'decisions_week')::int=(f1->>'decisions_week')::int+1,'Product did not change Founder');perform pg_temp.ok((p2#>>'{kpis,reviews}')::int=(f2#>>'{kpis,reviews}')::int+1 and(p2#>>'{kpis,spot_opens}')::int=(f2#>>'{kpis,spot_opens}')::int+1 and(p2#>>'{decision,sessions}')::int=(f2#>>'{decision,sessions}')::int+1,'Product did not change Overview');perform pg_temp.ok((p3#>>'{summary,active_users}')::int=(f3#>>'{summary,active_users}')::int+1,'Product did not change Growth');perform pg_temp.ok((p4#>>'{summary,active}')::int=(f4#>>'{summary,active}')::int+1,'Product did not change Users');perform pg_temp.ok((p5#>>'{metrics,spot_opens}')::int=(f5#>>'{metrics,spot_opens}')::int+3 and(p5#>>'{metrics,reviews}')::int=(f5#>>'{metrics,reviews}')::int+1 and(p5#>>'{metrics,decisions}')::int=(f5#>>'{metrics,decisions}')::int+1 and(p5#>>'{metrics,favorites}')::int=(f5#>>'{metrics,favorites}')::int+1,'Product did not change User detail');perform pg_temp.ok((p6#>>'{summary,impressions}')::int=(f6#>>'{summary,impressions}')::int+1,'Product did not change Decisions');perform pg_temp.ok((p7#>>'{summary,shares}')::int=(f7#>>'{summary,shares}')::int+1 and(p7#>>'{summary,posts}')::int=(f7#>>'{summary,posts}')::int+1 and(p7#>>'{summary,likes}')::int=(f7#>>'{summary,likes}')::int+1 and(p7#>>'{summary,comments}')::int=(f7#>>'{summary,comments}')::int+1,'Product did not change Moments');perform pg_temp.ok((p8#>>'{summary,partner_spots}')::int=(f8#>>'{summary,partner_spots}')::int+1,'Product did not change Partners');perform pg_temp.ok((p9->>'total')::int=(f9->>'total')::int+1,'Product did not change Quality');
 perform pg_temp.ok(exists(select 1 from public.admin_review_spots_v2()where id=p),'Product missing Reviews');perform pg_temp.ok(exists(select 1 from public.get_spot_claim_queue_v3(null,200)where spot_id=p),'Product missing Claims');perform pg_temp.ok(exists(select 1 from public.admin_get_spot_owner_moderation_queue_v2(null,1000)where spot_id=p),'Product missing moderation');
 if tax is not null then perform pg_temp.ok((select spots_count from public.admin_get_taxonomy_overview_v2()where id=tax)=base_tax_metric+1,'Product did not change taxonomy metric');end if;if concept is not null then perform pg_temp.ok((select spots_count from public.admin_concepts_overview_v2()where id=concept)=base_mood_metric+1,'Product did not change mood metric');end if;
 perform pg_temp.ok((select count(*)from public.reviews)=raw_reviews+2 and(select count(*)from public.analytics_events)=raw_events+6 and(select count(*)from public.spot_claims)=raw_claims+2,'raw history changed');perform pg_temp.ok((select count(*)from public.spot_taxonomies)=raw_tax+case when tax is null then 0 else 2 end,'taxonomy history changed');perform pg_temp.ok((select count(*)from public.spot_mood_concepts)=raw_moods+case when concept is null then 0 else 2 end,'mood history changed');perform pg_temp.ok((select count(*)from public.spot_owner_change_events)=raw_mod+2,'audit history changed');
 perform pg_temp.ok((select count(*)from public.decision_sessions)=raw_decisions+2 and(select count(*)from public.decision_impressions)=raw_impressions+2,'decision history changed');perform pg_temp.ok((select count(*)from public.social_posts)=raw_posts+2 and(select count(*)from public.social_feed_events)=raw_feed+2 and(select count(*)from public.social_post_reactions)=raw_reactions+2 and(select count(*)from public.social_comments)=raw_comments+2,'social history changed');perform pg_temp.ok((select count(*)from public.favorites)=raw_favorites+2 and(select count(*)from public.user_events)=raw_user_events+2,'user history changed');
 perform pg_temp.ok((select count(*)from public.admin_product_spot_universe_v2 where id in(f,p))=1,'Spot universe inconsistent');perform pg_temp.ok((select count(*)from public.admin_product_reviews_v2 where spot_id in(f,p))=1,'Review universe inconsistent');perform pg_temp.ok((select count(*)from public.admin_product_analytics_events_v2 where spot_id in(f,p))=3,'Event universe inconsistent');
 insert into public.spots(id,name,address,city,country,lat,lng,status,category_id,data_origin)
 select gen_random_uuid(),'Scale Product '||g,'Scale '||g,'Basel','Schweiz',47.55,7.59,'approved',cat,'REAL' from generate_series(1,10000)g;
 perform pg_temp.ok((public.admin_spot_quality_v2(50,0,'Scale Product','all')->>'filtered_total')::int=10000,'10K quality filtering failed');
 perform pg_temp.ok(jsonb_array_length(public.admin_spot_quality_v2(50,0,'Scale Product','all')->'rows')=50,'10K quality pagination failed');
 perform pg_temp.ok((public.admin_spots_operations_v2(fr,tt,50,0,'Scale Product','approved')->>'filtered_total')::int=10000,'10K Spot filtering failed');
 perform pg_temp.ok(jsonb_array_length(public.admin_spots_operations_v2(fr,tt,50,0,'Scale Product','approved')->'spots')=50,'10K Spot pagination failed');
end$$;
rollback;
