import { deepFreeze, withContentHash } from "./canonical.js";
import { DecisionProductEvaluationPolicySchema, DecisionProductEvaluationReleaseSchema, DecisionProductIntentPolicySchema, DecisionProductRankingPolicySchema, PRODUCT_DECISION_VERSIONS } from "./product-v1-contracts.js";

export type ProductV1Intent = "EAT" | "COFFEE" | "DRINKS" | "SPORT_MOVEMENT" | "NATURE_ANIMAL_EXPERIENCE" | "CULTURE_ART" | "ACTIVITY_EXPERIENCE";
export type ProductV1IntentMapping = { intentId: ProductV1Intent; acceptedPrimaryPurposes: readonly string[]; acceptedPrimaryCategories: readonly string[]; acceptedPlaceTypes: readonly string[]; incompatiblePrimaryPurposes: readonly string[]; incompatiblePrimaryCategories: readonly string[]; incompatiblePlaceTypes: readonly string[] };
const allPurposes = ["EAT_DRINK", "SPORT_MOVEMENT", "NATURE_ANIMAL_EXPERIENCE", "CULTURE_ART", "ACTIVITY_EXPERIENCE"] as const;
const map = (intentId: ProductV1Intent, acceptedPrimaryPurposes: readonly string[], acceptedPrimaryCategories: readonly string[], acceptedPlaceTypes: readonly string[]): ProductV1IntentMapping => ({ intentId, acceptedPrimaryPurposes, acceptedPrimaryCategories, acceptedPlaceTypes, incompatiblePrimaryPurposes: allPurposes.filter((value) => !acceptedPrimaryPurposes.includes(value)), incompatiblePrimaryCategories: ["EAT", "DRINKS", "COFFEE_DAYTIME", "SPORT_MOVEMENT", "NATURE_ANIMAL_EXPERIENCE", "CULTURE_ART", "ACTIVITY_EXPERIENCE"].filter((value) => !acceptedPrimaryCategories.includes(value)), incompatiblePlaceTypes: ["RESTAURANT", "CAFE", "PUB", "WINE_BAR", "BAR", "CLIMBING_GYM", "PARK", "ZOO", "MUSEUM", "ACTIVITY_VENUE"].filter((value) => !acceptedPlaceTypes.includes(value)) });
export const PRODUCT_V1_INTENT_MAPPINGS: readonly ProductV1IntentMapping[] = deepFreeze([
  map("EAT", ["EAT_DRINK"], ["EAT"], ["RESTAURANT", "BRASSERIE", "BISTRO"]), map("COFFEE", ["EAT_DRINK"], ["COFFEE_DAYTIME"], ["CAFE"]),
  map("DRINKS", ["EAT_DRINK"], ["DRINKS", "NIGHTLIFE"], ["PUB", "WINE_BAR", "BAR", "BREWERY", "TAPROOM", "COCKTAIL_BAR", "LOUNGE"]), map("SPORT_MOVEMENT", ["SPORT_MOVEMENT"], ["SPORT_MOVEMENT"], ["CLIMBING_GYM", "GYM", "SPORTS_CENTRE", "SPORTS_COURT"]),
  map("NATURE_ANIMAL_EXPERIENCE", ["NATURE_ANIMAL_EXPERIENCE"], ["OUTDOOR_NATURE"], ["PARK", "NATURE_RESERVE", "ZOO", "AQUARIUM"]),
  map("CULTURE_ART", ["CULTURE_ART"], ["CULTURE_ART"], ["MUSEUM"]), map("ACTIVITY_EXPERIENCE", ["ACTIVITY_EXPERIENCE"], ["ACTIVITY_EXPERIENCE"], ["ACTIVITY_VENUE"]),
]);
export const DECISION_PRODUCT_INTENT_POLICY = deepFreeze(DecisionProductIntentPolicySchema.parse(withContentHash({ contractVersion: PRODUCT_DECISION_VERSIONS.intentPolicy, policyId: "decision-vnext-product-intent-policy-v1", scope: "PRODUCT_V1", mappings: PRODUCT_V1_INTENT_MAPPINGS, precedence: "SPECIFIC_CONFIRM_THEN_SPECIFIC_INCOMPATIBLE_THEN_UNKNOWN", embeddedOfferingsConfirmPrimaryIntent: false, generalEatDrinkConfirmsSpecificIntent: false, commercialSignalsForbidden: true }, "policyHash")));
export const DECISION_PRODUCT_RANKING_POLICY = deepFreeze(DecisionProductRankingPolicySchema.parse(withContentHash({ contractVersion: PRODUCT_DECISION_VERSIONS.rankingPolicy, policyId: "decision-vnext-product-lexicographic-ranking-v1", precedence: ["HARD_CONSTRAINTS", "ELIGIBILITY_TIER", "CORE_INTENT_COVERAGE", "PRIMARY_VISIT_PURPOSE", "ACTUAL_AVAILABILITY", "CONSENTED_USER_RELEVANCE", "SITUATIONAL_CONTEXT_FIT", "WORLD_EVIDENCE", "NEUTRAL_IDENTITY"], userSignals: ["DIRECT_SPOT_POSITIVE"], commercialSignalsForbidden: true, fixtureOrderForbidden: true, spotNameForbidden: true }, "policyHash")));
export const DECISION_PRODUCT_EVALUATION_POLICY = deepFreeze(DecisionProductEvaluationPolicySchema.parse(withContentHash({ contractVersion: PRODUCT_DECISION_VERSIONS.evaluationPolicy, policyId: "decision-vnext-product-evaluation-policy-v1", scope: "PRODUCT_DECISION", requiresCanonicalWorldPort: true, requiresCanonicalUserProjectionPort: true, requiresVerifiedContext: true, founderLabAuthorityAccepted: false, syntheticFixtureAuthorityAccepted: false, hardConstraintsBeforeRanking: true }, "policyHash")));
export const DECISION_PRODUCT_EVALUATION_RELEASE = deepFreeze(DecisionProductEvaluationReleaseSchema.parse(withContentHash({ contractVersion: PRODUCT_DECISION_VERSIONS.evaluationRelease, releaseId: "decision-vnext-product-evaluation-release-v1", evaluationPolicyHash: DECISION_PRODUCT_EVALUATION_POLICY.policyHash, rankingPolicyHash: DECISION_PRODUCT_RANKING_POLICY.policyHash, intentPolicyHash: DECISION_PRODUCT_INTENT_POLICY.policyHash, productSemanticsApproved: true, productRankingAuthorized: true, runtimeActivated: false, productionExecutionAuthorized: false }, "releaseHash")));
