import { ProductDecisionLearningInputSchema, RelevantUserProjectionSchema } from "@backyrd/user-intelligence-vnext-core";
import { identifier, schema, sha256, timestamp, version, type Infer } from "./schema.js";

export const PRODUCT_DECISION_VERSIONS = Object.freeze({
  request: "backyrd.decision-vnext.product-request@1.0", interactionRequest: "backyrd.decision-vnext.product-interaction-request@1.0", interactionResponse: "backyrd.decision-vnext.product-interaction-response@1.0", context: "backyrd.decision-vnext.product-context@1.0", cohort: "backyrd.decision-vnext.product-world-cohort@1.0",
  assessment: "backyrd.decision-vnext.product-candidate-assessment@1.0", intentPolicy: "backyrd.decision-vnext.product-intent-policy@1.0",
  response: "backyrd.decision-vnext.product-response@1.0", envelope: "backyrd.decision-vnext.product-envelope@1.0", rankingPolicy: "backyrd.decision-vnext.product-ranking-policy@1.0",
  evaluation: "backyrd.decision-vnext.product-evaluation@1.0", evaluationPolicy: "backyrd.decision-vnext.product-evaluation-policy@1.0", evaluationRelease: "backyrd.decision-vnext.product-evaluation-release@1.0",
  presentation: "backyrd.decision-vnext.product-presentation@1.0", error: "backyrd.decision-vnext.product-error@1.0",
} as const);
const nullableId = schema.union([identifier, schema.literal(null)] as const);
const nullableText = schema.union([schema.string({ min: 1, max: 500 }), schema.literal(null)] as const);
const nullableInt = schema.union([schema.number({ integer: true, min: 0, max: 100_000 }), schema.literal(null)] as const);
const nullableRank = schema.union([schema.number({ integer: true, min: 1, max: 1000 }), schema.literal(null)] as const);
const ref = schema.string({ min: 1, max: 200, pattern: /^[A-Za-z0-9][A-Za-z0-9_.:@/-]*$/ });
const knowledge = schema.enum(["KNOWN", "UNKNOWN", "NOT_CONFIGURED", "NOT_AVAILABLE", "DENIED"] as const);
const coverageState = schema.enum(["CONFIRMED", "UNKNOWN", "NOT_CONFIGURED", "INCOMPATIBLE", "DISPUTED", "NOT_APPLICABLE"] as const);
const tier = schema.enum(["ELIGIBLE_CONFIRMED", "UNCONFIRMED_FALLBACK", "NOT_CONFIGURED", "INELIGIBLE"] as const);
const availability = schema.enum(["open", "closed", "unknown", "not_authorized", "expired", "disputed", "not_requested"] as const);
const group = schema.object({ size: nullableInt, minimumAge: nullableInt, adultPresent: schema.boolean(), companionType: nullableId });
const budget = schema.object({ state: knowledge, amount: nullableInt, currency: schema.union([schema.literal("CHF"), schema.literal(null)] as const), perPerson: schema.boolean(), calibrationLabel: nullableId });
const dateTime = schema.object({ state: knowledge, localDate: schema.union([schema.string({ pattern: /^\d{4}-\d{2}-\d{2}$/ }), schema.literal(null)] as const), dayPhase: nullableId, timeZone: schema.union([schema.string({ min: 1, max: 80 }), schema.literal(null)] as const) });

export const DecisionProductExplicitContextSchema = schema.object({ primaryIntent: schema.optional(nullableId), secondaryIntent: schema.optional(nullableId), occasion: schema.optional(nullableId), moods: schema.optional(schema.array(identifier, { max: 12 })), targetCity: schema.optional(nullableId), dateTime: schema.optional(dateTime), group: schema.optional(group), budget: schema.optional(budget), stayDuration: schema.optional(schema.union([schema.enum(["SHORT", "MEDIUM", "LONG"] as const), schema.literal(null)] as const)), hardConstraints: schema.optional(schema.array(identifier, { max: 30 })), softPreferences: schema.optional(schema.array(identifier, { max: 30 })) });
export type DecisionProductExplicitContext = Infer<typeof DecisionProductExplicitContextSchema>;
export const DecisionProductRequestSchema = schema.object({ contractVersion: version(PRODUCT_DECISION_VERSIONS.request), requestId: identifier, idempotencyKey: identifier, naturalLanguage: schema.string({ min: 1, max: 2_000 }), explicit: DecisionProductExplicitContextSchema, alternativeRequested: schema.boolean(), previouslyPresentedCandidateIds: schema.array(identifier, { max: 50 }), rejectedCandidateIds: schema.array(identifier, { max: 50 }) });
export type DecisionProductRequest = Infer<typeof DecisionProductRequestSchema>;
export const DecisionProductInteractionRequestSchema = schema.object({ contractVersion: version(PRODUCT_DECISION_VERSIONS.interactionRequest), actionId: identifier, idempotencyKey: identifier, decisionId: identifier, eventType: schema.enum(["candidate_impression", "candidate_opened"] as const), candidateId: identifier });
export type DecisionProductInteractionRequest = Infer<typeof DecisionProductInteractionRequestSchema>;
export const DecisionProductInteractionResponseSchema = schema.object({ contractVersion: version(PRODUCT_DECISION_VERSIONS.interactionResponse), status: schema.literal("ACKNOWLEDGED"), decisionId: identifier, candidateId: identifier, eventType: schema.enum(["candidate_impression", "candidate_opened"] as const), legacyWriteUsed: schema.literal(false), fallbackUsed: schema.literal(false) });
export type DecisionProductInteractionResponse = Infer<typeof DecisionProductInteractionResponseSchema>;
export const DecisionProductContextSchema = schema.object({ contractVersion: version(PRODUCT_DECISION_VERSIONS.context), resolverVersion: identifier, inputHash: sha256, primaryIntent: nullableId, secondaryIntent: nullableId, intentCompatibility: schema.enum(["COMPATIBLE", "INCOMPATIBLE", "NOT_APPLICABLE", "UNKNOWN"] as const), occasion: nullableId, moods: schema.array(identifier, { max: 12 }), targetCity: nullableId, dateTime, group, budget, stayDuration: schema.union([schema.enum(["SHORT", "MEDIUM", "LONG"] as const), schema.literal(null)] as const), hardConstraints: schema.array(identifier, { max: 30 }), softPreferences: schema.array(identifier, { max: 30 }), unresolvedTerms: schema.array(schema.string({ min: 1, max: 120 }), { max: 30 }), locationAuthority: schema.object({ explicitTargetWins: schema.literal(true), authorizedCity: nullableId, deviceCityUsed: schema.boolean(), state: knowledge }), limitations: schema.array(identifier, { max: 30 }), rawTextPersisted: schema.literal(false), interpretationHash: sha256 });
export type DecisionProductContext = Infer<typeof DecisionProductContextSchema>;
export const DecisionProductWorldCohortSchema = schema.object({ contractVersion: version(PRODUCT_DECISION_VERSIONS.cohort), cohortId: identifier, source: schema.literal("CANONICAL_WORLD_KNOWLEDGE_READER"), generatedAt: timestamp, authorizedCity: identifier, worldRegistryVersion: ref, worldRegistryHash: sha256, sourcePolicyVersion: ref, sourcePolicyHash: sha256, spotBindings: schema.array(schema.object({ spotId: identifier, snapshotHash: sha256 }), { min: 1, max: 1000 }), candidateSetHash: sha256, limitations: schema.array(identifier, { max: 20 }), commercialSignalsPresent: schema.literal(false), fixtureSourceUsed: schema.literal(false), cohortHash: sha256 });
export type DecisionProductWorldCohort = Infer<typeof DecisionProductWorldCohortSchema>;
export const DecisionProductIntentPolicySchema = schema.object({
  contractVersion: version(PRODUCT_DECISION_VERSIONS.intentPolicy), policyId: identifier, scope: schema.literal("PRODUCT_V1"),
  mappings: schema.array(schema.object({ intentId: identifier, acceptedPrimaryPurposes: schema.array(identifier, { max: 20 }), acceptedPrimaryCategories: schema.array(identifier, { max: 20 }), acceptedPlaceTypes: schema.array(identifier, { max: 30 }), incompatiblePrimaryPurposes: schema.array(identifier, { max: 30 }), incompatiblePrimaryCategories: schema.array(identifier, { max: 30 }), incompatiblePlaceTypes: schema.array(identifier, { max: 50 }) }), { min: 7, max: 9 }),
  precedence: schema.literal("SPECIFIC_CONFIRM_THEN_SPECIFIC_INCOMPATIBLE_THEN_UNKNOWN"), embeddedOfferingsConfirmPrimaryIntent: schema.literal(false),
  generalEatDrinkConfirmsSpecificIntent: schema.literal(false), commercialSignalsForbidden: schema.literal(true), policyHash: sha256,
});
const reason = schema.object({ reasonCode: identifier, domain: schema.enum(["WORLD", "USER", "CONTEXT", "LIMITATION"] as const), sourceHash: sha256, statementDe: schema.string({ min: 1, max: 500 }), confirmed: schema.boolean() });
const coverage = schema.object({ intentId: nullableId, state: coverageState, mappingIds: schema.array(identifier, { max: 20 }), worldFactKeys: schema.array(identifier, { max: 20 }), evidenceSourceHash: sha256 });
const contextual = schema.object({ state: coverageState, mappingIds: schema.array(identifier, { max: 20 }), evidenceSourceHash: sha256 });
const onsite = schema.object({ state: coverageState, mappingIds: schema.array(identifier, { max: 20 }), availableKinds: schema.array(identifier, { max: 20 }), matchedKinds: schema.array(identifier, { max: 20 }), relationships: schema.array(schema.enum(["PART_OF_SPOT", "EMBEDDED_FACILITY", "UNKNOWN"] as const), { max: 3 }), confirmsCoreIntent: schema.literal(false), evidenceSourceHash: sha256 });
export const DecisionProductCandidateAssessmentSchema = schema.object({ contractVersion: version(PRODUCT_DECISION_VERSIONS.assessment), candidateId: identifier, snapshotHash: sha256, tier, coreIntentCoverage: coverage, secondaryIntentCoverage: coverage, worldClassification: schema.object({ primaryVisitPurpose: nullableId, primaryCategory: nullableId, placeTypes: schema.array(identifier, { max: 20 }), evidenceSourceHash: sha256 }), primaryVisitPurpose: contextual, specificCoreClassification: contextual, onsiteOfferings: onsite, visitSituation: contextual, atmosphere: contextual, typicalDaypart: contextual, actualAvailability: schema.object({ status: availability, evidenceSourceHash: sha256 }), confirmedHardConstraints: schema.array(identifier, { max: 30 }), unknownHardConstraints: schema.array(identifier, { max: 30 }), failedHardConstraints: schema.array(identifier, { max: 30 }), matchedSoftPreferences: schema.array(identifier, { max: 30 }), conflicts: schema.array(identifier, { max: 20 }), reasons: schema.array(reason, { min: 1, max: 60 }), limitations: schema.array(identifier, { max: 30 }), rejectionClass: schema.enum(["NONE", "SITUATIONAL_REJECT"] as const), userIntelligenceInvolved: schema.boolean(), userIntelligenceAffectsEligibility: schema.literal(false), neutralTieBreakerHash: sha256, assessmentHash: sha256 });
export type DecisionProductCandidateAssessment = Infer<typeof DecisionProductCandidateAssessmentSchema>;

export const DecisionProductPresentationSchema = schema.object({ contractVersion: version(PRODUCT_DECISION_VERSIONS.presentation), spotId: identifier, name: schema.string({ min: 1, max: 160 }), locality: nullableId, categoryLabel: nullableText, imageUrl: schema.union([schema.string({ min: 1, max: 2_000, pattern: /^https:\/\// }), schema.literal(null)] as const), sourceHash: sha256, presentationHash: sha256 });
export type DecisionProductPresentation = Infer<typeof DecisionProductPresentationSchema>;
export const DecisionProductRankingPolicySchema = schema.object({ contractVersion: version(PRODUCT_DECISION_VERSIONS.rankingPolicy), policyId: identifier, precedence: schema.array(schema.enum(["HARD_CONSTRAINTS", "ELIGIBILITY_TIER", "CORE_INTENT_COVERAGE", "ACTUAL_AVAILABILITY", "CONSENTED_USER_RELEVANCE", "SITUATIONAL_CONTEXT_FIT", "WORLD_EVIDENCE", "NEUTRAL_IDENTITY"] as const), { min: 8, max: 8 }), userSignals: schema.array(schema.enum(["DIRECT_SPOT_POSITIVE"] as const), { min: 1, max: 1 }), commercialSignalsForbidden: schema.literal(true), fixtureOrderForbidden: schema.literal(true), spotNameForbidden: schema.literal(true), policyHash: sha256 });
export const DecisionProductEvaluationPolicySchema = schema.object({ contractVersion: version(PRODUCT_DECISION_VERSIONS.evaluationPolicy), policyId: identifier, scope: schema.literal("PRODUCT_DECISION"), requiresCanonicalWorldPort: schema.literal(true), requiresCanonicalUserProjectionPort: schema.literal(true), requiresVerifiedContext: schema.literal(true), founderLabAuthorityAccepted: schema.literal(false), syntheticFixtureAuthorityAccepted: schema.literal(false), hardConstraintsBeforeRanking: schema.literal(true), policyHash: sha256 });
export const DecisionProductEvaluationReleaseSchema = schema.object({ contractVersion: version(PRODUCT_DECISION_VERSIONS.evaluationRelease), releaseId: identifier, evaluationPolicyHash: sha256, rankingPolicyHash: sha256, intentPolicyHash: sha256, productSemanticsApproved: schema.literal(true), productRankingAuthorized: schema.literal(true), runtimeActivated: schema.literal(false), productionExecutionAuthorized: schema.literal(false), releaseHash: sha256 });
export const DecisionProductEvaluationSchema = schema.object({ contractVersion: version(PRODUCT_DECISION_VERSIONS.evaluation), evaluationId: identifier, createdAt: timestamp, requestHash: sha256, interpretation: DecisionProductContextSchema, worldCohort: DecisionProductWorldCohortSchema, userProjectionHash: sha256, candidates: schema.array(DecisionProductCandidateAssessmentSchema, { max: 1000 }), limitations: schema.array(identifier, { max: 50 }), evaluatorVersion: ref, evaluationPolicyHash: sha256, evaluationReleaseHash: sha256, intentPolicyHash: sha256, sourceKind: schema.literal("CANONICAL_PRODUCT_PORTS"), productSemanticsApproved: schema.literal(true), productRankingAuthorized: schema.literal(true), fixtureSourceUsed: schema.literal(false), evaluationHash: sha256 });
export type DecisionProductEvaluation = Infer<typeof DecisionProductEvaluationSchema>;
const rankVector = schema.object({ hardConstraintState: schema.enum(["PASS", "UNKNOWN", "FAIL"] as const), eligibilityTier: tier, coreIntentState: coverageState, actualAvailability: availability, userRelevance: schema.object({ state: schema.enum(["POSITIVE_DIRECT", "NEUTRAL"] as const), confidence: schema.number({ min: 0, max: 1 }), sourceHash: sha256 }), contextFit: schema.object({ secondaryIntentConfirmed: schema.boolean(), visitSituationConfirmed: schema.boolean(), matchedSoftPreferenceCount: schema.number({ integer: true, min: 0, max: 30 }), atmosphereConfirmed: schema.boolean(), typicalDaypartConfirmed: schema.boolean() }), worldEvidence: schema.object({ conflictFree: schema.boolean(), confirmedReasonCount: schema.number({ integer: true, min: 0, max: 60 }) }), neutralIdentity: sha256, vectorHash: sha256 });
const responseReason = schema.object({ code: identifier, domain: schema.enum(["WORLD", "USER", "CONTEXT", "ELIGIBILITY", "RANKING", "LIMITATION"] as const), sourceHash: sha256, statement: schema.string({ min: 1, max: 500 }), confirmed: schema.boolean() });
export const DecisionProductCandidateSchema = schema.object({ spotId: identifier, presentation: DecisionProductPresentationSchema, tier, rank: nullableRank, coreIntentCoverage: coverageState, actualAvailability: availability, confirmedHardConstraints: schema.array(identifier, { max: 30 }), unknownHardConstraints: schema.array(identifier, { max: 30 }), failedHardConstraints: schema.array(identifier, { max: 30 }), rankVector, reasons: schema.array(responseReason, { min: 1, max: 80 }), limitations: schema.array(identifier, { max: 40 }), contextualReject: schema.boolean(), candidateHash: sha256 });
export const DecisionProductResponseSchema = schema.object({ contractVersion: version(PRODUCT_DECISION_VERSIONS.response), status: schema.literal("AVAILABLE"), decisionId: identifier, requestHash: sha256, envelopeHash: sha256, rankingPolicyVersion: version(PRODUCT_DECISION_VERSIONS.rankingPolicy), rankingPolicyHash: sha256, interpretation: DecisionProductContextSchema, primaryCandidateId: nullableId, candidates: schema.array(DecisionProductCandidateSchema, { max: 1000 }), limitations: schema.array(identifier, { max: 60 }), alternative: schema.object({ requested: schema.boolean(), selectedCandidateId: nullableId, negativeSignalProduced: schema.literal(false) }), reject: schema.object({ candidateIds: schema.array(identifier, { max: 50 }), contextualOnly: schema.literal(true), worldFactProduced: schema.literal(false) }), personalization: schema.object({ state: schema.enum(["ACTIVE", "NEUTRAL"] as const), neutralReason: nullableId, projectionHash: sha256 }), learning: schema.object({ mode: schema.enum(["CONSENT_BOUND_EVENTS", "DISABLED_NEUTRAL"] as const), acknowledgement: schema.enum(["CONSENT_BOUND_IDEMPOTENT", "NOT_APPLICABLE_NEUTRAL"] as const), eventCount: schema.number({ integer: true, min: 0, max: 52 }), rawTextIncluded: schema.literal(false) }), productOutputAuthorized: schema.literal(true), legacyEngineUsed: schema.literal(false), fallbackUsed: schema.literal(false), resultHash: sha256 });
export type DecisionProductResponse = Infer<typeof DecisionProductResponseSchema>;
export const DecisionProductExecutionEnvelopeSchema = schema.object({ contractVersion: version(PRODUCT_DECISION_VERSIONS.envelope), decisionId: identifier, requestHash: sha256, idempotencyIdentityHash: sha256, actor: schema.object({ subjectBindingHash: sha256, authenticationContextHash: sha256, sessionBindingHash: sha256, boundBy: schema.literal("SERVER") }), authority: schema.object({ serverTime: timestamp, authorizedCity: identifier, locationBindingHash: sha256, purpose: schema.literal("PRODUCT_DECISION"), transportSlug: schema.literal("decision-v13") }), bindings: schema.object({ worldCohortHash: sha256, userProjectionHash: sha256, contextHash: sha256, rankingPolicyHash: sha256, evaluatorContractVersion: ref }), boundaries: schema.object({ authenticatedAccountsOnly: schema.literal(true), founderAllowlistUsed: schema.literal(false), legacyEngineUsed: schema.literal(false), fallbackUsed: schema.literal(false), hardConstraintsBeforeRanking: schema.literal(true), userProjectionEligibilityAuthority: schema.literal(false), commercialInfluence: schema.literal(false) }), envelopeHash: sha256 });
export const DecisionProductExecutionSchema = schema.object({ response: DecisionProductResponseSchema, envelope: DecisionProductExecutionEnvelopeSchema, projection: RelevantUserProjectionSchema, learningEvents: schema.array(ProductDecisionLearningInputSchema, { max: 52 }) });
export type DecisionProductExecution = Infer<typeof DecisionProductExecutionSchema>;
