import { CONTRACT_VERSIONS } from "./contracts.js";

// Runtime schemas are the normative validators. This catalog makes discovery and
// compatibility checks machine-readable without maintaining a second validator.
export const USER_INTELLIGENCE_VNEXT_SCHEMA_CATALOG = Object.freeze({
  catalogVersion: "backyrd.user-intelligence.schema-catalog@1.0",
  additionalPropertiesDefault: false,
  compatibility: {
    major: "EXACT_MATCH_FAIL_CLOSED",
    minor: "ONLY_EXPLICITLY_LISTED_MINOR_VERSIONS_ARE_ACCEPTED",
    unknownRegistry: "FAIL_CLOSED",
  },
  contracts: Object.freeze([
    ["CanonicalUserEvent", CONTRACT_VERSIONS.canonicalUserEvent, "CanonicalUserEventSchema", "parseCanonicalUserEvent"],
    ["EventReferencePolicy", CONTRACT_VERSIONS.eventReferencePolicy, "EVENT_REFERENCE_MATRIX", null],
    ["TemporalBinding", CONTRACT_VERSIONS.temporalValidation, "TemporalBindingSchema", null],
    ["TemporalValidationPolicy", CONTRACT_VERSIONS.temporalPolicy, "TemporalValidationPolicySchema", "validateTemporalIntegrity"],
    ["UserEventAuthority", CONTRACT_VERSIONS.userEventAuthority, "UserEventAuthoritySchema", "parseUserEventAuthority"],
    ["ConsentEnvelope", CONTRACT_VERSIONS.consentEnvelope, "ConsentEnvelopeSchema", "parseConsentEnvelope"],
    ["EvidenceChain", CONTRACT_VERSIONS.evidenceChain, "EvidenceChainSchema", "parseEvidenceChain"],
    ["UserConceptReference", CONTRACT_VERSIONS.userConceptReference, "UserConceptReferenceSchema", null],
    ["TasteNode", CONTRACT_VERSIONS.tasteNode, "TasteNodeSchema", null],
    ["PracticalPreference", CONTRACT_VERSIONS.practicalPreference, "PracticalPreferenceSchema", null],
    ["DirectSpotAffinity", CONTRACT_VERSIONS.directSpotAffinity, "DirectSpotAffinitySchema", null],
    ["UserIntelligenceManifest", CONTRACT_VERSIONS.manifest, "UserIntelligenceManifestSchema", "parseUserIntelligenceManifest"],
    ["UserIntelligenceSnapshot", CONTRACT_VERSIONS.snapshot, "UserIntelligenceSnapshotSchema", "parseUserIntelligenceSnapshot"],
    ["RelevantUserProjectionRequest", CONTRACT_VERSIONS.projectionRequest, "RelevantUserProjectionRequestSchema", null],
    ["RelevantUserProjection", CONTRACT_VERSIONS.projection, "RelevantUserProjectionSchema", "parseRelevantUserProjection"],
    ["UserTransparencyView", CONTRACT_VERSIONS.transparencyView, "UserTransparencyViewSchema", null],
    ["LifecycleCommand", CONTRACT_VERSIONS.lifecycleCommand, "LifecycleCommandSchema", "parseLifecycleCommand"],
    ["CanonicalEventCatalog", CONTRACT_VERSIONS.canonicalEventCatalog, "CANONICAL_EVENT_CATALOG", "assertConfiguredEventSemantics"],
    ["JourneyResolution", CONTRACT_VERSIONS.journeyResolution, "JourneyResolutionSchema", "parseJourneyResolution"],
    ["Deduplication", CONTRACT_VERSIONS.deduplication, "DeduplicationRecordSchema", "deduplicateCanonicalEvents"],
    ["EvidenceChainV2", CONTRACT_VERSIONS.evidenceChainV2, "EvidenceChainV2Schema", "verifyEvidenceChainV2"],
    ["WorldEvidenceConsumer", CONTRACT_VERSIONS.worldEvidenceConsumer, "WorldEvidenceBindingSchema", "parseWorldEvidenceBinding"],
    ["ContextEvidence", CONTRACT_VERSIONS.contextEvidence, "ContextEvidenceBindingSchema", "parseContextEvidenceBinding"],
    ["CorrectionResolution", CONTRACT_VERSIONS.correctionResolution, "CorrectionAuthorityRecordSchema", "parseCorrectionAuthorityRecord"],
    ["EvidenceEngineState", CONTRACT_VERSIONS.evidenceEngineState, "EvidenceEngineStateSchema", "parseEvidenceEngineState"],
    ["EvidenceBuilderInput", CONTRACT_VERSIONS.evidenceBuilderInput, "EvidenceChainBuildInputSchema", "buildEvidenceChains"],
    ["InterpretationPolicy", CONTRACT_VERSIONS.interpretationPolicy, "InterpretationPolicySchema", "parseInterpretationPolicy"],
    ["ObservationRecord", CONTRACT_VERSIONS.observationRecord, "ObservationRecordSchema", null],
    ["InterpretationRecord", CONTRACT_VERSIONS.interpretationRecord, "InterpretationRecordSchema", null],
    ["UserModelManifestV3", CONTRACT_VERSIONS.userModelManifest, "UserModelManifestV3Schema", null],
    ["UserModelSnapshotV3", CONTRACT_VERSIONS.userModelSnapshot, "UserModelSnapshotV3Schema", null],
    ["UserModelState", CONTRACT_VERSIONS.userModelState, "UserModelStateSchema", "verifyUserModelIntegrity"],
    ["UserModelCommand", CONTRACT_VERSIONS.userModelCommand, "UserModelCommandSchema", "buildUserModel"],
    ["UserModelAuthority", CONTRACT_VERSIONS.userModelAuthority, "UserModelAuthoritySchema", null],
    ["UserModelAuthorityRecord", CONTRACT_VERSIONS.userModelAuthorityRecord, "UserModelAuthorityRecordSchema", "verifyUserModelState"],
    ["UserModelAuthorityTrustAnchor", CONTRACT_VERSIONS.userModelAuthorityTrustAnchor, "UserModelAuthorityTrustAnchorSchema", "verifyUserModelState"],
    ["UserModelEvidenceCheckpoint", CONTRACT_VERSIONS.userModelEvidenceCheckpoint, "UserModelEvidenceCheckpointSchema", "updateUserModel"],
    ["UserModelLifecyclePlan", CONTRACT_VERSIONS.userModelLifecyclePlan, "UserModelLifecyclePlanSchema", "planUserModelLifecycle"],
    ["UserModelLifecycleExecution", CONTRACT_VERSIONS.userModelLifecycleExecution, "UserModelLifecycleExecutionRecordSchema", "verifyUserModelLifecycleCompletion"],
    ["UserModelLifecycleTrustAnchor", CONTRACT_VERSIONS.userModelLifecycleTrustAnchor, "UserModelLifecycleTrustAnchorSchema", "verifyUserModelLifecycleCompletion"],
    ["UserModelLifecycleCompletion", CONTRACT_VERSIONS.userModelLifecycleCompletion, "UserModelLifecycleCompletionSchema", "verifyUserModelLifecycleCompletion"],
    ["SignalSemanticsRegistry", CONTRACT_VERSIONS.signalSemanticsRegistry, "SignalSemanticsRegistrySchema", "parseSignalSemanticsRegistry"],
    ["CalibrationPolicy", CONTRACT_VERSIONS.calibrationPolicy, "CalibrationPolicySchema", "verifyCalibrationPolicy"],
    ["CalibrationPolicyTrustAnchor", CONTRACT_VERSIONS.calibrationPolicyTrustAnchor, "CalibrationPolicyTrustAnchorSchema", "verifyCalibrationPolicy"],
    ["CalibrationAuthorityProof", CONTRACT_VERSIONS.calibrationAuthorityProof, "CalibrationAuthorityProofSchema", "verifyCalibrationEvidence"],
    ["Phase2CalibrationSourceBinding", CONTRACT_VERSIONS.calibrationEvidenceAdapter, "Phase2CalibrationSourceBindingSchema", "deriveCalibrationEvidenceFromPhase2"],
    ["CalibrationEvidence", CONTRACT_VERSIONS.calibrationEvidence, "CalibrationEvidenceSchema", "verifyCalibrationEvidence"],
    ["CalibrationEvidenceTrustAnchor", CONTRACT_VERSIONS.calibrationEvidenceTrustAnchor, "CalibrationEvidenceTrustAnchorSchema", "verifyCalibrationEvidence"],
    ["CalibrationScenario", CONTRACT_VERSIONS.calibrationScenario, "CalibrationScenarioSchema", "runCalibrationScenario"],
    ["CalibrationSemanticTarget", CONTRACT_VERSIONS.calibrationSemanticTarget, "CalibrationSemanticTargetSchema", "verifyCalibrationReport"],
    ["CalibrationConflictRecord", CONTRACT_VERSIONS.calibrationConflictRecord, "CalibrationConflictRecordSchema", "verifyCalibrationReport"],
    ["CalibrationReport", CONTRACT_VERSIONS.calibrationReport, "CalibrationReportSchema", "verifyCalibrationReport"],
    ["FounderDecisionRecord", CONTRACT_VERSIONS.founderDecisionRecord, "FounderDecisionRecordSchema", "verifyProductInterpretationPolicy"],
    ["FounderDecisionRelease", CONTRACT_VERSIONS.founderDecisionRelease, "FounderDecisionReleaseSchema", "verifyProductInterpretationPolicy"],
    ["FounderDecisionTrustAnchor", CONTRACT_VERSIONS.founderDecisionTrustAnchor, "FounderDecisionTrustAnchorSchema", "verifyProductInterpretationPolicy"],
    ["ProductSignalSemanticsRegistry", CONTRACT_VERSIONS.productSignalSemanticsRegistry, "ProductSignalSemanticsRegistrySchema", "parseProductSignalSemanticsRegistry"],
    ["ProductInterpretationPolicy", CONTRACT_VERSIONS.productInterpretationPolicy, "ProductInterpretationPolicySchema", "verifyProductInterpretationPolicy"],
    ["ProductPolicyRelease", CONTRACT_VERSIONS.productPolicyRelease, "ProductPolicyReleaseSchema", "verifyProductInterpretationPolicy"],
    ["ProductPolicyTrustAnchor", CONTRACT_VERSIONS.productPolicyTrustAnchor, "ProductPolicyTrustAnchorSchema", "verifyProductInterpretationPolicy"],
    ["ProductPolicyObservation", CONTRACT_VERSIONS.productPolicyObservation, "ProductPolicyObservationSchema", "deriveProductPolicyObservationFromCalibration"],
    ["ProductPolicyEvidenceAnchor", CONTRACT_VERSIONS.productPolicyEvidenceAnchor, "ProductPolicyEvidenceAnchorSchema", "verifyProductPolicyEvaluation"],
    ["ProductPolicyEvaluation", CONTRACT_VERSIONS.productPolicyEvaluation, "ProductPolicyEvaluationSchema", "verifyProductPolicyEvaluation"],
    ["ProductPolicyReducerState", CONTRACT_VERSIONS.productPolicyReducerState, "ProductPolicyReducerStateSchema", "verifyProductPolicyState"],
    ["Phase3DCalibrationCandidate", CONTRACT_VERSIONS.phase3dCalibrationCandidate, "Phase3DCalibrationCandidateSchema", "verifyPhase3DCalibrationCandidates"],
    ["Phase3DFounderCalibrationDecisionRecord", CONTRACT_VERSIONS.phase3dFounderCalibrationDecisionRecord, "Phase3DFounderCalibrationDecisionRecordSchema", "verifyPhase3DFounderCalibrationDecisionRecord"],
    ["Phase3DCalibrationTraceability", CONTRACT_VERSIONS.phase3dCalibrationTraceability, "Phase3DCalibrationTraceabilitySchema", "verifyPhase3DCalibrationCandidates"],
    ["Phase3DCalibrationRelease", CONTRACT_VERSIONS.phase3dCalibrationReleaseFinal, "Phase3DCalibrationReleaseSchema", "verifyPhase3DCalibrationCandidates"],
    ["Phase3DCalibrationTrustAnchor", CONTRACT_VERSIONS.phase3dCalibrationTrustAnchorFinal, "Phase3DCalibrationTrustAnchorSchema", "verifyPhase3DCalibrationCandidates"],
    ["Phase3DFounderLabReport", CONTRACT_VERSIONS.phase3dReport, "Phase3DFounderLabReportSchema", "verifyPhase3DFounderLabReport"],
  ].map(([name, contractVersion, runtimeSchemaExport, semanticValidatorExport]) => ({ name, contractVersion, runtimeSchemaExport, semanticValidatorExport }))),
});
