import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { chromium } from "@playwright/test";
import { hashBody } from "../../packages/world-knowledge-core/dist/index.js";
import { LOCAL_FOUNDER_COHORT_FIXTURE, makeFounderCohortHandoff } from "./phase3c-founder-cohort-fixture.mjs";
import { startPhase3CFounderLabServer } from "./phase3c-founder-lab-ui-server.mjs";

const stateDirectory = fs.mkdtempSync(path.join(os.tmpdir(), "backyrd-founder-e2e-"));
const { server, url } = await startPhase3CFounderLabServer({ port: 0, stateDirectory });
const browser = await chromium.launch({ headless: true }); let assertions = 0;
const screenshotDirectory = process.env.PHASE3C_E2E_SCREENSHOT_DIR || null;
const realCohortPath = process.env.PHASE3C_FOUNDER_COHORT_PATH || null;
if (screenshotDirectory) fs.mkdirSync(screenshotDirectory, { recursive: true, mode: 0o700 });
const equal = (a, b, message) => { assert.equal(a, b, message); assertions += 1; }; const deep = (a, b, message) => { assert.deepEqual(a, b, message); assertions += 1; }; const ok = (value, message) => { assert.ok(value, message); assertions += 1; };
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } }); page.setDefaultTimeout(10_000);
const upload = async (artifact, name = "founder-world-cohort.json") => { const file=path.join(stateDirectory,name); fs.writeFileSync(file,`${JSON.stringify(artifact)}\n`,{mode:0o600}); const chooserPromise=page.waitForEvent("filechooser"); await page.locator("#cohort-file").click(); const chooser=await chooserPromise; await chooser.setFiles(file); };
const previewAndImport = async (artifact, expectedName, fileName = "founder-world-cohort.json") => { await upload(artifact, fileName); await page.waitForFunction((name) => document.querySelector("#preview-content")?.textContent.includes(name), expectedName); await page.click("#confirm-import"); await page.waitForFunction((name) => document.querySelector("#source-summary")?.textContent.includes(name), expectedName); };
const rehash = (artifact) => { const copy = structuredClone(artifact); delete copy.handoffHash; return { ...copy, handoffHash: hashBody(copy, []) }; };
const runPreset = async (label) => { const previous=await page.locator("#expert-data").textContent(); await page.getByRole("button", { name: label }).click(); await page.click("#resolve"); await page.waitForFunction(() => document.querySelector("#action-status")?.textContent.includes("Situation erkannt")); await page.click("#evaluate"); await page.waitForFunction((before) => document.querySelector("#expert-data")?.textContent!==before, previous); };
const groupCounts = async (activePage) => {
  const counts = Object.fromEntries(await activePage.locator(".group").evaluateAll((groups) => groups.map((group) => [group.dataset.group, group.querySelectorAll(".card").length])));
  return { confirmed: counts.ELIGIBLE_CONFIRMED, fallback: counts.UNCONFIRMED_FALLBACK, notConfigured: counts.NOT_CONFIGURED, ineligible: counts.INELIGIBLE, rejected: counts.REJECTED };
};
const visibleSpotGroups = async (activePage) => Object.fromEntries(await Promise.all(LOCAL_FOUNDER_COHORT_FIXTURE.map(async ({ spotId, name }) => {
  const card = activePage.locator(`[data-candidate-id="${spotId}"]`);
  return [name, await card.locator("xpath=ancestor::*[contains(@class,'group')]").getAttribute("data-group")];
})));
const assertPlainFounderView = async (activePage, scope, message) => {
  const visible = await activePage.locator(scope).innerText();
  ok(!/soft-mood-world-evidence-not-available|rejected-in-current-session|blocking-world-conflict|context\.|LOCATION_SCOPE|ACCESSIBILITY|AGE_OR_LEGAL|BUDGET_MAXIMUM|WORLD_|[a-f0-9]{64}/.test(visible), message);
};
const runFreshFounderCase = async ({ label, text, setup, expected }) => {
  const context = await browser.newContext({ viewport: { width: 1280, height: 900 } });
  const activePage = await context.newPage(); activePage.setDefaultTimeout(10_000);
  try {
    await activePage.goto(url); equal(await activePage.locator("#source-badge").innerText(), "Founder World Cohort", `${label}: real Founder cohort active in fresh browser`);
    equal(await activePage.locator("#evaluate").isDisabled(), true, `${label}: evaluation initially disabled`);
    if (setup) await setup(activePage);
    if (text) await activePage.fill("#task", text); else await activePage.getByRole("button", { name: label }).click();
    await activePage.click("#resolve");
    await activePage.waitForFunction(() => document.querySelector("#action-status")?.textContent.includes("Situation erkannt und auswertbar"));
    equal(await activePage.locator("#evaluate").isDisabled(), false, `${label}: evaluation enabled only after complete interpretation`);
    const visible = {
      summary: await activePage.locator("#understood").innerText(),
      primaryIntent: await activePage.inputValue("#primary"), secondaryIntent: await activePage.inputValue("#secondary"),
      occasion: await activePage.inputValue("#occasion"), moods: await activePage.inputValue("#moods"),
      targetCity: await activePage.inputValue("#target-city"), dayPhase: await activePage.inputValue("#day-phase"),
      budget: await activePage.inputValue("#budget"), companion: await activePage.inputValue("#companion"),
      minimumAge: await activePage.inputValue("#minimum-age"), adultPresent: await activePage.isChecked("#adult-present"),
      hardConstraints: await activePage.inputValue("#hard"), softPreferences: await activePage.inputValue("#soft"),
    };
    for (const [key, value] of Object.entries(expected.fields)) {
      if (typeof value === "boolean") equal(visible[key], value, `${label}: visible ${key}`);
      else ok(visible[key].includes(value), `${label}: visible ${key} includes ${value}`);
    }
    await activePage.click("#evaluate"); await activePage.waitForSelector("#results:not([hidden])");
    const groups = await groupCounts(activePage); equal(Object.values(groups).reduce((sum, count) => sum + count, 0), 5, `${label}: exactly five Founder candidates evaluated`);
    for (const [key, value] of Object.entries(expected.groups)) equal(groups[key], value, `${label}: ${key} candidate count`);
    const resultData = JSON.parse(await activePage.locator("#expert-data").textContent()); const spots = {};
    for (const { spotId, name } of LOCAL_FOUNDER_COHORT_FIXTURE) {
      const card = activePage.locator(`[data-candidate-id="${spotId}"]`); equal(await card.count(), 1, `${label}: ${name} visible exactly once`);
      const group = await card.locator("xpath=ancestor::*[contains(@class,'group')]").getAttribute("data-group"); const text = await card.innerText();
      equal(group, expected.spots[name].group, `${label}: ${name} visible group`); ok(text.includes(expected.spots[name].core), `${label}: ${name} core-intent explanation (${text})`); ok(text.includes(expected.spots[name].reason), `${label}: ${name} visible reason (${text})`);
      for (const heading of ["Hauptgrund für den Besuch", "Spezifische Kernklassifikation", "Zusatzangebot", "Besuchssituation", "Atmosphäre", "Typische Tageszeit", "Tatsächlich geöffnet"]) ok(text.includes(heading), `${label}: ${name} shows ${heading}`);
      const assessment = resultData.candidates.find((item) => item.candidateId === spotId);
      for (const field of ["visitSituation","atmosphere","typicalDaypart"]) if (expected.spots[name][field]) equal(assessment[field].state, expected.spots[name][field], `${label}: ${name} ${field}`);
      spots[name] = { group, core: assessment.coreIntentCoverage.state, primaryPurpose: assessment.worldClassification.primaryVisitPurpose, primaryCategory: assessment.worldClassification.primaryCategory, placeTypes: assessment.worldClassification.placeTypes, onsiteKinds: assessment.onsiteOfferings.availableKinds, onsiteRelationships: assessment.onsiteOfferings.relationships, visitSituation: assessment.visitSituation.state, atmosphere: assessment.atmosphere.state, typicalDaypart: assessment.typicalDaypart.state, availability: assessment.actualAvailability.status, reason: expected.spots[name].reason };
    }
    await assertPlainFounderView(activePage, "#results", `${label}: normal result contains no internal code or hash`);
    return { label, visible, groups, spots };
  } finally { await context.close(); }
};
page.on("pageerror", (error) => process.stderr.write(`browser_page_error:${error.message}\n`));
try {
  await page.goto(url); equal(await page.title(), "Backyrd Founder Decision Lab", "German Founder UI title"); ok((await page.locator("body").innerText()).includes("EVALUATION ONLY"), "evaluation boundary visible"); equal(await page.locator("#source-badge").innerText(), "Synthetische Testwelt", "fallback clearly labelled");
  equal(await page.locator("#evaluate").isDisabled(), true, "evaluation disabled until interpretation is verified");
  const storedArtifact = realCohortPath ? JSON.parse(fs.readFileSync(realCohortPath, "utf8")) : null; const valid = storedArtifact?.artifact ?? storedArtifact ?? makeFounderCohortHandoff(); await upload(valid); await page.waitForSelector("#cohort-preview:not([hidden])"); const previewText=await page.locator("#preview-content").innerText(); for(const {name} of LOCAL_FOUNDER_COHORT_FIXTURE) ok(previewText.includes(name), `preview lists ${name}`); await page.click("#confirm-import"); await page.waitForFunction(() => document.querySelector("#source-badge")?.textContent === "Founder World Cohort"); ok((await page.locator("#source-summary").innerText()).includes("5 Spots"), "five-spot Founder cohort activated"); if(screenshotDirectory) await page.screenshot({path:path.join(screenshotDirectory,"01-founder-cohort-import.png"),fullPage:true});
  await previewAndImport(valid, "Volta Bräu", "founder-world-cohort-reimport.json"); equal(await page.locator("#source-badge").innerText(), "Founder World Cohort", "idempotent reimport");
  const second = makeFounderCohortHandoff(["Anderer Founder Spot", "Zweiter Founder Spot"]); await previewAndImport(second, "Anderer Founder Spot", "founder-world-cohort-second.json"); ok((await page.locator("#source-summary").innerText()).includes("Anderer Founder Spot"), "intentional cohort switch"); ok(!(await page.locator("#source-summary").innerText()).includes("Volta Bräu"), "cohorts never mix");
  await page.reload(); await page.waitForFunction(() => document.querySelector("#source-badge")?.textContent === "Founder World Cohort"); ok((await page.locator("#source-summary").innerText()).includes("Anderer Founder Spot"), "cohort persists across reload");
  const one = makeFounderCohortHandoff(["Volta Bräu"]); await previewAndImport(one, "Volta Bräu", "founder-world-cohort-one.json"); ok((await page.locator("#source-summary").innerText()).includes("nur einen Spot"), "single spot warning visible");
  for (const [name, mutate, expected] of [
    ["invalid-scope.json", (a) => { a.scope="PRODUCTION"; }, "scope"],
    ["invalid-manifest.json", (a) => { a.spots[0].manifestHash="0".repeat(64); }, "verändert"],
    ["invalid-snapshot.json", (a) => { a.spots[0].snapshot.facts[0].value="Manipuliert"; }, "verändert"],
    ["invalid-registry.json", (a) => { a.manifest.registryVersion="backyrd.world-knowledge.registry@999"; a.manifestContentHash=hashBody(a.manifest,[]); }, "registry"],
    ["invalid-nested-schema.json", (a) => { const fact=a.spots.flatMap((spot)=>spot.snapshot.facts).find((item)=>item.key==="rule.age_access_conditions"); fact.value.rules[0].notes="nicht kanonisch"; }, "nicht übernommen"],
  ]) { const forged=structuredClone(valid); mutate(forged); await page.locator("#notice").evaluate((element)=>{element.textContent="";}); await upload(rehash(forged),name); await page.waitForFunction(() => document.querySelector("#notice")?.textContent.includes("nicht übernommen")); ok((await page.locator("#notice").innerText()).toLowerCase().includes(expected), `${name} rejected`); }
  await page.click("#synthetic"); await page.waitForFunction(() => document.querySelector("#source-badge")?.textContent === "Synthetische Testwelt"); ok(!(await page.locator("#source-summary").innerText()).includes("Volta Bräu"), "explicit synthetic switch does not mix worlds");
  await previewAndImport(valid, "Volta Bräu", "founder-world-cohort-final.json");
  const incompleteContext = await browser.newContext({ viewport: { width: 1280, height: 900 } }); const incompletePage = await incompleteContext.newPage(); incompletePage.setDefaultTimeout(10_000);
  await incompletePage.goto(url); await incompletePage.fill("#task", "Ich suche einen Ort für mich und meine zwölfjährige Tochter."); await incompletePage.click("#resolve"); await incompletePage.waitForFunction(() => document.querySelector("#action-status")?.textContent.includes("noch nicht auswertbar"));
  const missing = await incompletePage.locator("#unclear").innerText(); ok(missing.includes("Hauptabsicht fehlt") && missing.includes("Zielort fehlt"), "incomplete request names every missing required field"); ok(missing.includes("Freitext") && missing.includes("Feld"), "incomplete request tells Founder where to correct it"); ok(missing.includes("pauschale Kandidatenauswertung") && missing.includes("nicht sinnvoll"), "incomplete request explains why evaluation is blocked"); equal(await incompletePage.locator("#evaluate").isDisabled(), true, "incomplete request cannot evaluate all five spots"); equal(await incompletePage.locator("#results").isHidden(), true, "incomplete request produces no candidate result"); await incompletePage.fill("#primary", "Essen"); await incompletePage.fill("#target-city", "Basel"); equal(await incompletePage.locator("#evaluate").isDisabled(), false, "Founder can complete the two named fields before evaluation"); await incompleteContext.close();
  const blockedResponse = await page.request.post(`${url}/api/evaluate`, { data: { text:"Ich suche einen Ort für mich und meine zwölfjährige Tochter.", tracking:false, deviceCity:"Basel", userMode:"NEUTRAL_MISSING", alternativeRequested:false, rejectedCandidateIds:[] } });
  equal(blockedResponse.status(), 400, "local evaluation endpoint rejects the incomplete request"); ok((await blockedResponse.json()).message.includes("phase3c_founder_lab_not_evaluable"), "server rejection carries the bounded evaluability reason");
  const founderCases = [];
  const allLocationFail = Object.fromEntries(LOCAL_FOUNDER_COHORT_FIXTURE.map(({name})=>[name,{group:"INELIGIBLE",core:name==="Volta Bräu"?"Kernabsicht bestätigt":["ELYS Boulderloft","Tierpark Lange Erlen"].includes(name)?"Kernabsicht nachweislich nicht erfüllt":"Kernabsicht unbekannt",reason:"Zielgebiet verletzt eine ausdrückliche Bedingung"}]));
  founderCases.push(await runFreshFounderCase({ label: "A · Composite Date", expected: { fields: { summary:"zwingende Zielbindung", primaryIntent:"Essen", secondaryIntent:"In Ruhe reden", occasion:"Erstes Date", moods:"ruhig", targetCity:"Zurich", budget:"40", hardConstraints:"Maximales Budget", softPreferences:"gewünschte Stimmung" }, groups: { confirmed:0, fallback:0, notConfigured:0, ineligible:5, rejected:0 }, spots:allLocationFail } }));
  founderCases.push(await runFreshFounderCase({ label: "B · Familie & Alter", expected: { fields: { summary:"zwingende Zielbindung", primaryIntent:"Essen", occasion:"Familie", targetCity:"Basel", companion:"Familie", minimumAge:"12", adultPresent:true, hardConstraints:"Altersregel" }, groups: { confirmed:0, fallback:3, notConfigured:0, ineligible:2, rejected:0 }, spots:{
    "Volta Bräu":{group:"UNCONFIRMED_FALLBACK",core:"Kernabsicht bestätigt",reason:"Altersregel ist unbekannt",visitSituation:"UNKNOWN"}, "ELYS Boulderloft":{group:"INELIGIBLE",core:"Kernabsicht nachweislich nicht erfüllt",reason:"Kernabsicht nicht erfüllt",visitSituation:"CONFIRMED"}, "Tierpark Lange Erlen":{group:"INELIGIBLE",core:"Kernabsicht nachweislich nicht erfüllt",reason:"Kernabsicht nicht erfüllt",visitSituation:"CONFIRMED"}, "Consum Weinbar":{group:"UNCONFIRMED_FALLBACK",core:"Kernabsicht unbekannt",reason:"Altersregel ist unbekannt",visitSituation:"UNKNOWN"}, "Café Frühling":{group:"UNCONFIRMED_FALLBACK",core:"Kernabsicht unbekannt",reason:"Altersregel ist unbekannt",visitSituation:"UNKNOWN"},
  } } }));
  founderCases.push(await runFreshFounderCase({ label: "C · Accessibility", expected: { fields: { summary:"zwingende Zielbindung", primaryIntent:"Kaffee", secondaryIntent:"In Ruhe reden", moods:"gemütlich", targetCity:"Basel", hardConstraints:"Rollstuhlgerechter Zugang" }, groups: { confirmed:0, fallback:3, notConfigured:0, ineligible:2, rejected:0 }, spots:{
    "Volta Bräu":{group:"UNCONFIRMED_FALLBACK",core:"Kernabsicht unbekannt",reason:"rollstuhlgerechte Zugang ist durch",atmosphere:"UNKNOWN"}, "ELYS Boulderloft":{group:"INELIGIBLE",core:"Kernabsicht nachweislich nicht erfüllt",reason:"Kernabsicht nicht erfüllt",atmosphere:"UNKNOWN"}, "Tierpark Lange Erlen":{group:"INELIGIBLE",core:"Kernabsicht nachweislich nicht erfüllt",reason:"Kernabsicht nicht erfüllt",atmosphere:"UNKNOWN"}, "Consum Weinbar":{group:"UNCONFIRMED_FALLBACK",core:"Kernabsicht unbekannt",reason:"rollstuhlgerechte Zugang ist unbekannt",atmosphere:"UNKNOWN"}, "Café Frühling":{group:"UNCONFIRMED_FALLBACK",core:"Kernabsicht bestätigt",reason:"rollstuhlgerechte Zugang ist unbekannt",atmosphere:"UNKNOWN"},
  } } }));
  founderCases.push(await runFreshFounderCase({ label: "D · Location", setup: async (activePage) => { await activePage.check("#tracking"); await activePage.selectOption("#device-city", "Basel"); }, expected: { fields: { summary:"zwingende Zielbindung", primaryIntent:"Essen", targetCity:"Zurich" }, groups: { confirmed:0, fallback:0, notConfigured:0, ineligible:5, rejected:0 }, spots:allLocationFail } }));
  founderCases.push(await runFreshFounderCase({ label: "Familienausflug am Nachmittag", text: "Ich suche heute Nachmittag in Basel einen Familienausflug für mich und meine zwölfjährige Tochter.", expected: { fields: { primaryIntent:"Familienausflug", targetCity:"Basel", dayPhase:"Nachmittag", companion:"Familie", minimumAge:"12" }, groups: { confirmed:1, fallback:0, notConfigured:0, ineligible:4, rejected:0 }, spots:{
    "Volta Bräu":{group:"INELIGIBLE",core:"Kernabsicht nachweislich nicht erfüllt",reason:"Kernabsicht nicht erfüllt",visitSituation:"UNKNOWN",typicalDaypart:"INCOMPATIBLE"}, "ELYS Boulderloft":{group:"INELIGIBLE",core:"Kernabsicht nachweislich nicht erfüllt",reason:"Kernabsicht nicht erfüllt",visitSituation:"CONFIRMED",typicalDaypart:"UNKNOWN"}, "Tierpark Lange Erlen":{group:"ELIGIBLE_CONFIRMED",core:"Kernabsicht bestätigt",reason:"Altersregel ist durch",visitSituation:"CONFIRMED",typicalDaypart:"CONFIRMED"}, "Consum Weinbar":{group:"INELIGIBLE",core:"Kernabsicht nachweislich nicht erfüllt",reason:"Kernabsicht nicht erfüllt",visitSituation:"UNKNOWN",typicalDaypart:"UNKNOWN"}, "Café Frühling":{group:"INELIGIBLE",core:"Kernabsicht nachweislich nicht erfüllt",reason:"Kernabsicht nicht erfüllt",visitSituation:"UNKNOWN",typicalDaypart:"INCOMPATIBLE"},
  } } }));
  founderCases.push(await runFreshFounderCase({ label: "Bouldern mit Familie", text: "Ich möchte heute Nachmittag in Basel mit meiner Familie bouldern.", expected: { fields: { primaryIntent:"Bouldern", targetCity:"Basel", dayPhase:"Nachmittag", companion:"Familie" }, groups: { confirmed:1, fallback:0, notConfigured:0, ineligible:4, rejected:0 }, spots:{
    "Volta Bräu":{group:"INELIGIBLE",core:"Kernabsicht nachweislich nicht erfüllt",reason:"Kernabsicht nicht erfüllt",visitSituation:"UNKNOWN"}, "ELYS Boulderloft":{group:"ELIGIBLE_CONFIRMED",core:"Kernabsicht bestätigt",reason:"Kernabsicht ist durch",visitSituation:"UNKNOWN"}, "Tierpark Lange Erlen":{group:"INELIGIBLE",core:"Kernabsicht nachweislich nicht erfüllt",reason:"Kernabsicht nicht erfüllt",visitSituation:"UNKNOWN"}, "Consum Weinbar":{group:"INELIGIBLE",core:"Kernabsicht nachweislich nicht erfüllt",reason:"Kernabsicht nicht erfüllt",visitSituation:"UNKNOWN"}, "Café Frühling":{group:"INELIGIBLE",core:"Kernabsicht nachweislich nicht erfüllt",reason:"Kernabsicht nicht erfüllt",visitSituation:"UNKNOWN"},
  } } }));
  const atmosphereSpot={spotId:"00000000-0000-4000-8000-000000000901",name:"Atmosphäre-Prüfspot"};
  const atmosphereFacts={ [atmosphereSpot.spotId]:[{key:"classification.primary_category",value:"COFFEE_DAYTIME",resolution:"KNOWN_VALUE"},{key:"classification.place_types",value:["CAFE"],resolution:"KNOWN_VALUE"}] };
  const atmosphereContext=(value)=>({[atmosphereSpot.spotId]:{"purpose.primary_visit":"EAT_DRINK","context.atmosphere":value}});
  await previewAndImport(makeFounderCohortHandoff([atmosphereSpot],atmosphereContext([{atmosphere:"LIVELY",conditions:{accompaniment:null,ageContext:null,area:null,dayparts:[],days:[],eventMode:null,groupSize:null,occasion:null}}]),atmosphereFacts),atmosphereSpot.name,"atmosphere-mismatch.json");
  await page.fill("#task","Ich möchte in Basel ruhig Kaffee trinken.");await page.click("#resolve");await page.waitForFunction(()=>document.querySelector("#action-status")?.textContent.includes("auswertbar"));await page.click("#evaluate");await page.waitForSelector("#results:not([hidden])");let atmosphereCard=page.locator(`[data-candidate-id="${atmosphereSpot.spotId}"]`);ok((await atmosphereCard.innerText()).includes("Die bestätigte Atmosphäre entspricht dem weichen Wunsch nicht"),"confirmed atmosphere mismatch is explained in Founder language");await assertPlainFounderView(page,"#results","atmosphere mismatch leaks no internal code");
  await previewAndImport(makeFounderCohortHandoff([atmosphereSpot],atmosphereContext({disputed:true}),atmosphereFacts),atmosphereSpot.name,"atmosphere-disputed.json");
  await page.fill("#task","Ich möchte in Basel ruhig Kaffee trinken.");await page.click("#resolve");await page.waitForFunction(()=>document.querySelector("#action-status")?.textContent.includes("auswertbar"));await page.click("#evaluate");await page.waitForSelector("#results:not([hidden])");atmosphereCard=page.locator(`[data-candidate-id="${atmosphereSpot.spotId}"]`);ok((await atmosphereCard.innerText()).includes("widersprüchliche Angaben"),"disputed atmosphere remains visibly disputed without a winner");await assertPlainFounderView(page,"#results","disputed atmosphere leaks no internal code");
  await previewAndImport(valid,"Volta Bräu","founder-world-cohort-restored.json");
  await page.fill("#task", "Ich möchte heute Abend in Basel ruhig etwas trinken, bei einem Date."); await page.click("#resolve"); await page.waitForFunction(() => document.querySelector("#action-status")?.textContent.includes("Situation erkannt und auswertbar")); await page.click("#evaluate"); await page.waitForFunction(() => document.querySelector("#action-status")?.textContent.includes("Auswertung abgeschlossen"));
  ok((await page.locator("#understood").innerText()).includes("Etwas trinken")&&(await page.locator("#understood").innerText()).includes("Basel"),"controlled flip base keeps drinks and Basel");
  const expectedFlipGroups = { "Volta Bräu":"ELIGIBLE_CONFIRMED", "ELYS Boulderloft":"INELIGIBLE", "Tierpark Lange Erlen":"INELIGIBLE", "Consum Weinbar":"ELIGIBLE_CONFIRMED", "Café Frühling":"UNCONFIRMED_FALLBACK" };
  const expectedFlipCounts = { confirmed:2, fallback:1, notConfigured:0, ineligible:2, rejected:0 };
  const baseGroups=await groupCounts(page); deep(baseGroups,expectedFlipCounts,"controlled flip base has canonical group counts"); const baseSpots=await visibleSpotGroups(page); deep(baseSpots,expectedFlipGroups,"controlled flip base has canonical per-spot groups"); await assertPlainFounderView(page,"#results","controlled flip base contains no internal code or hash");
  const baseHard=await page.inputValue("#hard"); await page.click("#context-flip"); equal(await page.locator("#evaluate").isDisabled(),true,"context change invalidates prior interpretation"); await page.click("#resolve"); await page.waitForFunction(() => document.querySelector("#action-status")?.textContent.includes("Situation erkannt und auswertbar")); equal(await page.inputValue("#primary"),"Etwas trinken","context flip preserves core intent"); equal(await page.inputValue("#target-city"),"Basel","context flip preserves target city"); equal(await page.inputValue("#hard"),baseHard,"context flip preserves hard constraints"); ok((await page.inputValue("#moods")).includes("lebhaft"),"context flip changes mood"); equal(await page.inputValue("#companion"),"Freunde","context flip changes companion"); await page.click("#evaluate"); await page.waitForFunction(() => document.querySelector("#comparison") && !document.querySelector("#comparison").hidden); const flipGroups=await groupCounts(page); deep(flipGroups,expectedFlipCounts,"controlled flip result has canonical group counts"); const flipSpots=await visibleSpotGroups(page); deep(flipSpots,expectedFlipGroups,"controlled flip result has canonical per-spot groups"); const comparison=await page.locator("#comparison").innerText(); ok(comparison.includes("Kernabsicht: unverändert")&&comparison.includes("Zielort und zwingende Bedingungen: unverändert"),"comparison proves invariant core and hard bindings"); ok(comparison.includes("Geänderte Situationsangaben: Nebenabsicht, Stimmung, Begleitung"),"comparison names only the controlled dimensions"); for(const {name}of LOCAL_FOUNDER_COHORT_FIXTURE){ok(comparison.includes(name),`comparison lists ${name}`);const row=page.locator("#comparison tbody tr").filter({hasText:name});ok((await row.innerText()).includes("unverändert"),`comparison keeps ${name} group stable`);} ok(comparison.includes("Vorher")&&comparison.includes("Jetzt")&&comparison.includes("Grund hinzu")&&comparison.includes("Grund entfallen"),"comparison exposes per-spot group and reason deltas"); await assertPlainFounderView(page,"#results","controlled flip result contains no internal code or hash"); await assertPlainFounderView(page,"#comparison","comparison contains no internal code or hash"); if(screenshotDirectory) await page.screenshot({path:path.join(screenshotDirectory,"04-context-flip-comparison.png"),fullPage:true});
  await page.click("#alternative"); await page.waitForFunction(() => document.querySelector("#action-status")?.textContent.includes("Weitere Alternative angefordert")); const alternativeStatus=await page.locator("#action-status").innerText(); ok(alternativeStatus.includes("kein Spot wird dadurch negativ bewertet")&&alternativeStatus.includes("keine langfristige Nutzerpräferenz"),"alternative stays neutral and explains unchanged fixture selection"); await assertPlainFounderView(page,"#action-status","alternative status contains no internal code or hash");
  const rejectSource=page.locator('[data-group="ELIGIBLE_CONFIRMED"] .card, [data-group="UNCONFIRMED_FALLBACK"] .card').first(); const rejectedName=await rejectSource.locator("h4").innerText(); await rejectSource.locator(".reject").click(); await page.waitForFunction(() => document.querySelector("#action-status")?.textContent.includes("Für diese Anfrage abgewählt")); const rejectedCard=page.locator('[data-group="REJECTED"] .card').filter({hasText:rejectedName}); equal(await rejectedCard.count(),1,"situational reject has its own visible group"); ok((await rejectedCard.innerText()).includes("keine objektive Unvereinbarkeit"),"reject never claims a hard World failure");
  await page.click("#replay"); await page.waitForFunction(() => document.querySelector("#action-status")?.textContent.includes("byte-identisch")); if(screenshotDirectory) await page.screenshot({path:path.join(screenshotDirectory,"05-replay.png"),fullPage:true});
  await assertPlainFounderView(page,"#results","reject result contains no internal code or hash"); await assertPlainFounderView(page,"#action-status","replay status contains no internal code or hash");
  await page.click("#expert"); const expert=await page.locator("#expert-data").innerText(); ok(expert.includes('"productionAuthorized": false')&&expert.includes('"writesUserIntelligence": false'), "expert boundaries visible"); ok(expert.includes('"soft-mood-world-evidence-not-available"'),"technical limitation remains available only in expert view"); ok(!expert.includes("Ich suche"), "raw request absent from result");
  await page.setViewportSize({ width: 390, height: 844 }); await page.reload(); await page.waitForSelector("#cohort-file"); equal(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth + 1), false, "narrow layout has no horizontal overflow");
  page.once("dialog", dialog=>dialog.accept()); await page.click("#reset"); await page.waitForFunction(() => document.querySelector("#source-badge")?.textContent === "Synthetische Testwelt"); equal(fs.existsSync(path.join(stateDirectory,"active-cohort.json")),false,"reset only clears local file");
  const requests=[]; page.on("request",request=>requests.push(request.url())); await page.reload(); await page.waitForSelector("#source-badge"); equal(requests.some(requestUrl=>!requestUrl.startsWith(url)),false,"no external network request");
  process.stdout.write(`${JSON.stringify({ suite:"phase3c-founder-cohort-browser-e2e", scenarios:29, assertions, outcome:"PASS", localOnly:true, cohortEvidenceSource:realCohortPath?"EXPORTED_LOCAL_FOUNDER_HANDOFF":"CANONICAL_WORLD_AUTHORING_FIXTURE", canonicalHandoffConsumer:true, founderSpotCount:5, founderCases, contextFlip:{before:{groups:baseGroups,spots:baseSpots},after:{groups:flipGroups,spots:flipSpots},changedDimensions:["Nebenabsicht","Stimmung","Begleitung"],coreIntentUnchanged:true,targetLocationUnchanged:true,hardConstraintsUnchanged:true}, screenshots:screenshotDirectory })}\n`);
} finally { await browser.close(); await new Promise((resolve)=>server.close(resolve)); }
