"use client";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "@/lib/supabaseClient";
import {Category,empty,Form,labels,NodeType,Row,slugify,toForm} from "@/lib/taxonomy";
import "./taxonomy.css";

export default function TaxonomyPage(){
 const[rows,setRows]=useState<Row[]>([]),[categories,setCategories]=useState<Category[]>([]);
 const[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[detailLoading,setDetailLoading]=useState(false);
 const[error,setError]=useState(""),[notice,setNotice]=useState(""),[search,setSearch]=useState("");
 const[type,setType]=useState<"all"|NodeType>("all"),[status,setStatus]=useState("all"),[owner,setOwner]=useState("all");
 const[open,setOpen]=useState(false),[form,setForm]=useState<Form>({...empty});

 useEffect(()=>{void load()},[]);
 async function load(){setLoading(true);setError("");const[a,b]=await Promise.all([supabase.rpc("admin_get_taxonomy_overview_v1"),supabase.from("categories").select("id,name,icon,color").order("name")]);if(a.error)setError(a.error.message);else setRows((a.data??[]) as Row[]);if(b.error)setError(x=>x||b.error!.message);else setCategories((b.data??[]) as Category[]);setLoading(false)}
 const filtered=useMemo(()=>rows.filter(r=>{const q=search.trim().toLowerCase(),hay=[r.label_de,r.label_en,r.slug,r.node_type,r.parent_label??"",...(r.category_names??[])].join(" ").toLowerCase();return(!q||hay.includes(q))&&(type==="all"||r.node_type===type)&&(status==="all"||(status==="active"?r.is_active:!r.is_active))&&(owner==="all"||(owner==="owner"?r.is_owner_selectable:!r.is_owner_selectable))}),[rows,search,type,status,owner]);
 const stats=useMemo(()=>({total:rows.length,active:rows.filter(r=>r.is_active).length,owner:rows.filter(r=>r.is_owner_selectable).length,assignments:rows.reduce((s,r)=>s+Number(r.spots_count||0),0)}),[rows]);
 const parents=rows.filter(r=>r.id!==form.id&&r.is_active&&(form.node_type==="subcategory"||r.node_type==="subcategory"));
 const patch=(k:keyof Form,v:any)=>setForm(f=>({...f,[k]:v}));
 function create(){setForm({...empty,category_ids:[],synonyms:[]});setError("");setNotice("");setOpen(true)}
 async function edit(id:string){setDetailLoading(true);setOpen(true);setError("");const{data,error}=await supabase.rpc("admin_get_taxonomy_node_v1",{p_id:id});if(error){setError(error.message);setOpen(false)}else setForm(toForm(data));setDetailLoading(false)}
 function toggleCategory(id:string){setForm(f=>({...f,category_ids:f.category_ids.includes(id)?f.category_ids.filter(x=>x!==id):[...f.category_ids,id]}))}
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");const slug=slugify(form.slug||form.label_de),weight=Number(form.ml_weight);if(!form.label_de.trim()||!slug||!Number.isFinite(weight)||weight<.1||weight>5){setError("Bitte Bezeichnung, Slug und ML-Gewicht (0,1–5,0) prüfen.");setSaving(false);return}
 const invalidSynonymWeight=form.synonyms.some(s=>s.synonym.trim()&&(!Number.isFinite(Number(s.weight))||Number(s.weight)<.1||Number(s.weight)>1.5));
 if(invalidSynonymWeight){setError("Bitte Synonym-Gewichte im Bereich 0,1–1,5 prüfen.");setSaving(false);return}
 const{data:id,error:uerr}=await supabase.rpc("admin_upsert_taxonomy_node_v2",{p_id:form.id,p_slug:slug,p_node_type:form.node_type,p_parent_id:form.parent_id||null,p_icon:form.icon||null,p_color:form.color||null,p_sort_order:Number(form.sort_order)||0,p_is_active:form.is_active,p_is_owner_selectable:form.is_owner_selectable,p_ml_weight:weight,p_label_de:form.label_de.trim(),p_short_label_de:form.short_label_de||null,p_description_de:form.description_de||null,p_label_en:form.label_en||null,p_short_label_en:form.short_label_en||null,p_description_en:form.description_en||null,p_category_ids:form.category_ids});
 if(uerr||!id){setError(uerr?.message||"Speichern fehlgeschlagen.");setSaving(false);return}
 const syn=form.synonyms.filter(s=>s.synonym.trim()).map(s=>({locale:s.locale,synonym:s.synonym.trim(),weight:Number(s.weight)||1}));
 const{error:serr}=await supabase.rpc("admin_set_taxonomy_synonyms_v1",{p_taxonomy_node_id:id,p_synonyms:syn});
 if(serr){setError(`Gespeichert, Synonyme fehlgeschlagen: ${serr.message}`);setSaving(false);await load();return}
 setNotice(form.id?"Taxonomie aktualisiert.":"Taxonomie erstellt.");setOpen(false);setSaving(false);await load()}
 async function remove(){if(!form.id||form.is_system||!confirm(`„${form.label_de||form.slug}“ wirklich löschen?`))return;setSaving(true);const{error}=await supabase.rpc("admin_delete_taxonomy_node_v1",{p_id:form.id});if(error)setError(error.message);else{setNotice("Taxonomie gelöscht.");setOpen(false);await load()}setSaving(false)}
 return <div className="bi-page taxonomy-page">
  <header className="bi-header"><div><div className="bi-eyebrow">Founder Intelligence</div><h1>Taxonomy</h1><p>Unterkategorien, Features, Angebote und Services zentral steuern.</p></div><div className="tax-actions"><button className="bi-actionButton" onClick={()=>void load()}>{loading?"Lädt…":"Neu laden"}</button><button className="bi-primaryButton" onClick={create}>+ Taxonomie</button></div></header>
  {error&&<div className="bi-error">{error}</div>}{notice&&<div className="tax-notice">{notice}</div>}
  <section className="bi-kpiGrid tax-kpis"><article className="bi-kpi"><span>Taxonomien</span><strong>{stats.total}</strong><div><small>Gesamter Katalog</small></div></article><article className="bi-kpi"><span>Aktiv</span><strong>{stats.active}</strong><div><small>Für Suche und ML</small></div></article><article className="bi-kpi"><span>Owner-wählbar</span><strong>{stats.owner}</strong><div><small>Im Spot Editor</small></div></article><article className="bi-kpi"><span>Zuweisungen</span><strong>{stats.assignments}</strong><div><small>Über alle Spots</small></div></article></section>
  <section className="bi-card tax-card"><div className="tax-toolbar"><input className="bi-input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, Slug oder Kategorie suchen…"/><select className="bi-select" value={type} onChange={e=>setType(e.target.value as any)}><option value="all">Alle Typen</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select className="bi-select" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Alle Status</option><option value="active">Aktiv</option><option value="inactive">Inaktiv</option></select><select className="bi-select" value={owner} onChange={e=>setOwner(e.target.value)}><option value="all">Alle Sichtbarkeiten</option><option value="owner">Owner-wählbar</option><option value="internal">Nur intern</option></select><span>{filtered.length} Ergebnisse</span></div>
   {loading?<div className="bi-state">Lädt…</div>:<div className="bi-tableWrap"><table className="bi-table"><thead><tr><th>Taxonomie</th><th>Typ</th><th>Kategorien</th><th>ML</th><th>Spots</th><th>Synonyme</th><th>Status</th><th/></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><button className="tax-name" onClick={()=>void edit(r.id)}><i style={r.color?{background:`${r.color}22`,color:r.color}:undefined}>{r.icon||"◇"}</i><span><strong>{r.label_de}</strong><small>{r.slug}{r.parent_label?` · ${r.parent_label}`:""}</small></span></button></td><td><b className={`tax-type ${r.node_type}`}>{labels[r.node_type]}</b></td><td>{r.category_names?.length?r.category_names.join(", "):"Alle"}</td><td>{Number(r.ml_weight).toFixed(2)}</td><td>{r.spots_count}</td><td>{r.synonyms_count}</td><td><span className={`bi-badge ${r.is_active?"success":"muted"}`}>{r.is_active?"Aktiv":"Inaktiv"}</span>{r.is_owner_selectable&&<small>Owner</small>}</td><td><button className="bi-action tax-edit" onClick={()=>void edit(r.id)}>Bearbeiten</button></td></tr>)}</tbody></table></div>}
  </section>
  {open&&<div className="tax-backdrop" onMouseDown={()=>!saving&&setOpen(false)}><section className="tax-modal" onMouseDown={e=>e.stopPropagation()}>{detailLoading?<div className="bi-state">Lädt…</div>:<form onSubmit={save}><header><div><div className="bi-eyebrow">{form.id?"Bearbeiten":"Neue Taxonomie"}</div><h2>{form.label_de||"Unbenannt"}</h2></div><button type="button" onClick={()=>setOpen(false)}>×</button></header><main>
   <div className="tax-section"><h3>Grunddaten</h3><div className="tax-grid">
    <label>Deutsche Bezeichnung<input className="bi-input" required value={form.label_de} onChange={e=>setForm(f=>({...f,label_de:e.target.value,slug:f.id||f.slug?f.slug:slugify(e.target.value)}))}/></label>
    <label>Slug<input className="bi-input" required value={form.slug} onChange={e=>patch("slug",slugify(e.target.value))}/></label>
    <label>Typ<select className="bi-select" value={form.node_type} onChange={e=>patch("node_type",e.target.value)}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
    <label>Übergeordnet<select className="bi-select" value={form.parent_id} onChange={e=>patch("parent_id",e.target.value)}><option value="">Keine</option>{parents.map(r=><option key={r.id} value={r.id}>{r.label_de}</option>)}</select></label>
    <label>ML-Gewicht<input className="bi-input" type="number" min=".1" max="5" step=".05" value={form.ml_weight} onChange={e=>patch("ml_weight",e.target.value)}/></label>
    <label>Sortierung<input className="bi-input" type="number" value={form.sort_order} onChange={e=>patch("sort_order",e.target.value)}/></label>
    <label>Icon<input className="bi-input" value={form.icon} onChange={e=>patch("icon",e.target.value)}/></label>
    <label>Farbe<input className="bi-input" value={form.color} onChange={e=>patch("color",e.target.value)} placeholder="#ff3b7f"/></label>
   </div><div className="tax-switches"><label><input type="checkbox" checked={form.is_active} onChange={e=>patch("is_active",e.target.checked)}/> Aktiv</label><label><input type="checkbox" checked={form.is_owner_selectable} onChange={e=>patch("is_owner_selectable",e.target.checked)}/> Owner-wählbar</label></div></div>
   <div className="tax-section"><h3>Übersetzungen</h3><div className="tax-grid"><label>Kurzbezeichnung DE<input className="bi-input" value={form.short_label_de} onChange={e=>patch("short_label_de",e.target.value)}/></label><label>Label EN<input className="bi-input" value={form.label_en} onChange={e=>patch("label_en",e.target.value)}/></label><label>Beschreibung DE<textarea value={form.description_de} onChange={e=>patch("description_de",e.target.value)}/></label><label>Description EN<textarea value={form.description_en} onChange={e=>patch("description_en",e.target.value)}/></label></div></div>
   <div className="tax-section"><h3>Hauptkategorien</h3><div className="tax-cats">{categories.map(c=><button type="button" key={c.id} className={form.category_ids.includes(c.id)?"on":""} onClick={()=>toggleCategory(c.id)}>{c.icon||"◇"} {c.name}</button>)}</div></div>
   <div className="tax-section"><div className="tax-section-head"><h3>Synonyme</h3><button type="button" className="bi-actionButton" onClick={()=>patch("synonyms",[...form.synonyms,{locale:"de",synonym:"",weight:1}])}>+ Synonym</button></div>{form.synonyms.map((s,i)=><div className="tax-syn" key={i}><select className="bi-select" value={s.locale} onChange={e=>patch("synonyms",form.synonyms.map((x,j)=>j===i?{...x,locale:e.target.value as any}:x))}><option value="de">DE</option><option value="en">EN</option></select><input className="bi-input" value={s.synonym} onChange={e=>patch("synonyms",form.synonyms.map((x,j)=>j===i?{...x,synonym:e.target.value}:x))}/><input className="bi-input" type="number" min=".1" max="1.5" step=".05" value={s.weight} onChange={e=>patch("synonyms",form.synonyms.map((x,j)=>j===i?{...x,weight:Number(e.target.value)}:x))}/><button type="button" onClick={()=>patch("synonyms",form.synonyms.filter((_,j)=>j!==i))}>×</button></div>)}</div>
  </main><footer><div>{form.id&&!form.is_system&&<button type="button" className="tax-delete" onClick={remove}>Löschen</button>}</div><div><button type="button" className="bi-actionButton" onClick={()=>setOpen(false)}>Abbrechen</button><button className="bi-primaryButton" disabled={saving}>{saving?"Speichert…":"Speichern"}</button></div></footer></form>}</section></div>}
 </div>
}
