"use client";

import { Component, useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { AUTHORING_FIELDS, AUTHORING_STEPS, AUTHORING_TAXONOMY_VERSION, getAuthoringFieldsForContext, getPlaceTypeConflict, validateAuthoringSubmission, type AuthoringField, type AuthoringRole, type AuthoringSectionState } from "@backyrd/world-knowledge-core";
import type { WorldAuthoringClient } from "./session";
export { sessionRecoveringAuthoringClient, type RpcResult, type WorldAuthoringAuth, type WorldAuthoringClient } from "./session";


type SpotListItem = { spotId: string; name: string; primaryCategory?: string; lifecycleStatus: "ACTIVE" | "ARCHIVED"; scope: string; answerCount: number; conflictCount: number; manifestHash?: string; catalogOrigin?: "MANUAL" | "LEGACY_PRODUCTION_IMPORT"; cohortSelected?: boolean; unconfirmedLegacyCount?: number; ambiguousLegacyCount?: number };
type Answer = { claimId: string; claimHash: string; knowledgeState: string; value: unknown; observedAt: string; validFrom?: string; validUntil?: string; visibility: string; verificationMethod?: string; confirmationDueAt?: string };
type TaxonomyCandidate = { candidateId: string; primaryCategory: string; value: unknown; taxonomyVersion: string; occurredAt: string; engineAuthorized: false };
type SpotDetail = { scope: string; lifecycleStatus: string; spotId: string; fallbackName: string; actor: { role: "ADMIN" | "VERIFIED_OWNER"; entitlement: AuthoringRole; allowedAttributeKeys: string[] }; answers: Record<string, Answer>; applicability: Record<string, string>; taxonomyCandidates?: Record<string, TaxonomyCandidate>; reviewItems: Array<{ class: string; priority: string; attributeKey?: string; reasonCodes: string[] }>; manifest: null | { manifestId: string; manifestHash: string; resolutionHash: string; inputHash: string; worldSnapshot: unknown; decisionProjection: unknown } };
type LegacyValue = { id: string; batchId: string; sourceField: string; targetKey: string | null; mappingStatus: string; disposition: string; reasonCode: string; value: unknown; selected: boolean; confirmed: boolean; originalValueHash: string; mappingRule: string; resultHash: string };
type LegacySummary = { spotId: string; values: LegacyValue[]; summary: { prefilled: number; normalized: number; reviewRequired: number; excluded: number; confirmed: number } };

const NEW_SPOT = "__new__";
const makeId = (prefix: string) => `${prefix}:${crypto.randomUUID()}`;
const canonicalJson = (value: unknown): string => JSON.stringify(value, (_, item) => item && typeof item === "object" && !Array.isArray(item) ? Object.fromEntries(Object.entries(item).sort(([a], [b]) => a.localeCompare(b))) : item);
const sha256 = async (value: unknown) => Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(canonicalJson(value))))).map((byte) => byte.toString(16).padStart(2, "0")).join("");

const technicalCode = (error: unknown): string => error instanceof Error ? error.message : typeof error === "string" ? error : "unknown_error";
export function translateAuthoringError(error: unknown, label?: string): string {
  const raw = technicalCode(error);
  if (raw.includes(": Bitte ") || raw.startsWith("Bitte ")) return raw;
  const code = raw.toLowerCase();
  const prefix = label ? `${label}: ` : "";
  if (code.includes("invalid_session") || code.includes("authentication_required") || code.includes("jwt")) return "Deine lokale Sitzung ist abgelaufen. Bitte melde dich erneut an; deine Eingaben bleiben erhalten.";
  if (code.includes("endpoint_mismatch") || code.includes("local_world_knowledge_not_configured")) return "Die lokale Testumgebung ist nicht korrekt verbunden. Bitte starte Admin und Supabase mit derselben lokalen Konfiguration neu.";
  if (code.includes("invalid_attribute_value")) return `${prefix}Der Wert passt noch nicht zum erwarteten Format. Bitte prüfe die markierte Eingabe.`;
  if (code.includes("invalid_taxonomy_candidate") || code.includes("taxonomy_candidate_category_conflict")) return `${prefix}Die Auswahl passt nicht zur aktuellen Hauptkategorie. Bitte lade den Spot neu und wähle aus der angezeigten Liste.`;
  if (code.includes("taxonomy_candidate_contract_mismatch")) return `${prefix}Diese Auswahl stammt aus einer anderen Taxonomie-Version und muss neu geprüft werden.`;
  if (code.includes("attribute_entitlement_denied") || code.includes("world_authoring_scope_denied") || code.includes("spot_owner_required")) return `${prefix}Du darfst diese Angabe für diesen Spot nicht bearbeiten.`;
  if (code.includes("current_state_valid_until_required")) return `${prefix}Ein aktueller Zustand benötigt ein Gültig-bis-Datum.`;
  if (code.includes("claim_idempotency_conflict")) return `${prefix}Diese Änderung wurde bereits mit anderem Inhalt verarbeitet. Bitte lade den Spot neu und prüfe den aktuellen Stand.`;
  if (code.includes("founder_authoring_environment_disabled")) return "Die lokale Founder-Testumgebung ist nicht aktiviert. Es wurden keine Daten verändert.";
  if (code.includes("failed to fetch") || code.includes("network")) return "Die lokale Verbindung ist unterbrochen. Bitte prüfe, ob Supabase und die Oberfläche laufen, und versuche es erneut.";
  return `${prefix}Die Aktion konnte nicht abgeschlossen werden. Deine Eingaben bleiben erhalten; bitte versuche es erneut.`;
}

const weekdays = [["MONDAY", "Montag"], ["TUESDAY", "Dienstag"], ["WEDNESDAY", "Mittwoch"], ["THURSDAY", "Donnerstag"], ["FRIDAY", "Freitag"], ["SATURDAY", "Samstag"], ["SUNDAY", "Sonntag"]] as const;
const objectValue = (value: unknown): Record<string, unknown> => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
const fieldFor = (key: string | null) => key ? AUTHORING_FIELDS.find((field) => field.attributeKey === key) : undefined;
const sourceLabels: Readonly<Record<string, string>> = Object.freeze({ name: "Name", address: "Adresse", city: "Ort", country: "Land", lat: "Breitengrad", lng: "Längengrad", category: "Hauptkategorie", website: "Webseite", phone: "Telefonnummer", email: "E-Mail", price_level: "Bisherige Preisangabe", hours_regular: "Reguläre Öffnungszeiten", id: "Spot-Identität" });
const weekdayLabels: Readonly<Record<string, string>> = Object.freeze({ MON: "Montag", MONDAY: "Montag", Montag: "Montag", TUE: "Dienstag", TUESDAY: "Dienstag", Dienstag: "Dienstag", WED: "Mittwoch", WEDNESDAY: "Mittwoch", Mittwoch: "Mittwoch", THU: "Donnerstag", THURSDAY: "Donnerstag", Donnerstag: "Donnerstag", FRI: "Freitag", FRIDAY: "Freitag", Freitag: "Freitag", SAT: "Samstag", SATURDAY: "Samstag", Samstag: "Samstag", SUN: "Sonntag", SUNDAY: "Sonntag", Sonntag: "Sonntag" });
const displayCodes: Readonly<Record<string, string>> = Object.freeze({ ALLOWED: "Erlaubt", NOT_ALLOWED: "Nicht erlaubt", CONDITIONAL: "Unter Bedingungen", ALL_AGES: "Alle Altersgruppen", MINIMUM_AGE: "Mindestalter", NOT_REQUIRED: "Nicht nötig", RECOMMENDED: "Empfohlen", REQUIRED: "Erforderlich", OPEN: "Geöffnet", CLOSED: "Geschlossen", TEMPORARILY_CLOSED: "Vorübergehend geschlossen", LIMITED: "Eingeschränkt", FULL: "Ausgelastet", KITCHEN_CLOSED: "Küche geschlossen", AREA_CLOSED: "Bereich geschlossen", VENUE: "Gesamter Spot", KITCHEN: "Küche", TERRACE: "Terrasse / Außenbereich", INDOOR: "Innenbereich", UNKNOWN: "Unbekannt" });
function humanValue(attributeKey: string | null, value: unknown): string {
  if (value === null || value === undefined || value === "") return "Kein sicher übernehmbarer Wert";
  const field = fieldFor(attributeKey);
  if (typeof value === "boolean") return value ? "Ja" : "Nein";
  if (typeof value === "string") return field?.allowedValues.find((option) => option.value === value)?.label ?? value;
  if (typeof value === "number") return new Intl.NumberFormat("de-CH", { maximumFractionDigits: 6 }).format(value);
  if (Array.isArray(value)) {
    if (value.every((entry) => typeof entry === "string")) return value.map((entry) => field?.allowedValues.find((option) => option.value === entry)?.label ?? entry).join(", ");
    if (value.every((entry) => entry && typeof entry === "object" && ("day" in entry || "date" in entry))) return value.map((entry) => { const row = entry as Record<string, unknown>; const intervals = Array.isArray(row.intervals) ? row.intervals as Record<string, unknown>[] : row.open && row.close ? [{ start: row.open, end: row.close }] : []; const times = intervals.map((interval) => `${String(interval.start ?? interval.from ?? "?").slice(0, 5)}–${String(interval.end ?? interval.to ?? "?").slice(0, 5)}`).join(" und "); return `${weekdayLabels[String(row.day)] ?? String(row.date ?? row.day)}: ${row.status === "CLOSED" ? "geschlossen" : times || "keine Zeit hinterlegt"}`; }).join("\n");
    return `${value.length} Einträge`;
  }
  if (typeof value === "object") {
    const item = value as Record<string, unknown>;
    if ("min" in item && "max" in item) return `${item.min} bis ${item.max}`;
    if ("kind" in item) return `${displayCodes[String(item.kind)] ?? "Betriebszustand"} · ${displayCodes[String(item.scope)] ?? "Bereich noch offen"}`;
    if ("policy" in item) return [displayCodes[String(item.policy)] ?? "Regel erfasst", item.minimumAge != null ? `ab ${item.minimumAge} Jahren` : null, item.appliesFromTime ? `ab ${item.appliesFromTime}` : null].filter(Boolean).join(" · ");
    return "Strukturierte Angabe";
  }
  return String(value);
}
const legacyStatusText = (item: LegacyValue, alreadyAnswered: boolean, candidateValid: boolean) => item.confirmed ? "Bestätigt" : alreadyAnswered ? "Bereits neu erfasst – keine erneute Bestätigung nötig" : item.disposition === "PREFILL_REQUIRES_CONFIRMATION" && candidateValid ? "Aus dem bisherigen System – bitte prüfen" : item.disposition === "PREFILL_REQUIRES_CONFIRMATION" ? "Format kann nicht sicher übernommen werden – bitte neu auswählen" : item.disposition === "REVIEW_REQUIRED" ? "Mehrdeutig – manuelle Auswahl erforderlich" : item.disposition === "IDENTITY_ONLY" ? "Bestehende Spot-Identität bleibt erhalten" : "Nicht in World Knowledge übernehmbar";
const legacyReasonText = (item: LegacyValue) => ({ LEGACY_VALUE_REQUIRES_ADMIN_CONFIRMATION: "Die Angabe hat keine ausreichend gebundene Bestätigung und braucht deine bewusste Prüfung.", ALLOWLISTED_CATEGORY_NORMALIZATION: "Die bisherige Kategorie wurde eindeutig auf eine freigegebene Hauptkategorie abgebildet.", PUBLIC_CONTACT_SEMANTICS_UNPROVEN: "Es ist nicht belegt, dass diese E-Mail als öffentliche Spot-Adresse gedacht war.", LEGACY_SEMANTICS_AMBIGUOUS: "Die alte Bedeutung entspricht keiner neuen Stufe eindeutig.", CANONICAL_PUBLIC_SPOT_ID_RETAINED: "Die bestehende Spot-ID wird unverändert weiterverwendet." } as Record<string, string>)[item.reasonCode] ?? "Diese Angabe kann nicht automatisch als bestätigte World-Information übernommen werden.";
type TimeInterval = { start: string; end: string };
type WeeklyRow = { day: string; intervals: TimeInterval[] };

const validTime = (value: unknown): value is string => typeof value === "string" && /^(?:[01]\d|2[0-3]):[0-5]\d$/.test(value);
const safeIsoDateTime = (value: string): string => { const parsed = Date.parse(value); return Number.isFinite(parsed) ? new Date(parsed).toISOString() : ""; };
const safeIntervals = (value: unknown): TimeInterval[] => Array.isArray(value) ? value.flatMap((entry) => {
  const row = objectValue(entry); const start = row.start ?? row.from; const end = row.end ?? row.to;
  return validTime(start) && validTime(end) ? [{ start, end }] : [];
}) : [];
const safeWeeklyRows = (value: unknown): WeeklyRow[] => Array.isArray(value) ? value.flatMap((entry) => {
  const row = objectValue(entry); return typeof row.day === "string" ? [{ day: row.day, intervals: safeIntervals(row.intervals) }] : [];
}) : [];

class FieldErrorBoundary extends Component<{ label: string; children: ReactNode }, { failed: boolean }> {
  state = { failed: false };
  static getDerivedStateFromError() { return { failed: true }; }
  componentDidUpdate(previous: Readonly<{ label: string; children: ReactNode }>) { if (previous.label !== this.props.label && this.state.failed) this.setState({ failed: false }); }
  render() { return this.state.failed ? <div className="wk-field-error" role="alert"><strong>{this.props.label}</strong><span>Diese gespeicherte Angabe hat ein unerwartetes Format. Deine Daten wurden nicht verändert. Bitte öffne die Expertensicht oder erfasse den Wert neu.</span></div> : this.props.children; }
}

function IntervalsInput({ label, intervals, disabled, onChange }: { label: string; intervals: TimeInterval[]; disabled?: boolean; onChange(value: TimeInterval[]): void }) {
  const update = (index: number, patch: Partial<TimeInterval>) => onChange(intervals.map((interval, intervalIndex) => intervalIndex === index ? { ...interval, ...patch } : interval));
  return <div className="wk-intervals">{intervals.map((interval, index) => <div className="wk-interval" key={index}>
    <input aria-label={`${label} Intervall ${index + 1} von`} type="time" value={validTime(interval.start) ? interval.start : ""} disabled={disabled} onChange={(event) => update(index, { start: event.target.value })} />
    <span>bis</span>
    <input aria-label={`${label} Intervall ${index + 1} bis`} type="time" value={validTime(interval.end) ? interval.end : ""} disabled={disabled} onChange={(event) => update(index, { end: event.target.value })} />
    {intervals.length > 1 && <button type="button" className="wk-icon-button" aria-label={`${label} Intervall ${index + 1} entfernen`} onClick={() => onChange(intervals.filter((_, intervalIndex) => intervalIndex !== index))}>−</button>}
  </div>)}{!disabled && intervals.length < 8 && <button type="button" className="wk-secondary wk-add-interval" onClick={() => onChange([...intervals, { start: "09:00", end: "18:00" }])}>+ Weiteres Zeitfenster</button>}</div>;
}

function WeeklyScheduleInput({ value, onChange }: { value: unknown; onChange(value: unknown): void }) {
  const schedule = safeWeeklyRows(value);
  const update = (day: string, intervals: TimeInterval[] | null) => onChange(intervals ? [...schedule.filter((row) => row.day !== day), { day, intervals }] : schedule.filter((row) => row.day !== day));
  return <div className="wk-schedule">{weekdays.map(([day, label]) => { const row = schedule.find((item) => item.day === day); const status = !row ? "NOT_SET" : row.intervals.length ? "OPEN" : "CLOSED"; return <div className="wk-schedule-row" key={day}><label>{label}<select aria-label={`${label} Status`} value={status} onChange={(event) => update(day, event.target.value === "NOT_SET" ? null : event.target.value === "CLOSED" ? [] : [{ start: "09:00", end: "18:00" }])}><option value="NOT_SET">Noch nicht angegeben</option><option value="OPEN">Geöffnet</option><option value="CLOSED">Geschlossen</option></select></label>{status === "OPEN" ? <IntervalsInput label={label} intervals={row?.intervals ?? []} onChange={(intervals) => update(day, intervals)} /> : <span className="wk-day-hint">{status === "CLOSED" ? "Bewusst als geschlossen erfasst" : "Es wird keine Aussage über diesen Tag gespeichert"}</span>}</div>; })}</div>;
}

function SpecialHoursInput({ value, onChange }: { value: unknown; onChange(value: unknown): void }) {
  const rows = Array.isArray(value) ? value.flatMap((entry) => { const row = objectValue(entry); return typeof row.date === "string" && (row.status === "OPEN" || row.status === "CLOSED") ? [{ date: row.date, status: row.status, intervals: safeIntervals(row.intervals) }] : []; }) : [];
  const update = (index: number, patch: Partial<(typeof rows)[number]>) => onChange(rows.map((row, rowIndex) => rowIndex === index ? { ...row, ...patch } : row));
  return <div className="wk-schedule">{rows.map((row, index) => <div className="wk-special-row" key={`${row.date}:${index}`}><div className="wk-special-heading"><input aria-label={`Sondertag ${index + 1} Datum`} type="date" value={row.date} onChange={(event) => update(index, { date: event.target.value })} /><select aria-label={`Sondertag ${index + 1} Status`} value={row.status} onChange={(event) => update(index, { status: event.target.value as "OPEN" | "CLOSED", intervals: event.target.value === "CLOSED" ? [] : row.intervals.length ? row.intervals : [{ start: "09:00", end: "18:00" }] })}><option value="OPEN">Geöffnet</option><option value="CLOSED">Geschlossen</option></select><button type="button" className="wk-secondary" onClick={() => onChange(rows.filter((_, rowIndex) => rowIndex !== index))}>Entfernen</button></div>{row.status === "OPEN" && <IntervalsInput label={`Sondertag ${index + 1}`} intervals={row.intervals} onChange={(intervals) => update(index, { intervals })} />}</div>)}<button type="button" className="wk-secondary" onClick={() => onChange([...rows, { date: new Date().toISOString().slice(0, 10), status: "CLOSED", intervals: [] }])}>+ Sondertag</button></div>;
}

function RuleInput({ control, value, onChange }: { control: AuthoringField["control"]; value: unknown; onChange(value: unknown): void }) {
  const current = objectValue(value);
  if (control === "RESERVATION_RULE") { const days = Array.isArray(current.days) ? current.days as string[] : []; return <div className="wk-structured"><label>Reservation<select className="wk-input" value={String(current.mode ?? "NOT_REQUIRED")} onChange={(event) => onChange({ mode: event.target.value, minimumPartySize: current.minimumPartySize ?? null, days, fromTime: current.fromTime ?? null, toTime: current.toTime ?? null })}><option value="NOT_REQUIRED">Nicht nötig</option><option value="RECOMMENDED">Empfohlen</option><option value="REQUIRED">Erforderlich</option><option value="CONDITIONAL">Unter Bedingungen</option></select></label><label>Ab Gruppengröße<input className="wk-input" type="number" min="1" value={current.minimumPartySize == null ? "" : String(current.minimumPartySize)} onChange={(event) => onChange({ ...current, mode: current.mode ?? "CONDITIONAL", minimumPartySize: event.target.value ? Number(event.target.value) : null, days, fromTime: current.fromTime ?? null, toTime: current.toTime ?? null })} /></label><div className="wk-choices">{weekdays.map(([day, label]) => <button type="button" className={days.includes(day) ? "selected" : ""} key={day} onClick={() => onChange({ ...current, mode: current.mode ?? "CONDITIONAL", minimumPartySize: current.minimumPartySize ?? null, days: days.includes(day) ? days.filter((item) => item !== day) : [...days, day], fromTime: current.fromTime ?? null, toTime: current.toTime ?? null })}>{label.slice(0, 2)}</button>)}</div><label>Von<input className="wk-input" type="time" value={String(current.fromTime ?? "")} onChange={(event) => onChange({ ...current, minimumPartySize: current.minimumPartySize ?? null, days, fromTime: event.target.value || null, toTime: current.toTime ?? null })} /></label><label>Bis<input className="wk-input" type="time" value={String(current.toTime ?? "")} onChange={(event) => onChange({ ...current, minimumPartySize: current.minimumPartySize ?? null, days, fromTime: current.fromTime ?? null, toTime: event.target.value || null })} /></label></div>; }
  if (control === "CONSUMPTION_RULE") return <div className="wk-structured"><label>Regel<select className="wk-input" value={String(current.policy ?? "NOT_ALLOWED")} onChange={(event) => onChange({ policy: event.target.value, exceptions: Array.isArray(current.exceptions) ? current.exceptions : [] })}><option value="ALLOWED">Erlaubt</option><option value="NOT_ALLOWED">Nicht erlaubt</option><option value="CONDITIONAL">Unter Bedingungen</option></select></label><label>Ausnahmen<input className="wk-input" value={Array.isArray(current.exceptions) ? current.exceptions.join("; ") : ""} placeholder="z. B. Babynahrung; Geburtstagskuchen" onChange={(event) => onChange({ policy: current.policy ?? "CONDITIONAL", exceptions: event.target.value.split(";").map((item) => item.trim()).filter(Boolean) })} /></label></div>;
  if (control === "PET_ACCESS_RULE") { const options = <><option value="ALLOWED">Erlaubt</option><option value="NOT_ALLOWED">Nicht erlaubt</option><option value="UNKNOWN">Noch unbekannt</option></>; return <div className="wk-structured"><label>Innen<select className="wk-input" value={String(current.indoor ?? "UNKNOWN")} onChange={(event) => onChange({ indoor: event.target.value, outdoor: current.outdoor ?? "UNKNOWN", assistanceAnimals: current.assistanceAnimals ?? "UNKNOWN", notes: current.notes ?? null })}>{options}</select></label><label>Außen<select className="wk-input" value={String(current.outdoor ?? "UNKNOWN")} onChange={(event) => onChange({ indoor: current.indoor ?? "UNKNOWN", outdoor: event.target.value, assistanceAnimals: current.assistanceAnimals ?? "UNKNOWN", notes: current.notes ?? null })}>{options}</select></label><label>Assistenztiere<select className="wk-input" value={String(current.assistanceAnimals ?? "UNKNOWN")} onChange={(event) => onChange({ indoor: current.indoor ?? "UNKNOWN", outdoor: current.outdoor ?? "UNKNOWN", assistanceAnimals: event.target.value, notes: current.notes ?? null })}>{options}</select></label><label>Hinweis<input className="wk-input" value={String(current.notes ?? "")} onChange={(event) => onChange({ indoor: current.indoor ?? "UNKNOWN", outdoor: current.outdoor ?? "UNKNOWN", assistanceAnimals: current.assistanceAnimals ?? "UNKNOWN", notes: event.target.value || null })} /></label></div>; }
  return <div className="wk-structured"><label>Zugang<select className="wk-input" value={String(current.policy ?? "ALL_AGES")} onChange={(event) => onChange({ policy: event.target.value, minimumAge: event.target.value === "ALL_AGES" ? null : current.minimumAge ?? 18, appliesFromTime: event.target.value === "ALL_AGES" ? null : current.appliesFromTime ?? null })}><option value="ALL_AGES">Alle Altersgruppen</option><option value="MINIMUM_AGE">Mindestalter</option></select></label>{current.policy === "MINIMUM_AGE" && <><label>Mindestalter<input className="wk-input" type="number" min="0" max="120" value={String(current.minimumAge ?? 18)} onChange={(event) => onChange({ ...current, minimumAge: Number(event.target.value), appliesFromTime: current.appliesFromTime ?? null })} /></label><label>Gilt ab Uhrzeit<input className="wk-input" type="time" value={String(current.appliesFromTime ?? "")} onChange={(event) => onChange({ ...current, minimumAge: current.minimumAge ?? 18, appliesFromTime: event.target.value || null })} /></label></>}</div>;
}

function FieldInput({ field, answer, candidate, onSave, onSaveCandidate, onApplicability, onConfirm, onError, disabled }: { field: AuthoringField; answer?: Answer; candidate?: TaxonomyCandidate; onSave(state: string, value: unknown, validUntil?: string): Promise<void>; onSaveCandidate?(value: readonly string[]): Promise<void>; onApplicability(value: "APPLICABLE" | "NOT_APPLICABLE"): Promise<void>; onConfirm(): Promise<void>; onError(message: string | null): void; disabled: boolean }) {
  const initialValue = answer?.value ?? candidate?.value ?? (field.control === "MULTI_SELECT" ? [] : "");
  const [value, setValue] = useState<unknown>(initialValue);
  const [saving, setSaving] = useState(false);
  const [validUntil, setValidUntil] = useState(answer?.validUntil ?? "");
  const [error, setError] = useState("");
  const [optionSearch, setOptionSearch] = useState("");
  useEffect(() => setValue(answer?.value ?? candidate?.value ?? (field.control === "MULTI_SELECT" ? [] : "")), [answer, candidate, field.control]);
  const save = async (state: string, next: unknown = value, validUntilValue?: string) => { setSaving(true); setError(""); onError(null); try { await onSave(state, next, validUntilValue); } catch (cause) { const message = translateAuthoringError(cause, field.label); setError(message); onError(message); } finally { setSaving(false); } };
  const safeSecondaryAction = async (action: () => Promise<void>) => { setSaving(true); setError(""); onError(null); try { await action(); } catch (cause) { const message = translateAuthoringError(cause, field.label); setError(message); onError(message); } finally { setSaving(false); } };
  const selected = Array.isArray(value) ? value as string[] : [];
  const availableValues = new Set(field.allowedValues.map((option) => option.value));
  const incompatibleSelections = selected.filter((entry) => !availableValues.has(entry));
  const selectableSelections = selected.filter((entry) => availableValues.has(entry));
  const hasPendingSelection = selectableSelections.some((entry) => field.allowedValues.find((option) => option.value === entry)?.state === "NOT_CONFIGURED");
  const shownOptions = field.allowedValues.filter((option) => !optionSearch || `${option.label} ${option.group ?? ""}`.toLocaleLowerCase("de-CH").includes(optionSearch.toLocaleLowerCase("de-CH")));
  const optionGroups = [...new Set(shownOptions.map((option) => option.group ?? "Auswahl"))];
  return <fieldset className="wk-field" disabled={disabled || saving}>
    <legend>{field.label}</legend><p>{field.help}</p>
    {field.control === "YES_NO" ? <div className="wk-segmented">
      <button type="button" className={answer?.knowledgeState === "KNOWN_TRUE" ? "selected" : ""} onClick={() => save("KNOWN_TRUE", true)}>Ja</button>
      <button type="button" className={answer?.knowledgeState === "KNOWN_FALSE" ? "selected" : ""} onClick={() => save("KNOWN_FALSE", false)}>Nein</button>
      <button type="button" className={answer?.knowledgeState === "UNKNOWN" ? "selected" : ""} onClick={() => save("UNKNOWN", null)}>Noch unbekannt</button>
      <button type="button" onClick={() => void safeSecondaryAction(() => onApplicability("NOT_APPLICABLE"))}>Nicht relevant</button>
    </div> : field.control === "MULTI_SELECT" ? <div className="wk-option-picker">{incompatibleSelections.length > 0 && <div className="wk-field-warning" role="status"><strong>Bisher gespeicherte Auswahl passt nicht zur aktuellen Einordnung:</strong><span>{humanValue(field.attributeKey, incompatibleSelections)}</span><span>Sie bleibt historisch erhalten und wird erst durch eine bewusste neue Auswahl ersetzt.</span></div>}{candidate && <div className="wk-field-warning" role="status"><strong>Als offener Taxonomie-Vorschlag gespeichert</strong><span>Diese Auswahl bleibt im lokalen Authoring erhalten, ist aber noch kein freigegebener World-Fakt und erscheint nicht im Engine-Snapshot.</span></div>}{field.allowedValues.length > 12 && <label className="wk-option-search">Auswahl durchsuchen<input className="wk-input" value={optionSearch} onChange={(event) => setOptionSearch(event.target.value)} placeholder={`In ${field.label} suchen`} /></label>}{optionGroups.map((group) => <section className="wk-option-group" key={group}><h4>{group}</h4><div className="wk-choices">{shownOptions.filter((option) => (option.group ?? "Auswahl") === group).map((option) => { const active = selected.includes(option.value); const pending = option.state === "NOT_CONFIGURED"; return <button type="button" key={option.value} className={active ? "selected" : ""} aria-pressed={active} title={pending ? "Kann als offener Vorschlag gespeichert werden; noch kein World-Fakt." : undefined} onClick={() => setValue(active ? selectableSelections.filter((item) => item !== option.value) : [...selectableSelections, option.value])}>{option.label}{pending ? <small>Noch nicht freigegeben</small> : null}</button>; })}</div></section>)}{!field.allowedValues.some((option) => option.state !== "NOT_CONFIGURED") && <div className="wk-note"><strong>Noch keine kanonische Auswahl freigegeben.</strong><p>Du kannst die fachlich passende Auswahl als offenen Vorschlag speichern. Sie wird erst nach einer Product-/Registry-Entscheidung zu einem World-Fakt.</p></div>}<div className="wk-inline"><button type="button" disabled={!selectableSelections.length} onClick={() => hasPendingSelection && onSaveCandidate ? void safeSecondaryAction(() => onSaveCandidate(selectableSelections)) : save("KNOWN_VALUE", selectableSelections)}>{hasPendingSelection ? "Als offenen Vorschlag speichern" : "Auswahl übernehmen"}</button><button type="button" className="wk-secondary" onClick={() => save("UNKNOWN", null)}>Bewusst unbekannt</button><button type="button" className="wk-secondary" onClick={() => void safeSecondaryAction(() => onApplicability("NOT_APPLICABLE"))}>Nicht relevant</button></div></div>
    : field.control === "SINGLE_SELECT" ? <select aria-label={field.label} className="wk-input" value={String(value)} onChange={(event) => { const next = event.target.value; setValue(next); if (next) void save("KNOWN_VALUE", next); }}><option value="">Bitte auswählen</option>{field.allowedValues.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select>
    : field.control === "INTEGER_RANGE" ? <div className="wk-range"><label>Von<input className="wk-input" type="number" min={0} value={(value as { min?: number })?.min ?? ""} onChange={(event) => { const current = typeof value === "object" && value ? value : {}; const next = event.target.value; setValue(next === "" ? Object.fromEntries(Object.entries(current).filter(([key]) => key !== "min")) : { ...current, min: Number(next) }); }} /></label><label>Bis<input className="wk-input" type="number" min={0} value={(value as { max?: number })?.max ?? ""} onChange={(event) => { const current = typeof value === "object" && value ? value : {}; const next = event.target.value; setValue(next === "" ? Object.fromEntries(Object.entries(current).filter(([key]) => key !== "max")) : { ...current, max: Number(next) }); }} /></label><button type="button" onClick={() => save("KNOWN_VALUE")}>Übernehmen</button></div>
    : field.control === "CURRENT_STATE" ? <div className="wk-structured"><label>Zustand<select className="wk-input" value={(value as { kind?: string })?.kind ?? ""} onChange={(e) => setValue({ ...(typeof value === "object" && value ? value : {}), kind: e.target.value })}><option value="">Bitte wählen</option>{field.allowedValues.map((option) => <option value={option.value} key={option.value}>{option.label}</option>)}</select></label><label>Betroffener Bereich<select className="wk-input" value={(value as { scope?: string })?.scope ?? ""} onChange={(e) => setValue({ ...(typeof value === "object" && value ? value : {}), scope: e.target.value })}><option value="">Bitte wählen</option><option value="VENUE">Gesamter Spot</option><option value="KITCHEN">Küche</option><option value="TERRACE">Terrasse/Außenbereich</option><option value="INDOOR">Innenbereich</option></select></label><label>Gültig bis<input className="wk-input" type="datetime-local" value={validUntil ? validUntil.slice(0, 16) : ""} onChange={(e) => setValidUntil(e.target.value ? safeIsoDateTime(e.target.value) : "")} /></label><button type="button" disabled={!validUntil} onClick={() => save("KNOWN_VALUE", value, validUntil)}>Aktuellen Zustand übernehmen</button></div>
    : field.control === "WEEKLY_SCHEDULE" ? <><WeeklyScheduleInput value={value} onChange={setValue} /><button type="button" onClick={() => save("KNOWN_VALUE")}>Zeiten übernehmen</button></>
    : field.control === "SPECIAL_HOURS" ? <><SpecialHoursInput value={value} onChange={setValue} /><button type="button" onClick={() => save("KNOWN_VALUE")}>Sondertage übernehmen</button></>
    : ["RESERVATION_RULE", "CONSUMPTION_RULE", "PET_ACCESS_RULE", "AGE_ACCESS_RULE"].includes(field.control) ? <><RuleInput control={field.control} value={value} onChange={setValue} /><button type="button" onClick={() => save("KNOWN_VALUE")}>Regel übernehmen</button></>
    : field.valueType === "COUNTRY_CODE" ? <div className="wk-inline"><select aria-label={field.label} className="wk-input" value={String(value ?? "")} onChange={(event) => setValue(event.target.value)}><option value="">Bitte auswählen</option><option value="CH">Schweiz</option><option value="DE">Deutschland</option><option value="AT">Österreich</option><option value="FR">Frankreich</option><option value="IT">Italien</option><option value="LI">Liechtenstein</option></select><button type="button" onClick={() => save("KNOWN_VALUE")}>Übernehmen</button></div>
    : field.valueType === "IANA_TIMEZONE" ? <div className="wk-inline"><select aria-label={field.label} className="wk-input" value={String(value ?? "")} onChange={(event) => setValue(event.target.value)}><option value="">Bitte auswählen</option><option value="Europe/Zurich">Europe/Zurich</option><option value="Europe/Berlin">Europe/Berlin</option><option value="Europe/Vienna">Europe/Vienna</option><option value="Europe/Paris">Europe/Paris</option><option value="Europe/Rome">Europe/Rome</option></select><button type="button" onClick={() => save("KNOWN_VALUE")}>Übernehmen</button></div>
    : field.control === "TEXTAREA" ? <div className="wk-stack"><textarea aria-label={field.label} className="wk-input wk-textarea" value={String(value ?? "")} maxLength={800} onChange={(event) => setValue(event.target.value)} /><span>{String(value ?? "").length}/800 Zeichen</span><button type="button" onClick={() => save("KNOWN_VALUE")}>Übernehmen</button></div>
    : <div className="wk-inline"><input aria-label={field.label} className="wk-input" type={field.control === "EMAIL" ? "email" : field.control === "URL" ? "url" : field.control === "NUMBER" ? "number" : field.control === "PHONE" ? "tel" : "text"} placeholder={field.control === "PHONE" ? "+41781234567" : field.control === "URL" ? "https://…" : undefined} value={String(value ?? "")} onChange={(event) => setValue(field.control === "NUMBER" ? event.target.value === "" ? "" : Number(event.target.value) : event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void save("KNOWN_VALUE"); }} /><button type="button" onClick={() => save("KNOWN_VALUE")}>Übernehmen</button></div>}
    {!(["YES_NO", "MULTI_SELECT"] as string[]).includes(field.control) && <div className="wk-knowledge-actions"><span>Du kannst die Angabe auch bewusst offen lassen:</span><button type="button" className="wk-secondary" onClick={() => save("UNKNOWN", null)}>Noch unbekannt</button><button type="button" className="wk-secondary" onClick={() => void safeSecondaryAction(() => onApplicability("NOT_APPLICABLE"))}>Nicht relevant</button></div>}
    {answer && <div className="wk-saved">{answer.knowledgeState === "UNKNOWN" ? "Bewusst als unbekannt gespeichert" : "Bestätigt"} · {new Date(answer.observedAt).toLocaleDateString("de-CH")} {answer.confirmationDueAt && new Date(answer.confirmationDueAt) <= new Date() ? <button type="button" className="wk-secondary" onClick={() => void safeSecondaryAction(onConfirm)}>Weiterhin aktuell</button> : null}</div>}
    {error && <div className="wk-field-error" role="alert">{error}</div>}
    {disabled && <span className="wk-locked">Diese objektive Zusatzangabe ist im Owner-Pro-Umfang verfügbar. Ein Admin kann sie ebenfalls pflegen.</span>}
  </fieldset>;
}

function LegacyReview({ legacy, answers, selection, onSelection, onConfirm, onOpenField }: { legacy: LegacySummary; answers: Record<string, Answer>; selection: string[]; onSelection(value: string[]): void; onConfirm(): void; onOpenField(attributeKey: string | null): void }) {
  const groups = AUTHORING_STEPS.slice(0, 8).map((step) => ({ ...step, values: legacy.values.filter((item) => item.targetKey ? step.attributeKeys.includes(item.targetKey) : step.id === (item.sourceField === "price_level" ? "price" : "basics")) })).filter((group) => group.values.length);
  const actionable = legacy.values.filter((item) => !item.confirmed && !answers[item.targetKey ?? ""] && item.disposition === "PREFILL_REQUIRES_CONFIRMATION" && Boolean(item.targetKey) && validateAuthoringSubmission(item.targetKey, "KNOWN_VALUE", item.value).ok).length;
  const replaced = legacy.values.filter((item) => !item.confirmed && Boolean(item.targetKey && answers[item.targetKey])).length;
  const manual = legacy.values.filter((item) => !item.confirmed && !answers[item.targetKey ?? ""] && (item.disposition === "REVIEW_REQUIRED" || item.disposition === "PREFILL_REQUIRES_CONFIRMATION" && Boolean(item.targetKey) && !validateAuthoringSubmission(item.targetKey, "KNOWN_VALUE", item.value).ok)).length;
  return <section className="wk-panel wk-legacy-panel"><span className="wk-eyebrow">VORHANDENE ANGABEN · BITTE BEWUSST PRÜFEN</span><h2>Aus dem bisherigen System übernehmen</h2><p>Backyrd bestätigt hier nichts automatisch. Vergleiche den bisherigen Vorschlag mit deiner bereits neu erfassten Angabe und wähle nur sichere Werte aus.</p>
    <div className="wk-review"><article><b>Noch zu prüfen</b><strong>{actionable}</strong><span>sichtbar und direkt bestätigbar</span></article><article><b>Manuell wählen</b><strong>{manual}</strong><span>fachliche Auswahl erforderlich</span></article><article><b>Durch neue Angabe erledigt</b><strong>{replaced}</strong><span>nicht mehr als offen gezählt</span></article><article><b>Nicht übernehmbar</b><strong>{legacy.summary.excluded}</strong><span>bleibt außerhalb des World-Modells</span></article><article><b>Bereits bestätigt</b><strong>{legacy.summary.confirmed}</strong><span>nicht erneut angeboten</span></article></div>
    {groups.map((group) => <section className="wk-legacy-group" key={group.id}><h3>{group.order}. {group.title}</h3>{group.values.map((item) => { const field = fieldFor(item.targetKey); const existing = item.targetKey ? answers[item.targetKey] : undefined; const validation = item.targetKey ? validateAuthoringSubmission(item.targetKey, "KNOWN_VALUE", item.value) : null; const candidateValid = validation?.ok === true; const confirmable = !item.confirmed && !existing && item.disposition === "PREFILL_REQUIRES_CONFIRMATION" && candidateValid; return <article className={`wk-legacy-card ${confirmable ? "confirmable" : ""}`} key={item.id}>
        <div className="wk-legacy-card-head">{confirmable ? <label><input type="checkbox" checked={selection.includes(item.id)} onChange={(event) => onSelection(event.target.checked ? [...selection, item.id] : selection.filter((id) => id !== item.id))} /><span>Zur Bestätigung auswählen</span></label> : <span className="wk-legacy-state">{legacyStatusText(item, Boolean(existing), candidateValid)}</span>}<strong>{field?.label ?? sourceLabels[item.sourceField] ?? "Bisherige Angabe"}</strong></div>
        <div className="wk-legacy-compare"><div><small>Bisher vorhanden</small><span>{item.value == null ? item.sourceField === "email" ? "E-Mail vorhanden, aber nicht als öffentlich belegt" : "Wert vorhanden, aber nicht eindeutig zuordenbar" : humanValue(item.targetKey, item.value)}</span></div><div><small>Neu in World Knowledge</small><span>{existing ? humanValue(item.targetKey, existing.value) : candidateValid ? humanValue(item.targetKey, validation.value) : "Noch offen – bitte im passenden Schritt auswählen"}</span></div></div>
        <p>{legacyReasonText(item)}</p>{!confirmable && !item.confirmed && item.disposition !== "EXCLUDED" && item.disposition !== "IDENTITY_ONLY" && <button type="button" className="wk-secondary" onClick={() => onOpenField(item.targetKey)}>Angabe jetzt prüfen</button>}
      </article>; })}</section>)}
    {selection.length > 0 && <div className="wk-confirm-bar"><div><strong>{selection.length} Angabe{selection.length === 1 ? "" : "n"} ausgewählt</strong><span>Es werden nur die sichtbaren, ausgewählten Werte append-only bestätigt.</span></div><button type="button" onClick={onConfirm}>Ausgewählte Angaben bestätigen</button></div>}
  </section>;
}

export function WorldKnowledgeAuthoring({ client, surface, rebuild, exportCohort }: { client: WorldAuthoringClient; surface: "ADMIN" | "OWNER"; rebuild?(spotId: string): Promise<unknown>; exportCohort?(): Promise<unknown> }) {
  const [spots, setSpots] = useState<SpotListItem[]>([]); const [spotId, setSpotId] = useState(""); const [detail, setDetail] = useState<SpotDetail | null>(null); const [legacy, setLegacy] = useState<LegacySummary | null>(null); const [legacySelection,setLegacySelection]=useState<string[]>([]); const [legacyFilter, setLegacyFilter] = useState("ALL"); const [visibleSpotCount, setVisibleSpotCount] = useState(80); const [step, setStep] = useState(0); const [search, setSearch] = useState(""); const [category, setCategory] = useState(""); const [message, setMessage] = useState(""); const [messageKind, setMessageKind] = useState<"SUCCESS" | "ERROR" | "INFO">("INFO"); const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({}); const [expert, setExpert] = useState(false); const [loading, setLoading] = useState(true); const [newName, setNewName] = useState("");
  const categoryOptions = AUTHORING_FIELDS.find((field) => field.attributeKey === "classification.primary_category")?.allowedValues ?? [];
  const loadSpots = useCallback(async () => { setLoading(true); try { const { data, error } = await client.rpc<{ spots: SpotListItem[] }>("world_founder_list_spots_v1", { p_search: search || null, p_primary_category: category || null, p_include_archived: true }); if (error) { setMessageKind("ERROR"); return setMessage(translateAuthoringError(error.message)); } setSpots(data?.spots ?? []); if (!spotId && data?.spots?.[0]) setSpotId(data.spots[0].spotId); } catch (cause) { setMessageKind("ERROR"); setMessage(translateAuthoringError(cause)); } finally { setLoading(false); } }, [client, search, category, spotId]);
  const loadDetail = useCallback(async () => { if (!spotId || spotId === NEW_SPOT) { setLegacy(null); return setDetail(null); } try { const { data, error } = await client.rpc<SpotDetail>("world_authoring_get_spot_v1", { p_spot_id: spotId }); if (error) { setMessageKind("ERROR"); return setMessage(translateAuthoringError(error.message)); } const candidateResult = await client.rpc<Record<string, TaxonomyCandidate>>("world_authoring_get_taxonomy_candidates_v1", { p_spot_id: spotId }); if (candidateResult.error) { setMessageKind("ERROR"); setMessage(translateAuthoringError(candidateResult.error.message)); } setDetail(data ? { ...data, taxonomyCandidates: candidateResult.data ?? {} } : data); if (surface === "ADMIN") { const result = await client.rpc<LegacySummary>("world_admin_get_legacy_import_summary_v1", { p_spot_id: spotId }); if (result.error) { setMessageKind("ERROR"); setMessage(translateAuthoringError(result.error.message)); setLegacy(null); } else setLegacy(result.data); } else setLegacy(null); } catch (cause) { setMessageKind("ERROR"); setMessage(translateAuthoringError(cause)); } }, [client, spotId, surface]);
  useEffect(() => { void loadSpots(); }, [loadSpots]); useEffect(() => { void loadDetail(); setFieldErrors({}); }, [loadDetail]); useEffect(() => setVisibleSpotCount(80), [search, category, legacyFilter]); useEffect(()=>setLegacySelection(legacy?.values.filter((value)=>value.selected&&!value.confirmed&&value.disposition==="PREFILL_REQUIRES_CONFIRMATION"&&!detail?.answers[value.targetKey ?? ""]&&(value.targetKey ? validateAuthoringSubmission(value.targetKey,"KNOWN_VALUE",value.value).ok : false)).map((value)=>value.id)??[]),[legacy,detail]);
  const current = AUTHORING_STEPS[step];
  const primaryCategory = detail?.answers["classification.primary_category"]?.value;
  const fields = useMemo(() => getAuthoringFieldsForContext(current.id, primaryCategory), [current.id, primaryCategory]);
  const placeTypeValue = detail?.answers["classification.place_types"]?.value ?? detail?.taxonomyCandidates?.["classification.place_types"]?.value;
  const placeTypeConflict = useMemo(() => getPlaceTypeConflict(primaryCategory, placeTypeValue), [primaryCategory, placeTypeValue]);
  const sectionState = useCallback((item: (typeof AUTHORING_STEPS)[number]): AuthoringSectionState => {
    if (Object.keys(fieldErrors).some((key) => item.attributeKeys.includes(key))) return "ERROR";
    const relevant = getAuthoringFieldsForContext(item.id, primaryCategory);
    if (!relevant.length && !["basics", "classification", "review"].includes(item.id)) return "NOT_RELEVANT";
    const handled = relevant.filter((field) => Boolean(detail?.answers[field.attributeKey]) || Boolean(detail?.taxonomyCandidates?.[field.attributeKey]) || detail?.applicability[field.attributeKey] === "NOT_APPLICABLE");
    if (!handled.length) return "NOT_VIEWED";
    if (handled.length < relevant.length) return "STARTED";
    if (handled.some((field) => detail?.answers[field.attributeKey]?.knowledgeState === "UNKNOWN" || detail?.applicability[field.attributeKey] === "NOT_APPLICABLE" || Boolean(detail?.taxonomyCandidates?.[field.attributeKey]))) return "INTENTIONALLY_INCOMPLETE";
    return "REVIEWED";
  }, [detail, fieldErrors, primaryCategory]);
  const sectionLabel: Record<AuthoringSectionState, string> = { NOT_VIEWED: "Noch nicht angesehen", STARTED: "Begonnen", REVIEWED: "Vollständig geprüft", INTENTIONALLY_INCOMPLETE: "Bewusst unvollständig", NOT_RELEVANT: "Nicht relevant", ERROR: "Fehlerhaft" };
  const runAction = async (action: () => Promise<unknown>, fallback = "Die Aktion konnte nicht abgeschlossen werden.") => { try { await action(); } catch (cause) { setMessageKind("ERROR"); setMessage(translateAuthoringError(cause) || fallback); } };
  const saveField = async (field: AuthoringField, state: string, value: unknown, validUntil?: string) => { if (!detail) return; const validation = validateAuthoringSubmission(field.attributeKey, state, value); if (!validation.ok) throw new Error(validation.message); if (field.attributeKey === "state.current" && !validUntil) throw new Error(`${field.label}: Ein aktueller Zustand benötigt ein Gültig-bis-Datum.`); const isAdmin = detail.actor.role === "ADMIN"; const parameters = { p_spot_id: detail.spotId, p_attribute_key: field.attributeKey, p_knowledge_state: state, p_value: validation.value, p_observed_at: new Date().toISOString(), p_valid_from: null, p_valid_until: validUntil ?? null, p_visibility: "PUBLIC", p_supersedes_claim_id: detail.answers[field.attributeKey]?.claimId ?? null, p_idempotency_key: makeId(`authoring:${field.attributeKey}`) }; const { error } = await client.rpc(isAdmin ? "world_admin_submit_claim_v1" : "world_owner_submit_claim_v1", parameters); if (error) throw new Error(error.message); setMessageKind("SUCCESS"); setMessage(`${field.label} gespeichert.`); await loadDetail(); };
  const saveTaxonomyCandidate = async (field: AuthoringField, value: readonly string[]) => { if (!detail || typeof primaryCategory !== "string") throw new Error(`${field.label}: Bitte wähle zuerst eine Hauptkategorie.`); const { error } = await client.rpc("world_authoring_submit_taxonomy_candidate_v1", { p_spot_id: detail.spotId, p_attribute_key: field.attributeKey, p_primary_category: primaryCategory, p_candidate_value: value, p_taxonomy_version: AUTHORING_TAXONOMY_VERSION, p_idempotency_key: makeId(`taxonomy-candidate:${field.attributeKey}`) }); if (error) throw new Error(error.message); setMessageKind("SUCCESS"); setMessage(`${field.label} als offener Vorschlag gespeichert. Der Engine-Snapshot bleibt unverändert.`); await loadDetail(); };
  const setApplicability = async (field: AuthoringField, value: "APPLICABLE" | "NOT_APPLICABLE") => { if (!detail) return; const { error } = await client.rpc("world_authoring_set_applicability_v1", { p_spot_id: detail.spotId, p_attribute_key: field.attributeKey, p_applicability: value, p_idempotency_key: makeId(`applicability:${field.attributeKey}`) }); if (error) throw new Error(error.message); await loadDetail(); };
  const confirmAnswer = async (field: AuthoringField) => { const claimId = detail?.answers[field.attributeKey]?.claimId; if (!claimId) return; const { error } = await client.rpc("world_confirm_claim_v1", { p_claim_id: claimId, p_idempotency_key: makeId(`confirmation:${claimId}`) }); if (error) throw new Error(error.message); await loadDetail(); setMessage(`${field.label} wurde als weiterhin aktuell bestätigt.`); };
  const createSpot = async () => { const { data, error } = await client.rpc<{ spotId: string }>("world_founder_create_spot_v1", { p_name: newName, p_owner_id: null, p_idempotency_key: makeId("new-spot") }); if (error) return setMessage(error.message); if (data) { setNewName(""); setSpotId(data.spotId); await loadSpots(); } };
  const analyze = async () => { if (!detail || !rebuild) return; setMessageKind("INFO"); setMessage("Datenvorschau wird aufgebaut …"); try { await rebuild(detail.spotId); await loadDetail(); setMessageKind("SUCCESS"); setMessage("Datenvorschau ist aktuell."); } catch (error) { setMessageKind("ERROR"); setMessage(translateAuthoringError(error)); } };
  const exportSpot = async () => { if (!detail) return; const body = { contractVersion: "backyrd.world-knowledge.authoring-transfer@4a.1", scope: "FOUNDER_EVALUATION_ONLY", sourceSpotId: detail.spotId, exportedAt: new Date().toISOString(), answers: Object.fromEntries(Object.entries(detail.answers).map(([key, answer]) => [key, { knowledgeState: answer.knowledgeState, value: answer.value, validFrom: answer.validFrom ?? null, validUntil: answer.validUntil ?? null, visibility: answer.visibility }])), applicability: detail.applicability, manifest: detail.manifest ? { manifestHash: detail.manifest.manifestHash, resolutionHash: detail.manifest.resolutionHash, inputHash: detail.manifest.inputHash, worldSnapshot: detail.manifest.worldSnapshot } : null }; const payload = { ...body, exportHash: await sha256(body) }; const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" })); link.download = `${String(detail.answers["identity.name"]?.value ?? detail.fallbackName).replaceAll(/[^a-zA-Z0-9äöüÄÖÜß-]+/g, "-")}-world.json`; link.click(); URL.revokeObjectURL(link.href); };
  const importSpot = async (file: File) => { if (!detail) return; const parsed = JSON.parse(await file.text()) as Record<string, unknown>; const { exportHash, ...body } = parsed; if (parsed.contractVersion !== "backyrd.world-knowledge.authoring-transfer@4a.1" || parsed.scope !== "FOUNDER_EVALUATION_ONLY" || typeof exportHash !== "string" || await sha256(body) !== exportHash) throw new Error("Importdatei ist ungültig oder verändert."); const answers = parsed.answers as Record<string, { knowledgeState: string; value: unknown; validFrom?: string | null; validUntil?: string | null; visibility?: string }>;
    for (const [attributeKey, answer] of Object.entries(answers)) { if (!detail.actor.allowedAttributeKeys.includes(attributeKey)) continue; const { error } = await client.rpc(detail.actor.role === "ADMIN" ? "world_admin_submit_claim_v1" : "world_owner_submit_claim_v1", { p_spot_id: detail.spotId, p_attribute_key: attributeKey, p_knowledge_state: answer.knowledgeState, p_value: answer.value, p_observed_at: new Date().toISOString(), p_valid_from: answer.validFrom ?? null, p_valid_until: answer.validUntil ?? null, p_visibility: answer.visibility === "INTERNAL" ? "INTERNAL" : "PUBLIC", p_supersedes_claim_id: detail.answers[attributeKey]?.claimId ?? null, p_idempotency_key: `import:${exportHash}:${attributeKey}` }); if (error) throw new Error(error.message); }
    await loadDetail(); setMessage("Import geprüft und append-only übernommen.");
  };
  const setLifecycle = async () => { if (!detail || surface !== "ADMIN") return; const next = detail.lifecycleStatus === "ACTIVE" ? "ARCHIVED" : "ACTIVE"; const { error } = await client.rpc("world_founder_set_spot_lifecycle_v1", { p_spot_id: detail.spotId, p_lifecycle_status: next, p_confirmation: "FOUNDER TESTSET ÄNDERN" }); if (error) throw new Error(error.message); await loadDetail(); await loadSpots(); };
  const resetTestset = async () => { if (surface !== "ADMIN" || !window.confirm("Wirklich alle aktiven Spots aus dem lokalen Founder-Testset archivieren? Die Historie bleibt erhalten.")) return; const { error } = await client.rpc("world_founder_reset_testset_v1", { p_confirmation: "LOKALES FOUNDER-TESTSET ZURÜCKSETZEN" }); if (error) throw new Error(error.message); setSpotId(""); setDetail(null); await loadSpots(); setMessage("Das lokale Testset wurde archiviert. Die Historie bleibt erhalten."); };
  const confirmLegacy = async () => { if (!legacy || !detail) return; const selected=legacy.values.filter((value)=>legacySelection.includes(value.id)&&!value.confirmed&&!detail.answers[value.targetKey ?? ""]&&value.disposition==="PREFILL_REQUIRES_CONFIRMATION"&&Boolean(value.targetKey)&&validateAuthoringSubmission(value.targetKey,"KNOWN_VALUE",value.value).ok); if(!selected.length){setMessageKind("INFO");return setMessage("Keine bestätigbaren Legacy-Werte ausgewählt.");} const batches=[...new Set(selected.map((value)=>value.batchId))]; if(batches.length!==1){setMessageKind("ERROR");return setMessage("Bitte bestätige jeweils nur Angaben aus demselben Importlauf.");} const ids=selected.map((value)=>value.id).sort(); const selectionHash=(await sha256(ids)).slice(0,24); const { error }=await client.rpc("world_admin_confirm_legacy_values_v1",{p_spot_id:detail.spotId,p_batch_id:batches[0],p_value_ids:ids,p_idempotency_key:`legacy-confirm:${batches[0]}:${detail.spotId}:${selectionHash}`}); if(error)throw new Error(error.message); await loadDetail(); await loadSpots(); setMessageKind("SUCCESS"); setMessage("Die ausgewählten Angaben wurden geprüft und append-only bestätigt."); };
  const setCohort = async (selected:boolean) => { if(!detail)return; const {error}=await client.rpc("world_founder_set_cohort_membership_v1",{p_spot_id:detail.spotId,p_selected:selected});if(error)throw new Error(error.message);await loadSpots();setMessage(selected?"Spot zur Founder-Kohorte hinzugefügt.":"Spot aus der Kohorte entfernt; Importkatalog und Historie bleiben erhalten."); };
  const answerCount = detail ? Object.keys(detail.answers).length : 0;
  const shownSpots=spots.filter((spot)=>legacyFilter==="ALL"||legacyFilter==="IMPORTED"&&spot.catalogOrigin==="LEGACY_PRODUCTION_IMPORT"||legacyFilter==="UNCONFIRMED"&&Boolean(spot.unconfirmedLegacyCount)||legacyFilter==="AMBIGUOUS"&&Boolean(spot.ambiguousLegacyCount)||legacyFilter==="COHORT"&&spot.cohortSelected||legacyFilter==="CONFLICTS"&&spot.conflictCount>0||legacyFilter==="REVIEWED"&&spot.catalogOrigin==="LEGACY_PRODUCTION_IMPORT"&&!spot.unconfirmedLegacyCount&&!spot.ambiguousLegacyCount);
  return <div className="wk-app">
    <header className="wk-header"><div><span className="wk-eyebrow">FOUNDER TESTUMGEBUNG · NICHT ÖFFENTLICH</span><h1>{detail?.answers["identity.name"]?.value as string || detail?.fallbackName || "World Knowledge"}</h1><p>{answerCount ? `${answerCount} konkrete Angaben gespeichert` : "Beschreibe den Spot Schritt für Schritt. Alle Angaben außer dem Namen sind optional."}</p></div><div className="wk-header-actions"><span className="wk-status">● Lokal gespeichert</span><button type="button" onClick={analyze} disabled={!detail || !rebuild}>Datenvorschau aktualisieren</button></div></header>
    <div className="wk-layout"><aside className="wk-sidebar"><label className="wk-search">Spot suchen<input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Name" /></label><label className="wk-search">Kategorie<select value={category} onChange={(event) => setCategory(event.target.value)}><option value="">Alle Kategorien</option>{categoryOptions.map((option) => <option value={option.value} key={option.value}>{option.label}</option>)}</select></label>{surface === "ADMIN"&&<label className="wk-search">Importstatus<select value={legacyFilter} onChange={(event)=>setLegacyFilter(event.target.value)}><option value="ALL">Alle Spots</option><option value="IMPORTED">Alle importierten Spots</option><option value="UNCONFIRMED">Legacy-Werte prüfen</option><option value="AMBIGUOUS">Mehrdeutige Mappings</option><option value="CONFLICTS">Konflikte</option><option value="COHORT">Founder Cohort</option><option value="REVIEWED">Vollständig geprüft</option></select></label>}{surface === "ADMIN" && <button type="button" className="wk-secondary" onClick={() => setSpotId(NEW_SPOT)}>+ Spot anlegen</button>}<div className="wk-spot-list">{loading ? <p>Lädt …</p> : shownSpots.slice(0,visibleSpotCount).map((spot) => <button type="button" className={spot.spotId === spotId ? "selected" : ""} onClick={() => setSpotId(spot.spotId)} key={spot.spotId}><strong>{spot.name}</strong><span>{spot.catalogOrigin==="LEGACY_PRODUCTION_IMPORT"?"Legacy importiert · ":""}{spot.unconfirmedLegacyCount?`${spot.unconfirmedLegacyCount} zu prüfen · `:""}{spot.cohortSelected?"Cohort · ":""}{spot.answerCount} bestätigt</span></button>)}{shownSpots.length>visibleSpotCount&&<button type="button" className="wk-load-more" onClick={()=>setVisibleSpotCount((count)=>count+80)}>Weitere {Math.min(80,shownSpots.length-visibleSpotCount)} Spots anzeigen</button>}</div>{detail && <nav aria-label="Erfassungsschritte">{AUTHORING_STEPS.map((item, index) => { const state = sectionState(item); return <button type="button" className={index === step ? "selected" : ""} onClick={() => setStep(index)} key={item.id}><b>{index + 1}</b><span>{item.title}<small>{sectionLabel[state]}</small></span></button>; })}</nav>}</aside>
    <main className="wk-main">{spotId === NEW_SPOT ? <section className="wk-panel"><span className="wk-eyebrow">NEUER TESTSPOT</span><h2>Welchen Spot möchtest du beschreiben?</h2><p>Nur der Name ist zum Anlegen nötig. Der Spot bleibt archiviert und ausschließlich in diesem lokalen Testset.</p><div className="wk-inline"><input className="wk-input" autoFocus value={newName} onChange={(e) => setNewName(e.target.value)} placeholder="Name des Spots" /><button type="button" disabled={!newName.trim()} onClick={createSpot}>Spot anlegen</button></div></section> : !detail ? <section className="wk-panel"><h2>Spot auswählen</h2><p>Wähle links einen Founder-Testspot aus.</p></section> : <>
      <section className="wk-panel"><div className="wk-step-title"><span>Schritt {current.order} von {AUTHORING_STEPS.length} · {sectionLabel[sectionState(current)]}</span><h2>{current.title}</h2><p>{current.explanation}</p><p className="wk-section-guidance">Alle Angaben sind optional. „Noch unbekannt“ speichert bewusst fehlendes Wissen; Überspringen erzeugt keinen Wert.</p></div>{Object.values(fieldErrors).length > 0 && <div className="wk-error-summary" role="alert"><strong>Bitte prüfe {Object.values(fieldErrors).length === 1 ? "diese Angabe" : "diese Angaben"}:</strong><ul>{Object.entries(fieldErrors).map(([key, error]) => <li key={key}>{error}</li>)}</ul></div>}{current.id === "classification" && placeTypeConflict.state !== "COMPATIBLE" && placeTypeValue ? <div className="wk-error-summary" role="alert"><strong>Die gespeicherte oder vorgemerkte Art des Ortes passt nicht mehr zur Hauptkategorie.</strong><p>Der bisherige Wert bleibt aus Gründen der Nachvollziehbarkeit erhalten. Wähle bewusst passende Ortstypen und speichere die Auswahl.</p></div> : null}{current.id === "activities" ? <div className="wk-note"><strong>Passende Aktivitäten ergeben sich aus der Art des Ortes und konkreter Ausstattung.</strong><p>Wähle in „Einordnung“ den passenden Ortstyp. Noch nicht kanonisch freigegebene Typen bleiben sichtbar gekennzeichnet und werden nicht als World-Fakt erfunden.</p></div> : current.id === "review" ? <Review detail={detail} sectionStates={Object.fromEntries(AUTHORING_STEPS.map((item) => [item.id, sectionState(item)]))} /> : fields.length === 0 ? <div className="wk-note"><strong>Für diese Einordnung nicht relevant.</strong><p>Dieser Bereich erzeugt keine Pflichtlücke. Du kannst direkt weitergehen.</p></div> : <div className="wk-fields">{Array.from(new Set(fields.map((field) => field.group))).map((group) => <section className="wk-group" key={group}><h3>{group}</h3>{fields.filter((field) => field.group === group).map((field) => <FieldErrorBoundary label={field.label} key={field.attributeKey}><FieldInput field={field} answer={detail.answers[field.attributeKey]} candidate={detail.taxonomyCandidates?.[field.attributeKey]} disabled={!detail.actor.allowedAttributeKeys.includes(field.attributeKey)} onSave={(state, value, validUntil) => saveField(field, state, value, validUntil)} onSaveCandidate={(value) => saveTaxonomyCandidate(field, value)} onApplicability={(value) => setApplicability(field, value)} onConfirm={() => confirmAnswer(field)} onError={(error) => setFieldErrors((existing) => { const next = { ...existing }; if (error) next[field.attributeKey] = error; else delete next[field.attributeKey]; return next; })} /></FieldErrorBoundary>)}</section>)}</div>}
      <footer className="wk-footer"><button className="wk-secondary" type="button" onClick={() => setStep(Math.max(0, step - 1))} disabled={step === 0}>Zurück</button><span>Du kannst diesen Bereich jederzeit überspringen.</span>{step < AUTHORING_STEPS.length - 1 ? <button type="button" onClick={() => setStep(step + 1)}>Weiter →</button> : <button type="button" onClick={analyze}>Datenvorschau aktualisieren</button>}</footer></section>
      {surface==="ADMIN"&&legacy&&legacy.values.length>0&&<LegacyReview legacy={legacy} answers={detail.answers} selection={legacySelection} onSelection={setLegacySelection} onConfirm={() => void runAction(confirmLegacy)} onOpenField={(attributeKey) => { const target = AUTHORING_STEPS.findIndex((item) => attributeKey ? item.attributeKeys.includes(attributeKey) : false); setStep(target >= 0 ? target : 0); document.querySelector(".wk-main")?.scrollIntoView({ behavior: "smooth", block: "start" }); }} />}
      <div className="wk-tools"><button type="button" className="wk-secondary" onClick={() => void runAction(exportSpot)}>Spot exportieren</button><label className="wk-file">Importieren<input type="file" accept="application/json" onChange={(event) => { const file = event.target.files?.[0]; if (file) void runAction(() => importSpot(file), "Import fehlgeschlagen."); }} /></label>{surface === "ADMIN" && <><button type="button" className="wk-secondary" onClick={()=>void runAction(() => setCohort(!spots.find((spot)=>spot.spotId===detail.spotId)?.cohortSelected))}>{spots.find((spot)=>spot.spotId===detail.spotId)?.cohortSelected?"Aus Founder Cohort entfernen":"Zur Founder Cohort hinzufügen"}</button><button type="button" className="wk-secondary" onClick={() => void runAction(setLifecycle)}>{detail.lifecycleStatus === "ACTIVE" ? "Aus Testset archivieren" : "Testspot reaktivieren"}</button><button type="button" className="wk-danger" onClick={() => void runAction(resetTestset)}>Lokales Testset zurücksetzen</button></>}</div>
      <button type="button" className="wk-expert-toggle" onClick={() => setExpert(!expert)}>Erweiterte Angaben und Quellen {expert ? "schließen" : "öffnen"}</button>{expert && <section className="wk-panel wk-expert"><h2>Technische Nachvollziehbarkeit</h2><p>Nur für Admins und die technische Prüfung. Diese Informationen beeinflussen Trust nicht automatisch.</p><pre>{JSON.stringify(detail, null, 2)}</pre></section>}
    </>}</main></div>{message && <div className={`wk-toast ${messageKind === "ERROR" ? "error" : messageKind === "SUCCESS" ? "success" : ""}`} role={messageKind === "ERROR" ? "alert" : "status"}>{message}{messageKind === "ERROR" && <button type="button" aria-label="Fehlermeldung schließen" onClick={() => setMessage("")}>×</button>}</div>}{surface === "ADMIN" && exportCohort && <button className="wk-cohort" type="button" onClick={() => void runAction(exportCohort)}>Founder World Cohort exportieren</button>}</div>;
}

function Review({ detail, sectionStates }: { detail: SpotDetail; sectionStates: Record<string, AuthoringSectionState> }) {
  const answers = Object.entries(detail.answers); const unknown = answers.filter(([, answer]) => answer.knowledgeState === "UNKNOWN"); const excluded = answers.filter(([, answer]) => answer.visibility !== "PUBLIC");
  const blocking = Object.values(sectionStates).filter((state) => state === "ERROR").length + detail.reviewItems.filter((item) => item.priority === "HIGH" || item.priority === "CRITICAL").length;
  const gaps = Object.values(sectionStates).filter((state) => state === "NOT_VIEWED" || state === "STARTED").length;
  const intentional = Object.values(sectionStates).filter((state) => state === "INTENTIONALLY_INCOMPLETE").length;
  return <div className="wk-review"><article><b>Das weiß Backyrd</b><strong>{answers.length}</strong><span>ausdrücklich gespeicherte Angaben</span></article><article><b>Bewusst unbekannt</b><strong>{unknown.length}</strong><span>nicht mit Nein verwechselt</span></article><article><b>Blockierende Fehler</b><strong>{blocking}</strong><span>vor Evaluation korrigieren</span></article><article><b>Bekannte Datenlücken</b><strong>{gaps}</strong><span>begonnene oder offene Bereiche</span></article><article><b>Bewusst offen</b><strong>{intentional}</strong><span>unbekannt oder nicht relevant</span></article><article><b>Nicht freigegeben</b><strong>{excluded.length}</strong><span>nicht in der öffentlichen Projektion</span></article><section className={`wk-readiness ${blocking ? "blocked" : "ready"}`}><h3>{blocking ? "Noch nicht für Evaluation bereit" : "Für die lokale Evaluation ausreichend"}</h3><p>{blocking ? "Behebe zuerst die angezeigten Fehler und Konflikte. Bereits gespeicherte Angaben bleiben erhalten." : gaps ? "Der Spot kann getestet werden; die genannten Datenlücken bleiben in der Auswertung sichtbar." : "Alle relevanten Bereiche wurden geprüft. Das ist keine globale Vollständigkeits- oder Qualitätsbewertung."}</p></section><section className="wk-preview"><span className="wk-eyebrow">MOBILE DATENVORSCHAU · KEIN FINALES DESIGN</span><h2>{String(detail.answers["identity.name"]?.value ?? detail.fallbackName)}</h2><p>{String(detail.answers["description.highlight"]?.value ?? "Noch keine öffentliche Beschreibung.")}</p><div className="wk-preview-grid"><div><small>Was für ein Ort?</small><b>{humanValue("classification.place_types", detail.answers["classification.place_types"]?.value) || "Noch offen"}</b></div><div><small>Angebot</small><b>{humanValue("offering.groups", detail.answers["offering.groups"]?.value) || "Noch offen"}</b></div><div><small>Preislevel</small><b>{humanValue("operation.price_level", detail.answers["operation.price_level"]?.value) || "Noch offen"}</b></div></div></section>{detail.manifest ? <div className="wk-note"><strong>Bereinigter Snapshot vorhanden</strong><p>Eine technisch geprüfte lokale Datenvorschau liegt vor. Private Kontakte, Abo, Payment und Actor-IDs sind ausgeschlossen. Hashes sind nur in der Expertensicht sichtbar.</p></div> : <div className="wk-note"><strong>Noch keine Datenvorschau</strong><p>Starte den lokalen Shadow-Rebuild, um den aufgelösten Wissensstand zu prüfen.</p></div>}</div>;
}
