"use client";

import Link from "next/link";
import Image from "next/image";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabaseClient";
import { dateTime, number } from "@/lib/intelligence";
import { type CockpitDetail, type NodeView, label, nodeView, profileLabel, promotionView, textAt } from "@/lib/userIntelligenceCockpit";

const REFRESH_MS=12_000;
export default function UserIntelligenceDetail(){
 const id=useParams<{id:string}>()?.id;const[data,setData]=useState<CockpitDetail|null>(null);const[error,setError]=useState("");const[loading,setLoading]=useState(true);const[tab,setTab]=useState<"decisions"|"evidence"|"changes"|"system">("decisions");
 const load=useCallback(async()=>{if(!id)return;const{data,error}=await supabase.rpc("backyrd_admin_user_intelligence_cockpit_detail_v1",{p_user_id:id,p_limit:300});if(error)setError(error.message);else{setData(data as CockpitDetail);setError("")}setLoading(false)},[id]);
 useEffect(()=>{const kickoff=window.setTimeout(()=>void load(),0);const timer=window.setInterval(()=>void load(),REFRESH_MS);return()=>{window.clearTimeout(kickoff);window.clearInterval(timer)}},[load]);
 const nodes=useMemo(()=>(data?.profile.nodes??[]).map(nodeView).sort((a,b)=>Math.abs(b.affinity*b.confidence)-Math.abs(a.affinity*a.confidence)),[data]);
 if(loading)return <div className="bi-page"><div className="bi-state">User Intelligence wird rekonstruiert …</div></div>;
 if(error||!data)return <div className="bi-page"><Link className="bi-back" href="/user-intelligence">← Cockpit</Link><div className="bi-error">{error||"Profil nicht gefunden"}</div></div>;
 const user=data.user;const consent=String(data.consent.status??"missing");
 return <div className="bi-page ui-cockpit"><div className="ui-detailNav"><Link href="/user-intelligence">← Alle Profile</Link><div className="ui-live compact"><i/><span>Live · {dateTime(data.generatedAt)}</span><button onClick={()=>void load()}>↻</button></div></div>
  <header className="ui-profileHero"><div className="ui-profileIdentity">{user.avatar_url?<Image src={user.avatar_url} alt="" width={64} height={64} unoptimized/>:<div className="ui-avatar large">{(user.display_name||user.username||user.email||"B").slice(0,1).toUpperCase()}</div>}<div><div className="bi-eyebrow">User Intelligence · {profileLabel(data.profile.state)}</div><h1>{user.display_name||user.username||user.email||"Backyrd User"}</h1><p>{user.email||user.user_id} · {user.city||"Ort unbekannt"}</p></div></div><div className="ui-profileMeta"><span className={`ui-consent ${consent}`}>{consent==="granted"?"Consent aktiv":"Keine Profilverarbeitung"}</span><small>Registriert {dateTime(user.registered_at)}</small><small>Runtime {String(data.profile.snapshot?.runtimeVersion??"noch keine")}</small></div></header>
  <IntelligencePortrait nodes={nodes} profileState={data.profile.state}/>
  <section className="ui-kpis detail"><Metric label="Taste-Knoten" value={data.profile.metrics.node_count}/><Metric label="Belastbar" value={data.profile.metrics.established_count}/><Metric label="Hypothesen" value={data.profile.metrics.hypothesis_count}/><Metric label="Widersprüche" value={data.profile.metrics.contradiction_count}/><Metric label="Decisions" value={data.totals.decisions_total}/><Metric label="Profiländerungen" value={data.totals.changes_total}/></section>
  <TasteSummary nodes={nodes}/>
  <section className="ui-profileGrid"><article className="ui-panel ui-taste"><div className="ui-sectionHead"><div><span className="bi-kicker">Aktuelles Modell</span><h2>Taste Map</h2></div><span>{nodes.length} kanonische Signale</span></div>{nodes.length===0?<Empty text="Noch keine Taste-Knoten. UNKNOWN bleibt UNKNOWN."/>:<div className="ui-tasteGrid">{nodes.map(node=>{const promotion=promotionView(node);return <div className="ui-tasteNode" key={`${node.concept}-${node.state}`}><header><strong>{label(node.concept)}</strong><em className={node.affinity<0?"negative":node.affinity>0?"positive":"neutral"}>{label(node.state)}</em></header><div className="ui-affinity"><span style={{left:`${Math.max(0,Math.min(100,(node.affinity+1)*50))}%`}}/><i/></div><dl><div><dt>Affinität</dt><dd>{node.affinity.toFixed(2)}</dd></div><div><dt>Confidence</dt><dd>{Math.round(node.confidence*100)}%</dd></div><div><dt>Positiv / Negativ</dt><dd>{node.positive.toFixed(2)} / {node.negative.toFixed(2)}</dd></div><div><dt>Unabhängig</dt><dd>{node.sessions} Sessions · {node.spots} Spots</dd></div></dl><div className="ui-promotion"><div><strong>{promotion.title}</strong><span>{Math.round(promotion.progress*100)} %</span></div><i><b style={{width:`${promotion.progress*100}%`}}/></i><p>{promotion.detail}</p></div></div>})}</div>}</article>
   <aside className="ui-panel ui-gaps"><div className="ui-sectionHead"><div><span className="bi-kicker">Messbare Lücken</span><h2>Was fehlt noch?</h2></div></div>{Object.keys(data.gaps).length===0?<div className="ui-good">✓ Keine strukturelle Profillücke erkannt.</div>:Object.entries(data.gaps).map(([key,value])=><div className="ui-gap" key={key}><span>!</span><div><strong>{label(key)}</strong><p>{value}</p></div></div>)}<div className="ui-snapshotMeta"><span>Snapshot</span><code>{String(data.profile.snapshot?.snapshotId??"noch keiner")}</code><span>Watermark</span><code>{dateTime(String(data.profile.snapshot?.sourceWatermark??""))}</code></div></aside>
  </section>
  <nav className="ui-tabs">{([['decisions','Decisions'],['evidence','Evidenzstrom'],['changes','Profilaufbau'],['system','Pipeline & Rohsicht']] as const).map(([key,name])=><button className={tab===key?"active":""} onClick={()=>setTab(key)} key={key}>{name}</button>)}</nav>
  {tab==="decisions"&&<section className="ui-panel"><div className="ui-sectionHead"><div><span className="bi-kicker">Decision → Learning</span><h2>Entscheidungsverlauf</h2></div><span>{data.decisions.length} angezeigt</span></div><div className="ui-decisionList">{data.decisions.length===0?<Empty text="Noch keine Decisions aufgezeichnet."/>:data.decisions.map(decision=>{const understood=textAt(decision.current_intent,["intent"],["primaryIntent"],["category"],["purpose"])??"Absicht nicht strukturiert";return <article className="ui-decision" key={decision.id}><div className="ui-decisionTime"><strong>{dateTime(decision.created_at)}</strong><span>{decision.city}</span></div><div className="ui-decisionBody"><h3>{understood}</h3><p>{decision.completed_at?"Vollständig ausgewertet":"Nicht vollständig abgeschlossen"}</p><div className="ui-impact"><span>{decision.learning_event_count} Learning-Events</span><span>{decision.memory_event_count} Memory-Events</span><span className={decision.directly_attributed_changes?"changed":"neutral"}>{decision.directly_attributed_changes?`${decision.directly_attributed_changes} direkt belegte Profiländerungen`:"Keine direkt zuordenbare Profiländerung"}</span></div></div><details><summary>Funnel ansehen</summary><pre>{JSON.stringify({intent:decision.current_intent,retrieval:decision.retrieval_funnel,result:decision.final_disposition},null,2)}</pre></details></article>})}</div></section>}
  {tab==="evidence"&&<section className="ui-panel"><div className="ui-sectionHead"><div><span className="bi-kicker">Consentgebundene Wahrheit</span><h2>Evidenzstrom</h2></div><span>{data.totals.memory_total} gesamt</span></div><div className="ui-stream">{data.memory.map(event=><div className="ui-streamRow" key={event.id}><i/><div><strong>{label(event.event_type)}</strong><span>{event.spot_name||label(event.evidence_family)} · {dateTime(event.occurred_at)}</span></div><div><em>{label(event.event_class)}</em><small>bis {dateTime(event.expires_at)}</small></div></div>)}{data.memory.length===0&&<Empty text="Keine consentgebundene Evidenz vorhanden."/>}</div></section>}
  {tab==="changes"&&<section className="ui-panel"><div className="ui-sectionHead"><div><span className="bi-kicker">Append-only Change Ledger</span><h2>Wie das Profil entstand</h2></div><span>{data.totals.changes_total} Änderungen</span></div><div className="ui-changeList">{data.changes.map(change=>{const next=nodeView({nodeKey:change.node_key,node:change.next_node});const before=change.previous_node?nodeView({nodeKey:change.node_key,node:change.previous_node}):null;return <article className="ui-change" key={change.id}><div className="ui-changeLine"><i/><span/></div><div><header><strong>{label(next.concept)}</strong><time>{dateTime(change.occurred_at)}</time></header><p>{before?`${label(before.state)} (${Math.round(before.confidence*100)}%) → `:"Neu → "}<b>{label(next.state)} ({Math.round(next.confidence*100)}%)</b></p><small>{label(change.reason_code)} · {change.triggering_chain_ids.length?`${change.triggering_chain_ids.length} direkt gebundene Quellen`:"Keine direkte Decision-Zuordnung im Ledger"}</small></div></article>})}{data.changes.length===0&&<Empty text="Noch keine Profiländerung im Ledger."/>}</div></section>}
  {tab==="system"&&<section className="ui-systemGrid"><article className="ui-panel"><div className="ui-sectionHead"><div><span className="bi-kicker">Verarbeitung</span><h2>Pipeline</h2></div></div>{data.work.length===0?<Empty text="Keine offenen oder historischen Work-Items."/>:data.work.map(item=><div className="ui-pipeline" key={item.state}><span className={item.state.toLowerCase()}>{label(item.state)}</span><strong>{number(item.count)}</strong><small>zuletzt {dateTime(item.latest)}</small></div>)}</article><article className="ui-panel"><div className="ui-sectionHead"><div><span className="bi-kicker">Product v1</span><h2>Learning-Records</h2></div><span>{data.totals.learning_total}</span></div>{data.learning.slice(0,25).map(item=><div className="ui-learning" key={item.id}><strong>{label(item.event_type)}</strong><span>{item.spot_name||item.decision_id||"Decision-bezogen"}</span><small>{label(item.semantic_disposition||"UNKNOWN")} · {dateTime(item.occurred_at)}</small></div>)}{data.learning.length===0&&<Empty text="Keine Product-v1-Learning-Records."/>}</article><article className="ui-panel ui-raw"><div className="ui-sectionHead"><div><span className="bi-kicker">Prüfbare Quelle</span><h2>Kanonischer Snapshot</h2></div></div><details><summary>Minimierten Snapshot öffnen</summary><pre>{JSON.stringify(data.profile.snapshot,null,2)}</pre></details><p>Keine Tokens, Service-Credentials oder rohen Decision-Texte werden an das Dashboard geliefert.</p></article></section>}
 </div>;
}
function IntelligencePortrait({nodes,profileState}:{nodes:NodeView[];profileState:CockpitDetail["profile"]["state"]}){
 const robust=nodes.filter(node=>["POSITIVE","NEGATIVE"].includes(node.state)).length;
 const hypotheses=nodes.filter(node=>node.state.startsWith("HYPOTHESIS")).length;
 const conflicts=nodes.filter(node=>node.state==="MIXED"||node.contradictions>0).length;
 return <section className="ui-intelligencePortrait" aria-label="Lebendiges Modell des Nutzerprofils"><div className="ui-human" aria-hidden="true"><div className="ui-orbit one"><i/><i/><i/></div><div className="ui-orbit two"><i/><i/></div><div className="ui-head"><span/><b/><em/></div><div className="ui-shoulders"/></div><div className="ui-intelligenceCopy"><span className="bi-kicker">Lebendes Nutzerbild</span><h2>So versteht Backyrd diesen Menschen gerade</h2><p>Das Modell ist <strong>{profileLabel(profileState).toLowerCase()}</strong>. Es trennt Vermutungen sichtbar von belastbaren Präferenzen und behält Widersprüche, statt sie glattzubügeln.</p><div><span><b>{robust}</b> belastbar</span><span><b>{hypotheses}</b> Hypothesen</span><span><b>{conflicts}</b> Konflikte</span></div></div></section>;
}
function TasteSummary({nodes}:{nodes:NodeView[]}){
 const hypotheses=nodes.filter(node=>node.state.startsWith("HYPOTHESIS")).slice(0,5);
 const robust=nodes.filter(node=>["POSITIVE","NEGATIVE"].includes(node.state)).slice(0,5);
 const conflicts=nodes.filter(node=>node.state==="MIXED"||node.contradictions>0).slice(0,5);
 return <section className="ui-summaryGrid"><SummaryCard title="Aktuelle Hypothesen" kicker="Noch in Prüfung" nodes={hypotheses} empty="Noch keine gerichteten Hypothesen."/><SummaryCard title="Belastbare Präferenzen" kicker="Für Ranking freigegeben" nodes={robust} empty="Noch keine Präferenz erfüllt alle Evidenzkriterien."/><SummaryCard title="Konflikte" kicker="Bewusst sichtbar" nodes={conflicts} empty="Keine widersprüchlichen Signale erkannt."/></section>;
}
function SummaryCard({title,kicker,nodes,empty}:{title:string;kicker:string;nodes:NodeView[];empty:string}){
 return <article className="ui-summaryCard"><span>{kicker}</span><h3>{title}</h3>{nodes.length?<ul>{nodes.map(node=><li key={`${title}-${node.concept}-${node.scopeKind}`}><b>{label(node.concept)}</b><small>{node.affinity<-.1?"eher gemieden":node.affinity>.1?"eher bevorzugt":"Richtung offen"} · {Math.round(node.confidence*100)} % Confidence</small></li>)}</ul>:<p>{empty}</p>}</article>;
}
function Metric({label:caption,value}:{label:string;value:number}){return <div className="ui-metric"><span>{caption}</span><strong>{number(value)}</strong></div>}
function Empty({text}:{text:string}){return <div className="ui-empty">{text}</div>}
