import assert from "node:assert/strict";
import test from "node:test";
import {
  ATTRIBUTE_DEFINITIONS, CHANGE_CLASSES, FOUNDATION_REGISTRY_SHAPE, LEGACY_ADAPTER_VERSION, PRIMARY_CATEGORY_LABELS, REGISTRY_HASH, REGISTRY_VERSION, RESOLUTION_CONTRACT_VERSION, UNCONFIGURED_SOURCE_POLICY, WORLD_KNOWLEDGE_PORT_VERSION,
  adaptLegacySpot, buildWorldKnowledgeSnapshot, createClaim, createRegistryApprovalAuthority, createRegistryApprovalRecord, createRegistryRelease, createSourcePolicy, createVerificationExecutionAuthority, createVerificationProcessContract, createVerificationRecord,
  evaluateClaimSource, hashBody, parseBuildWorldKnowledgeInput, parseResolutionResult, parseVerificationRecord, profileLegacySpots, projectForDecision, resolveWorldKnowledge, sha256, sourceReadiness, validateRegistryTransition,
} from "../dist/index.js";

const approvalAuthority = createRegistryApprovalAuthority({authorityId:"authority:test-cto",allowedRoles:["PRODUCT_CTO"],allowedChangeClasses:CHANGE_CLASSES,semanticEquivalenceApproval:true,validFrom:"2026-09-10T00:00:00.000Z",validUntil:"2028-01-01T00:00:00.000Z"});
const shape = (version, definitions, labels=PRIMARY_CATEGORY_LABELS) => ({version,definitions,categoryLabels:labels,hash:sha256({version,definitions,categoryLabels:labels})});
const approvalRecords=[];
const release = (changeClass, previous, next, extras={}) => { const approval=createRegistryApprovalRecord({recordId:`approval:test:${approvalRecords.length+1}`,authorityId:approvalAuthority.authorityId,authorityHash:approvalAuthority.authorityHash,role:"PRODUCT_CTO",registryVersion:next.version,registryHash:next.hash,changeClass,approvedAt:"2026-09-10T12:00:00.000Z"},approvalAuthority); approvalRecords.push(approval); return createRegistryRelease({registryVersion:next.version,registryHash:next.hash,predecessorVersion:previous.version,changeClass,createdAt:"2026-09-10T12:00:00.000Z",approval:{recordId:approval.recordId,approvalHash:approval.approvalHash,role:approval.role,approvedAt:approval.approvedAt,authorityId:approval.authorityId,authorityHash:approval.authorityHash},changeSummary:["synthetic transition"],compatibilityStatus:"BACKWARD_COMPATIBLE",deprecations:[],aliases:[],...extras}); };
const governanceContext = (history=[]) => ({acceptedApprovalAuthorities:[approvalAuthority],acceptedApprovalRecords:[...approvalRecords],history});

test("registry governance validates previous content, authority and forward versions",()=>{
  const base=FOUNDATION_REGISTRY_SHAPE; const labels=structuredClone(PRIMARY_CATEGORY_LABELS); labels.EAT.de="Gastronomie"; const labelNext=shape("backyrd.world-knowledge.registry@1.1",ATTRIBUTE_DEFINITIONS,labels); assert.doesNotThrow(()=>validateRegistryTransition(base,labelNext,release("LABEL_ONLY",base,labelNext),governanceContext()));
  const extra={...ATTRIBUTE_DEFINITIONS[0],key:"identity.legal_name",labels:{de:"Rechtlicher Name",en:"Legal name"}}; const additive=shape("backyrd.world-knowledge.registry@1.1",[...ATTRIBUTE_DEFINITIONS,extra]); assert.doesNotThrow(()=>validateRegistryTransition(base,additive,release("ADDITIVE_DEFINITION",base,additive),governanceContext()));
  const manipulated={...base,definitions:base.definitions.map((item,index)=>index?item:{...item,max:999})}; assert.throws(()=>validateRegistryTransition(manipulated,labelNext,release("LABEL_ONLY",base,labelNext),governanceContext()),/content hash/);
  const unaccepted=createRegistryApprovalAuthority({authorityId:"authority:self-claimed",allowedRoles:["PRODUCT_CTO"],allowedChangeClasses:CHANGE_CLASSES,semanticEquivalenceApproval:true,validFrom:"2026-09-10T00:00:00.000Z",validUntil:"2028-01-01T00:00:00.000Z"}); const unacceptedRecord=createRegistryApprovalRecord({recordId:"approval:self",authorityId:unaccepted.authorityId,authorityHash:unaccepted.authorityHash,role:"PRODUCT_CTO",registryVersion:labelNext.version,registryHash:labelNext.hash,changeClass:"LABEL_ONLY",approvedAt:"2026-09-10T12:00:00.000Z"},unaccepted); const selfApproved=createRegistryRelease({registryVersion:labelNext.version,registryHash:labelNext.hash,predecessorVersion:base.version,changeClass:"LABEL_ONLY",createdAt:"2026-09-10T12:00:00.000Z",approval:{recordId:unacceptedRecord.recordId,approvalHash:unacceptedRecord.approvalHash,role:unacceptedRecord.role,approvedAt:unacceptedRecord.approvedAt,authorityId:unaccepted.authorityId,authorityHash:unaccepted.authorityHash},changeSummary:["self claimed"],compatibilityStatus:"BACKWARD_COMPATIBLE",deprecations:[],aliases:[]}); assert.throws(()=>validateRegistryTransition(base,labelNext,selfApproved,governanceContext()),/not accepted/);
  const inventedRecord=createRegistryApprovalRecord({recordId:"approval:invented",authorityId:approvalAuthority.authorityId,authorityHash:approvalAuthority.authorityHash,role:"PRODUCT_CTO",registryVersion:labelNext.version,registryHash:labelNext.hash,changeClass:"LABEL_ONLY",approvedAt:"2026-09-10T12:00:00.000Z"},approvalAuthority); const inventedRelease=createRegistryRelease({registryVersion:labelNext.version,registryHash:labelNext.hash,predecessorVersion:base.version,changeClass:"LABEL_ONLY",createdAt:"2026-09-10T12:00:00.000Z",approval:{recordId:inventedRecord.recordId,approvalHash:inventedRecord.approvalHash,role:inventedRecord.role,approvedAt:inventedRecord.approvedAt,authorityId:inventedRecord.authorityId,authorityHash:inventedRecord.authorityHash},changeSummary:["invented record"],compatibilityStatus:"BACKWARD_COMPATIBLE",deprecations:[],aliases:[]}); assert.throws(()=>validateRegistryTransition(base,labelNext,inventedRelease,governanceContext()),/approval record was not accepted/);
  assert.throws(()=>validateRegistryTransition(labelNext,base,release("LABEL_ONLY",labelNext,base),governanceContext()),/move forward/);
});

test("removal requires deprecation in an earlier retained registry artifact",()=>{
  const base=FOUNDATION_REGISTRY_SHAPE; const key=ATTRIBUTE_DEFINITIONS[0].key; const deprecated=shape("backyrd.world-knowledge.registry@1.1",ATTRIBUTE_DEFINITIONS); const deprecation=release("DEPRECATION",base,deprecated,{deprecations:[{key,replacementKey:null,removalNotBeforeVersion:"backyrd.world-knowledge.registry@2.0",compatibilityPlan:"Adapter retains historical values."}]}); validateRegistryTransition(base,deprecated,deprecation,governanceContext());
  const removed=shape("backyrd.world-knowledge.registry@2.0",ATTRIBUTE_DEFINITIONS.slice(1)); const removal=release("REMOVAL",deprecated,removed); assert.throws(()=>validateRegistryTransition(deprecated,removed,removal,governanceContext()),/earlier registry/); assert.doesNotThrow(()=>validateRegistryTransition(deprecated,removed,removal,governanceContext([{shape:deprecated,release:deprecation}])));
  const sameRelease=release("REMOVAL",deprecated,removed,{deprecations:[{key,replacementKey:null,removalNotBeforeVersion:"backyrd.world-knowledge.registry@2.0",compatibilityPlan:"same release"}]}); assert.throws(()=>validateRegistryTransition(deprecated,removed,sameRelease,governanceContext()),/earlier registry/);
});

test("alias graphs reject dangling, conflicting, cyclic and false equivalence",()=>{
  const base=FOUNDATION_REGISTRY_SHAPE; const old=ATTRIBUTE_DEFINITIONS[0]; const equivalent={...old,key:"identity.display_name",labels:{de:"Anzeigename",en:"Display name"}}; const target=shape("backyrd.world-knowledge.registry@2.0",[...ATTRIBUTE_DEFINITIONS.slice(1),equivalent]);
  const valid=release("KEY_REPLACEMENT",base,target,{aliases:[{fromKey:old.key,toKey:equivalent.key,relation:"SEMANTICALLY_EQUIVALENT"}]}); assert.doesNotThrow(()=>validateRegistryTransition(base,target,valid,governanceContext()));
  assert.throws(()=>validateRegistryTransition(base,target,release("KEY_REPLACEMENT",base,target,{aliases:[{fromKey:old.key,toKey:"missing.target",relation:"NAVIGATION_ONLY"}]}),governanceContext()),/target does not exist/);
  const second={...equivalent,key:"identity.alternate_name"}; const twoTargets=shape("backyrd.world-knowledge.registry@2.0",[...ATTRIBUTE_DEFINITIONS.slice(1),equivalent,second]); assert.throws(()=>validateRegistryTransition(base,twoTargets,release("KEY_REPLACEMENT",base,twoTargets,{aliases:[{fromKey:old.key,toKey:equivalent.key,relation:"NAVIGATION_ONLY"},{fromKey:old.key,toKey:second.key,relation:"NAVIGATION_ONLY"}]}),governanceContext()),/conflicting targets/);
  const cyclicShape=shape("backyrd.world-knowledge.registry@1.1",ATTRIBUTE_DEFINITIONS); assert.throws(()=>validateRegistryTransition(base,cyclicShape,release("DEPRECATION",base,cyclicShape,{aliases:[{fromKey:"identity.name",toKey:"location.locality",relation:"NAVIGATION_ONLY"},{fromKey:"location.locality",toKey:"identity.name",relation:"NAVIGATION_ONLY"}],deprecations:[{key:"identity.name",replacementKey:"location.locality",removalNotBeforeVersion:"backyrd.world-knowledge.registry@2.0",compatibilityPlan:"test"},{key:"location.locality",replacementKey:"identity.name",removalNotBeforeVersion:"backyrd.world-knowledge.registry@2.0",compatibilityPlan:"test"}]}),governanceContext()),/cycle/);
  const inequivalent={...equivalent,valueType:"BOOLEAN"}; const badTarget=shape("backyrd.world-knowledge.registry@2.0",[...ATTRIBUTE_DEFINITIONS.slice(1),inequivalent]); assert.throws(()=>validateRegistryTransition(base,badTarget,release("KEY_REPLACEMENT",base,badTarget,{aliases:[{fromKey:old.key,toKey:inequivalent.key,relation:"SEMANTICALLY_EQUIVALENT"}]}),governanceContext()),/not semantically equivalent/);
});

const useCases=(allowed=[])=>Object.fromEntries(["GENERAL_WORLD","DISCOVERY","OPENING_HOURS_ELIGIBILITY","PRICE","HARD_CONSTRAINTS","ACCESSIBILITY","INTENT_MATCHING","EXPLANATION","RESEARCH"].map((key)=>[key,allowed.includes(key)?"ALLOWED":"PROHIBITED"]));
const minimumTrust=(values={})=>Object.fromEntries(["GENERAL_WORLD","DISCOVERY","OPENING_HOURS_ELIGIBILITY","PRICE","HARD_CONSTRAINTS","ACCESSIBILITY","INTENT_MATCHING","EXPLANATION","RESEARCH"].map((key)=>[key,values[key]??null]));
const configuredPolicy=(configs)=>createSourcePolicy({policyVersion:"policy:synthetic:closure:1",registryVersion:REGISTRY_VERSION,registryHash:REGISTRY_HASH,createdAt:"2026-09-10T12:00:00.000Z",entries:UNCONFIGURED_SOURCE_POLICY.entries.map((entry)=>{const config=configs[entry.attributeKey];return config?{...entry,state:"CONFIGURED",allowedSourceTypes:config.sources??["OFFICIAL_SOURCE"],allowedActorTypes:config.actors??["ADMIN"],sourceReference:config.reference??"REQUIRED",selfAssertionAllowed:config.selfAssertion??false,verificationProcess:{requirement:config.process?"PROCESS_REQUIRED":"NONE",allowedProcessIds:config.process?[config.process]:[]},freshness:{policyRef:config.freshnessRef??`freshness:${entry.attributeKey}`,mode:config.freshness??"PERMANENT_UNTIL_CONTRADICTED"},useCases:useCases(config.useCases??["GENERAL_WORLD"]),minimumTrustByUseCase:minimumTrust(Object.fromEntries((config.useCases??["GENERAL_WORLD"]).map((key)=>[key,config.minimumTrust??"REFERENCED"])))}:entry;})});
const claim=(overrides={})=>createClaim({claimId:"claim:source",attributeKey:"operation.takeaway",scope:{spotId:"spot:source",area:"SPOT"},knowledgeState:"KNOWN_TRUE",value:true,actorType:"ADMIN",sourceType:"OFFICIAL_SOURCE",sourceReferenceId:"source:official",provenanceSessionId:"session:test",verificationState:"UNVERIFIED",observedAt:"2026-09-10T12:00:00.000Z",validFrom:null,validUntil:null,stance:"SUPPORTS",visibility:"INTERNAL",supersedesClaimId:null,...overrides});

test("source policy enforces source, actor, reference and self-assertion boundaries",()=>{
  const policy=configuredPolicy({"operation.takeaway":{useCases:["GENERAL_WORLD","HARD_CONSTRAINTS"]}}); assert.equal(evaluateClaimSource(claim(),policy).status,"AUTHORIZED");
  assert.equal(evaluateClaimSource(claim({sourceType:"PUBLIC_SOURCE"}),policy).status,"REJECTED"); assert.equal(evaluateClaimSource(claim({actorType:"VERIFIED_OWNER"}),policy).status,"REJECTED"); assert.equal(evaluateClaimSource(claim({sourceReferenceId:null}),policy).status,"REJECTED");
  const forbidden=configuredPolicy({"operation.takeaway":{reference:"FORBIDDEN",useCases:["GENERAL_WORLD"]}}); assert.equal(evaluateClaimSource(claim(),forbidden).status,"REJECTED");
  const noSelf=configuredPolicy({"operation.takeaway":{sources:["OWNER_ASSERTION"],actors:["VERIFIED_OWNER"],reference:"OPTIONAL",selfAssertion:false,useCases:["GENERAL_WORLD"],minimumTrust:"ASSERTED"}}); assert.equal(evaluateClaimSource(claim({actorType:"VERIFIED_OWNER",sourceType:"OWNER_ASSERTION",sourceReferenceId:null}),noSelf).status,"REJECTED");
  const forgedEntries=UNCONFIGURED_SOURCE_POLICY.entries.map((entry)=>entry.attributeKey==="operation.takeaway"?{...entry,useCases:{...entry.useCases,HARD_CONSTRAINTS:"ALLOWED"},minimumTrustByUseCase:{...entry.minimumTrustByUseCase,HARD_CONSTRAINTS:"ASSERTED"}}:entry); assert.throws(()=>createSourcePolicy({policyVersion:"policy:forged",registryVersion:REGISTRY_VERSION,registryHash:REGISTRY_HASH,createdAt:"2026-09-10T12:00:00.000Z",entries:forgedEntries}),/unconfigured policy/);
});

test("resolution binds assessments and readiness follows concrete claims",()=>{
  const hoursPolicy=configuredPolicy({"hours.regular":{freshness:"SCHEDULE_BOUND",useCases:["GENERAL_WORLD","OPENING_HOURS_ELIGIBILITY"]}}); const hours=claim({claimId:"claim:hours",attributeKey:"hours.regular",knowledgeState:"KNOWN_VALUE",value:[{day:"MONDAY",intervals:[{start:"10:00",end:"22:00"}]}]});
  const result=resolveWorldKnowledge({contractVersion:RESOLUTION_CONTRACT_VERSION,registryVersion:REGISTRY_VERSION,asOf:"2026-09-10T12:00:00.000Z",claims:[hours],sourcePolicy:hoursPolicy,verificationRecords:[]},[hoursPolicy]); assert.equal(result.sourceAssessments[0].useCaseAuthorizations.OPENING_HOURS_ELIGIBILITY,"AUTHORIZED"); assert.equal(sourceReadiness([hours],"OPENING_HOURS_ELIGIBILITY",hoursPolicy).status,"READY");
  const snapshot=buildWorldKnowledgeSnapshot(parseBuildWorldKnowledgeInput({contractVersion:WORLD_KNOWLEDGE_PORT_VERSION,spotId:"spot:source",resolution:result},[hoursPolicy]),[hoursPolicy]); assert.equal(snapshot.readiness.find((row)=>row.useCase==="OPENING_HOURS_ELIGIBILITY").state,"READY"); assert.ok(!snapshot.readiness.find((row)=>row.useCase==="OPENING_HOURS_ELIGIBILITY").reasonCodes.includes("SOURCE_POLICY_NOT_CONFIGURED"));
  const inadequate=claim({claimId:"claim:bad-hours",attributeKey:"hours.regular",knowledgeState:"KNOWN_VALUE",value:[{day:"MONDAY",intervals:[{start:"10:00",end:"22:00"}]}],sourceType:"OWNER_ASSERTION",actorType:"VERIFIED_OWNER",sourceReferenceId:"source:owner"}); const rejected=resolveWorldKnowledge({contractVersion:RESOLUTION_CONTRACT_VERSION,registryVersion:REGISTRY_VERSION,asOf:"2026-09-10T12:00:00.000Z",claims:[inadequate],sourcePolicy:hoursPolicy,verificationRecords:[]},[hoursPolicy]); assert.equal(rejected.resolved.length,0); assert.equal(rejected.sourceAssessments[0].status,"REJECTED");
  const forged=structuredClone(result); forged.sourceAssessments[0].status="AUTHORIZED"; forged.sourceAssessments[0].trust="VERIFIED"; const {assessmentHash:_old,...assessmentBody}=forged.sourceAssessments[0]; forged.sourceAssessments[0].assessmentHash=hashBody(assessmentBody,[]); const {resultHash:_result,...resultBody}=forged; forged.resultHash=hashBody(resultBody,[]); assert.throws(()=>parseResolutionResult(forged,[hoursPolicy]),/deterministic policy evaluation/);
  const restrictivePolicy=configuredPolicy({"hours.regular":{sources:["OWNER_ASSERTION"],actors:["VERIFIED_OWNER"],reference:"OPTIONAL",selfAssertion:true,freshness:"SCHEDULE_BOUND",useCases:["GENERAL_WORLD","OPENING_HOURS_ELIGIBILITY"],minimumTrust:"ASSERTED"}}); const rehashed=structuredClone(result); rehashed.sourcePolicy=restrictivePolicy; rehashed.sourceAssessments=[evaluateClaimSource(hours,restrictivePolicy)]; rehashed.resolved=rehashed.resolved.map((item)=>{const body={...item,sourceAssessmentHashes:[rehashed.sourceAssessments[0].assessmentHash]}; delete body.resolutionHash; return {...body,resolutionHash:hashBody(body,[])};}); const {resultHash:_rehashedResult,...rehashedBody}=rehashed; rehashed.resultHash=hashBody(rehashedBody,[]); assert.throws(()=>parseResolutionResult(rehashed,[restrictivePolicy]),/deterministic resolution/);

  const mixed=resolveWorldKnowledge({contractVersion:RESOLUTION_CONTRACT_VERSION,registryVersion:REGISTRY_VERSION,asOf:"2026-09-10T12:00:00.000Z",claims:[hours,claim({claimId:"claim:unconfigured-takeaway"})],sourcePolicy:hoursPolicy,verificationRecords:[]},[hoursPolicy]); const mixedSnapshot=buildWorldKnowledgeSnapshot(parseBuildWorldKnowledgeInput({contractVersion:WORLD_KNOWLEDGE_PORT_VERSION,spotId:"spot:source",resolution:mixed},[hoursPolicy]),[hoursPolicy]); const decision=projectForDecision(mixedSnapshot,[hoursPolicy]); assert.deepEqual(decision.operationalRules.map((entry)=>entry.key),["hours.regular"]); assert.equal(decision.facts.some((entry)=>entry.key==="operation.takeaway"),false);
});

function verificationWorld(){
  const policy=configuredPolicy({"operation.takeaway":{process:"process:takeaway-check",useCases:["GENERAL_WORLD","HARD_CONSTRAINTS"],minimumTrust:"VERIFIED"}}); const verifiedClaim=claim({claimId:"claim:verify",verificationState:"VERIFIED",observedAt:"2026-09-10T12:00:00.000Z"});
  const process=createVerificationProcessContract({processId:"process:takeaway-check",processVersion:"1.0",policyVersion:policy.policyVersion,policyHash:policy.policyHash,attributeKeys:["operation.takeaway"],allowedVerifierRoles:["AUTHORIZED_HUMAN_VERIFIER"],requiredAuthorityClass:"PRODUCT_APPROVED_HUMAN_PROCESS",requiredSourceTypes:["OFFICIAL_SOURCE"],freshnessPolicyRef:"freshness:operation.takeaway",allowedResults:["VERIFIED","REJECTED","INCONCLUSIVE","REQUIRES_REVIEW"],maxFutureClockSkewSeconds:60},policy);
  const authority=createVerificationExecutionAuthority({authorityId:"authority:takeaway-test",processId:process.processId,processVersion:process.processVersion,processHash:process.processHash,verifierRole:"AUTHORIZED_HUMAN_VERIFIER",authorityClass:"PRODUCT_APPROVED_HUMAN_PROCESS",validFrom:"2026-09-10T11:00:00.000Z",validUntil:"2026-09-10T13:00:00.000Z"},process,policy); const context={processes:[process],authorities:[authority],serverTime:"2026-09-10T12:00:30.000Z"};
  const draft={recordId:"verification:1",policyVersion:policy.policyVersion,policyHash:policy.policyHash,claimId:verifiedClaim.claimId,claimHash:verifiedClaim.contentHash,attributeKey:verifiedClaim.attributeKey,spotId:verifiedClaim.scope.spotId,processId:process.processId,processVersion:process.processVersion,processHash:process.processHash,executionAuthorityId:authority.authorityId,executionAuthorityHash:authority.authorityHash,verifierRole:"AUTHORIZED_HUMAN_VERIFIER",sourceReferenceIds:["source:official"],result:"VERIFIED",checkedAt:"2026-09-10T12:00:15.000Z",reverificationPolicyRef:"freshness:operation.takeaway",reasonCodes:["DOCUMENT_MATCH"]}; return {policy,verifiedClaim,process,authority,context,draft};
}

test("verification requires separately accepted process and execution authority",()=>{
  const world=verificationWorld(); assert.throws(()=>createVerificationRecord(world.draft,world.verifiedClaim,world.policy),/authority is required/); const record=createVerificationRecord(world.draft,world.verifiedClaim,world.policy,world.context); assert.equal(parseVerificationRecord(record,world.verifiedClaim,world.policy,world.context).result,"VERIFIED");
  const otherAuthority=createVerificationExecutionAuthority({authorityId:"authority:other",processId:world.process.processId,processVersion:world.process.processVersion,processHash:world.process.processHash,verifierRole:"AUTHORIZED_HUMAN_VERIFIER",authorityClass:"PRODUCT_APPROVED_HUMAN_PROCESS",validFrom:"2026-09-10T11:00:00.000Z",validUntil:"2026-09-10T13:00:00.000Z"},world.process,world.policy); assert.throws(()=>createVerificationRecord({...world.draft,executionAuthorityId:otherAuthority.authorityId,executionAuthorityHash:otherAuthority.authorityHash},world.verifiedClaim,world.policy,world.context),/not accepted/);
  assert.throws(()=>createVerificationRecord({...world.draft,processVersion:"2.0"},world.verifiedClaim,world.policy,world.context),/unknown or stale/); assert.throws(()=>createVerificationRecord({...world.draft,reverificationPolicyRef:"freshness:wrong"},world.verifiedClaim,world.policy,world.context),/does not match/); assert.throws(()=>createVerificationRecord({...world.draft,checkedAt:"2026-09-10T11:59:59.000Z"},world.verifiedClaim,world.policy,world.context),/predate/); assert.throws(()=>createVerificationRecord({...world.draft,checkedAt:"2026-09-10T12:02:00.000Z"},world.verifiedClaim,world.policy,world.context),/clock skew/);
  assert.throws(()=>createVerificationRecord({...world.draft,spotId:"spot:other"},world.verifiedClaim,world.policy,world.context),/does not bind/); assert.throws(()=>createVerificationRecord({...world.draft,sourceReferenceIds:["source:swapped"]},world.verifiedClaim,world.policy,world.context),/claim-bound source/);
  const forged={...record,verifierRole:"INDEPENDENT_SYSTEM_CHECK"}; const {resultHash:_hash,...body}=forged; forged.resultHash=hashBody(body,[]); assert.throws(()=>parseVerificationRecord(forged,world.verifiedClaim,world.policy,world.context),/role is not bound/);
  const request={contractVersion:RESOLUTION_CONTRACT_VERSION,registryVersion:REGISTRY_VERSION,asOf:"2026-09-10T12:00:30.000Z",claims:[world.verifiedClaim],sourcePolicy:world.policy,verificationRecords:[record]}; assert.throws(()=>resolveWorldKnowledge(request,[world.policy]),/authority is required/); assert.equal(resolveWorldKnowledge(request,[world.policy],world.context).resolved[0].trust,"VERIFIED");
});

test("AI-only verification and inner payload substitution fail closed",()=>{
  const world=verificationWorld(); const aiPolicy=configuredPolicy({"operation.takeaway":{sources:["AI_INFERENCE"],actors:["SYSTEM"],reference:"REQUIRED",selfAssertion:true,process:"process:takeaway-check",useCases:["GENERAL_WORLD"],minimumTrust:"VERIFIED"}}); const ai=claim({claimId:"claim:ai",actorType:"SYSTEM",sourceType:"AI_INFERENCE",verificationState:"UNVERIFIED"}); assert.throws(()=>createVerificationRecord({...world.draft,policyVersion:aiPolicy.policyVersion,policyHash:aiPolicy.policyHash,claimId:ai.claimId,claimHash:ai.contentHash},ai,aiPolicy,world.context),/AI inference/);
});

const legacy=(overrides={})=>({spotId:"00000000-0000-4000-8000-000000000001",observedAt:"2026-09-10T12:00:00.000Z",sourceReferenceId:null,name:"Synthetic Bistro",address:"Testweg 1",city:"Basel",country:"ch",latitude:47.55,longitude:7.59,timezone:"Europe/Zurich",categoryName:"Restaurant",website:"https://example.invalid",phone:"+41790000000",hours:[{day:"Montag",open:"10:00",close:"22:00"}],facts:{price_level:3,atmosphere_tags:["cozy"]},commercialContext:{ownerTier:"PRO",payment:"PAID"},...overrides});
test("legacy adapter remains deterministic and decision projection is policy filtered",()=>{
  const one=adaptLegacySpot(legacy()),two=adaptLegacySpot(legacy());assert.equal(one.adapterVersion,LEGACY_ADAPTER_VERSION);assert.equal(one.resultHash,two.resultHash);assert.deepEqual(one.claims,two.claims);assert.equal(one.snapshot.spot.classification.primaryCategory,"EAT");assert.ok(one.claims.every(c=>c.verificationState==="UNVERIFIED"));assert.ok(one.audit.some(a=>a.legacyField==="facts.atmosphere_tags"&&a.outcome==="REQUIRES_REVIEW"));assert.ok(one.audit.some(a=>a.legacyField==="commercialContext.payment"&&a.outcome==="EXCLUDED"));assert.equal(JSON.stringify(one.snapshot).includes("PAID"),false);
  const decision=projectForDecision(one.snapshot);assert.equal("publicContact" in decision,false);assert.equal(decision.facts.length,0);assert.equal(decision.operationalRules.length,0);assert.equal(decision.classification.primaryCategory,null);
  const referenced=adaptLegacySpot(legacy({sourceReferenceId:"source:legacy-export"}));assert.notEqual(one.resultHash,referenced.resultHash);assert.notEqual(one.claims[0].contentHash,referenced.claims[0].contentHash);
  const ambiguous=adaptLegacySpot(legacy({categoryName:"Restaurant-Bar",timezone:null}));assert.ok(ambiguous.audit.some(a=>a.reasonCode==="CATEGORY_MAPPING_AMBIGUOUS"));assert.ok(ambiguous.audit.some(a=>a.reasonCode==="TIMEZONE_MISSING")); assert.deepEqual(profileLegacySpots([legacy(),legacy({name:null,categoryName:"Restaurant-Bar"})]),{totalSpots:2,coverage:{name:1,address:2,coordinates:2,timezone:2,category:2,hours:2,sourceReference:0},invalidHours:0,ambiguousCategories:1});
});
