import assert from "node:assert/strict";
import test from "node:test";
import {
  ATTRIBUTE_DEFINITIONS, FOUNDATION_REGISTRY_SHAPE, LEGACY_ADAPTER_VERSION, PRIMARY_CATEGORY_LABELS, REGISTRY_HASH, REGISTRY_VERSION, RESOLUTION_CONTRACT_VERSION,
  UNCONFIGURED_SOURCE_POLICY, adaptLegacySpot, createClaim, createRegistryRelease, createSourcePolicy, createVerificationRecord, evaluateClaimSource, parseSourcePolicy, parseVerificationRecord,
  profileLegacySpots, projectForDecision, resolveWorldKnowledge, sha256, sourceReadiness, validateRegistryTransition,
} from "../dist/index.js";

const release = (changeClass, previous, next, extras={}) => createRegistryRelease({registryVersion:next.version,registryHash:next.hash,predecessorVersion:previous.version,changeClass,createdAt:"2026-09-10T12:00:00.000Z",approval:{recordId:"approval:test",role:"PRODUCT_CTO",approvedAt:"2026-09-10T12:00:00.000Z"},changeSummary:["synthetic transition"],compatibilityStatus:"BACKWARD_COMPATIBLE",deprecations:[],aliases:[],...extras});
const shape = (version, definitions, labels=PRIMARY_CATEGORY_LABELS) => ({version,definitions,categoryLabels:labels,hash:sha256({version,definitions,categoryLabels:labels})});

test("registry governance permits labels/additions and rejects silent semantics, reuse, and removal",()=>{
  const base=shape(REGISTRY_VERSION,ATTRIBUTE_DEFINITIONS); const labels=structuredClone(PRIMARY_CATEGORY_LABELS); labels.EAT.de="Gastronomie"; const labelNext=shape("backyrd.world-knowledge.registry@1.1",ATTRIBUTE_DEFINITIONS,labels); assert.doesNotThrow(()=>validateRegistryTransition(base,labelNext,release("LABEL_ONLY",base,labelNext)));
  const extra={...ATTRIBUTE_DEFINITIONS[0],key:"identity.legal_name",labels:{de:"Rechtlicher Name",en:"Legal name"}}; const additive=shape("backyrd.world-knowledge.registry@1.1",[...ATTRIBUTE_DEFINITIONS,extra]); assert.doesNotThrow(()=>validateRegistryTransition(base,additive,release("ADDITIVE_DEFINITION",base,additive)));
  const changed=shape("backyrd.world-knowledge.registry@1.1",ATTRIBUTE_DEFINITIONS.map((d,i)=>i?d:{...d,max:999})); assert.throws(()=>validateRegistryTransition(base,changed,release("SEMANTIC_CHANGE",base,changed)),/major version/);
  const removed=shape("backyrd.world-knowledge.registry@2.0",ATTRIBUTE_DEFINITIONS.slice(1)); assert.throws(()=>validateRegistryTransition(base,removed,release("REMOVAL",base,removed)),/deprecation plan/);
  assert.equal(FOUNDATION_REGISTRY_SHAPE.version,REGISTRY_VERSION);
});

const claimDraft=(overrides={})=>({claimId:"claim:verify",attributeKey:"operation.takeaway",scope:{spotId:"spot:verify",area:"SPOT"},knowledgeState:"KNOWN_TRUE",value:true,actorType:"VERIFIED_OWNER",sourceType:"OWNER_ASSERTION",sourceReferenceId:"source:owner-document",provenanceSessionId:"session:test",verificationState:"VERIFIED",observedAt:"2026-09-10T12:00:00.000Z",validFrom:null,validUntil:null,stance:"SUPPORTS",visibility:"INTERNAL",supersedesClaimId:null,...overrides});
const configuredPolicy=()=>createSourcePolicy({policyVersion:"policy:synthetic:1",registryVersion:REGISTRY_VERSION,registryHash:REGISTRY_HASH,createdAt:"2026-09-10T12:00:00.000Z",entries:UNCONFIGURED_SOURCE_POLICY.entries.map(e=>e.attributeKey==="operation.takeaway"?{...e,state:"CONFIGURED",allowedSourceTypes:["OWNER_ASSERTION","ADMIN_OBSERVATION","OFFICIAL_SOURCE"],allowedActorTypes:["VERIFIED_OWNER","ADMIN"],sourceReference:"OPTIONAL",selfAssertionAllowed:true,verificationProcess:{requirement:"PROCESS_REQUIRED",allowedProcessIds:["process:takeaway-check"]},freshness:{policyRef:"freshness:takeaway",mode:"PERMANENT_UNTIL_CONTRADICTED"},useCases:{...e.useCases,GENERAL_WORLD:"ALLOWED",HARD_CONSTRAINTS:"ALLOWED"}}:e)});

test("source policy remains fail-closed and verification is separately bound",()=>{
  assert.equal(sourceReadiness(["hours.regular"],"OPENING_HOURS_ELIGIBILITY",UNCONFIGURED_SOURCE_POLICY).status,"PARTIAL"); assert.throws(()=>parseSourcePolicy({...UNCONFIGURED_SOURCE_POLICY,policyVersion:"unknown"}),/hash mismatch/);
  const policy=configuredPolicy(); const claim=createClaim(claimDraft()); assert.throws(()=>resolveWorldKnowledge({contractVersion:RESOLUTION_CONTRACT_VERSION,registryVersion:REGISTRY_VERSION,asOf:"2026-09-10T12:00:00.000Z",claims:[claim],sourcePolicy:policy,verificationRecords:[]},[policy]),/lacks valid/);
  const ownerAsserted=createClaim(claimDraft({claimId:"claim:owner",sourceReferenceId:null,verificationState:"UNVERIFIED"})); const adminAsserted=createClaim(claimDraft({claimId:"claim:admin",actorType:"ADMIN",sourceType:"ADMIN_OBSERVATION",sourceReferenceId:null,verificationState:"UNVERIFIED"})); const official=createClaim(claimDraft({claimId:"claim:official",actorType:"ADMIN",sourceType:"OFFICIAL_SOURCE",verificationState:"UNVERIFIED"})); assert.equal(evaluateClaimSource(ownerAsserted,policy).status,"ASSERTED"); assert.equal(evaluateClaimSource(adminAsserted,policy).status,"ASSERTED"); assert.equal(evaluateClaimSource(official,policy).status,"REFERENCED");
  const record=createVerificationRecord({recordId:"verification:1",policyVersion:policy.policyVersion,policyHash:policy.policyHash,claimId:claim.claimId,claimHash:claim.contentHash,attributeKey:claim.attributeKey,spotId:claim.scope.spotId,processId:"process:takeaway-check",processVersion:"1.0",verifierRole:"AUTHORIZED_HUMAN_VERIFIER",sourceReferenceIds:["source:owner-document"],result:"VERIFIED",checkedAt:"2026-09-10T12:00:00.000Z",reverificationPolicyRef:"freshness:takeaway",reasonCodes:["DOCUMENT_MATCH"]},claim,policy);
  assert.equal(parseVerificationRecord(record,claim,policy).result,"VERIFIED"); const request={contractVersion:RESOLUTION_CONTRACT_VERSION,registryVersion:REGISTRY_VERSION,asOf:"2026-09-10T12:00:00.000Z",claims:[claim],sourcePolicy:policy,verificationRecords:[record]}; assert.throws(()=>resolveWorldKnowledge(request),/unknown source policy/); const resolved=resolveWorldKnowledge(request,[policy]); assert.equal(resolved.resolved[0].trust,"VERIFIED");
  const {contractVersion:_cv,resultHash:_rh,...recordDraft}=record; assert.throws(()=>createVerificationRecord({...recordDraft,recordId:"verification:wrong",spotId:"spot:other"},claim,policy),/does not bind/);
  assert.throws(()=>createVerificationRecord({...recordDraft,recordId:"verification:tampered",sourceReferenceIds:["source:substituted"]},claim,policy),/claim-bound source/);
  const ai=createClaim(claimDraft({claimId:"claim:ai",actorType:"SYSTEM",sourceType:"AI_INFERENCE",verificationState:"UNVERIFIED"})); assert.throws(()=>createVerificationRecord({...recordDraft,recordId:"verification:ai",claimId:ai.claimId,claimHash:ai.contentHash},ai,policy),/AI inference/);
});

const legacy=(overrides={})=>({spotId:"00000000-0000-4000-8000-000000000001",observedAt:"2026-09-10T12:00:00.000Z",sourceReferenceId:null,name:"Synthetic Bistro",address:"Testweg 1",city:"Basel",country:"ch",latitude:47.55,longitude:7.59,timezone:"Europe/Zurich",categoryName:"Restaurant",website:"https://example.invalid",phone:"+41790000000",hours:[{day:"Montag",open:"10:00",close:"22:00"}],facts:{price_level:3,atmosphere_tags:["cozy"]},commercialContext:{ownerTier:"PRO",payment:"PAID"},...overrides});
test("legacy adapter is deterministic, conservative, source-sensitive and strips commercial context",()=>{
  const one=adaptLegacySpot(legacy()),two=adaptLegacySpot(legacy());assert.equal(one.adapterVersion,LEGACY_ADAPTER_VERSION);assert.equal(one.resultHash,two.resultHash);assert.deepEqual(one.claims,two.claims);assert.equal(one.snapshot.spot.classification.primaryCategory,"EAT");assert.ok(one.claims.every(c=>c.verificationState==="UNVERIFIED"));assert.ok(one.audit.some(a=>a.legacyField==="facts.atmosphere_tags"&&a.outcome==="REQUIRES_REVIEW"));assert.ok(one.audit.some(a=>a.legacyField==="commercialContext.payment"&&a.outcome==="EXCLUDED"));assert.equal(JSON.stringify(one.snapshot).includes("PAID"),false);assert.equal("ownerTier" in one.snapshot,false);
  const referenced=adaptLegacySpot(legacy({sourceReferenceId:"source:legacy-export"}));assert.notEqual(one.resultHash,referenced.resultHash);assert.notEqual(one.claims[0].contentHash,referenced.claims[0].contentHash);
  const decision=projectForDecision(one.snapshot);assert.equal("publicContact" in decision,false);assert.equal(JSON.stringify(decision).includes("example.invalid"),false);
  const ambiguous=adaptLegacySpot(legacy({categoryName:"Restaurant-Bar",timezone:null}));assert.ok(ambiguous.audit.some(a=>a.reasonCode==="CATEGORY_MAPPING_AMBIGUOUS"));assert.ok(ambiguous.audit.some(a=>a.reasonCode==="TIMEZONE_MISSING"));
  assert.deepEqual(profileLegacySpots([legacy(),legacy({name:null,categoryName:"Restaurant-Bar"})]),{totalSpots:2,coverage:{name:1,address:2,coordinates:2,timezone:2,category:2,hours:2,sourceReference:0},invalidHours:0,ambiguousCategories:1});
});
