import assert from "node:assert/strict";
import test from "node:test";
import { runQueueOnce } from "../src/queue-runner.mjs";
import { N2_VERSIONS } from "../../../decision-lab/src/n2-memory-user-intelligence.mjs";

const source={consentGranted:true,memoryEvents:[{id:"e",idempotencyKey:"e",userId:"u",eventType:"verified_visit",contractVersion:N2_VERSIONS.memoryEventContract,occurredAt:"2026-01-01T00:00:00.000Z",observedAt:"2026-01-01T00:00:00.000Z",ingestedAt:"2026-01-01T00:00:00.000Z",sessionId:"s",spotId:"a",momentSignature:{audience:"solo"},spotEvidence:{},evidenceEnvelope:{n4Availability:"FULL",placeType:"bar",tasteConcepts:[{concept:"vibe.cozy",confidence:.9}],momentSignature:{audience:"solo"},attributionDisposition:"PINNED_EVENT_TIME_N4"},provenance:{source:"fixture",sourceEventId:"e",sourceVersion:"v1"},consentPurpose:"personalized_recommendations",consentState:"granted"}],reviewsById:{},n4BySpot:{},asOf:"2026-01-01T00:00:00.000Z",watermark:"2026-01-01T00:00:00.000Z"};

test("runner claims and commits through the shared worker",async()=>{let persisted=false,failure=null;const repository={claimWork:async()=>({userId:"u",watermark:source.watermark,workIds:["e"],leaseToken:"l",attempt:1}),readCanonicalSources:async()=>source,readLatestCard:async()=>null,persistAtomically:async()=>{persisted=true;return{snapshotHash:"h"}},failWork:async(_claim,value)=>{failure=value}};const result=await runQueueOnce({repository});assert.equal(result.status,"COMMITTED",JSON.stringify(failure));assert.equal(persisted,true);});
test("runner classifies technical failure as retryable",async()=>{let failure;const repository={claimWork:async()=>({userId:"u",watermark:source.watermark,workIds:["e"],leaseToken:"l",attempt:1}),readCanonicalSources:async()=>{throw new Error("temporary_n4_read")},failWork:async(_claim,value)=>{failure=value}};const result=await runQueueOnce({repository});assert.equal(result.status,"RETRYABLE_FAILED");assert.equal(failure.retryable,true);});
test("runner reconciles a successful commit after response loss",async()=>{let failed=false;const repository={claimWork:async()=>({userId:"u",watermark:source.watermark,workIds:["e"],leaseToken:"l",attempt:1}),readCanonicalSources:async()=>source,readLatestCard:async()=>null,persistAtomically:async()=>{throw new Error("response_lost_after_commit")},reconcileWork:async()=>"COMMITTED",failWork:async()=>{failed=true}};const result=await runQueueOnce({repository});assert.equal(result.status,"COMMITTED_RECOVERED");assert.equal(failed,false);});
