import assert from "node:assert/strict";
import fs from "node:fs";
import http from "node:http";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { FounderLabService, minimizeFixtureSearch, UI_API_VERSION, UI_STORE_VERSION } from "./phase3d-founder-lab-service.mjs";
import { startFounderLabUiServer } from "./phase3d-founder-lab-ui-server.mjs";
import { contentHash } from "../../packages/user-intelligence-vnext-core/dist/index.js";

const fixedNow = () => "2026-09-12T12:00:00.000Z";
const setup = () => { const directory = fs.mkdtempSync(path.join(os.tmpdir(), "phase3d-ui-")); const statePath = path.join(directory, "state.json"); const service = new FounderLabService({ statePath, now: fixedNow }); service.createUser("Founder Test"); service.startJourney({ mode: "NEW", spotId: "fixture-cafe-cozy", dayPhase: "morning", companyType: "alone", timeBudget: "medium", requestedMoodConcept: null, intentLabel: "Café finden" }); return { service, statePath, directory }; };
const action = (service, actionName, extra = {}) => service.applyAction({ actionName, deliveryMode: "NORMAL", ...extra });
const newJourney = (service, overrides = {}) => service.startJourney({ mode: "NEW", spotId: "fixture-cafe-cozy", dayPhase: "morning", companyType: "alone", timeBudget: "medium", requestedMoodConcept: null, intentLabel: "Café finden", ...overrides });

test("UI store and API are explicitly local evaluation contracts", () => { assert.match(UI_STORE_VERSION, /founder-lab-ui-store@3d-1/); assert.match(UI_API_VERSION, /founder-lab-ui-api@3d-1/); });
test("fixture search minimizes approved phrases without retaining raw text", () => { const value = minimizeFixtureSearch("gemütliches Café am Vormittag"); assert.deepEqual(value.conceptIds, ["place_type.cafe", "vibe.cozy"]); assert.equal(value.rawTextStored, false); assert.equal(JSON.stringify(value).includes("gemütliches Café am Vormittag"), false); });
test("unknown search is fail-closed and does not change state", () => { const { service, statePath } = setup(); const before = fs.readFileSync(statePath, "utf8"); assert.throws(() => action(service, "search", { searchText: "mein privater unbekannter text", searchScope: "SELF_CURRENT" }), /nicht verstanden/); assert.equal(fs.readFileSync(statePath, "utf8"), before); });
test("client-selected policy strength independence authority and commercial fields fail closed", () => { const forbidden = ["policy", "signalStrength", "independence", "authority", "ownerTier", "rankingAuthorized", "eligibilityAuthorized", "retentionDays"]; for (const field of forbidden) { const { service, statePath } = setup(); const before = fs.readFileSync(statePath, "utf8"); assert.throws(() => service.applyAction({ actionName: "save", deliveryMode: "NORMAL", [field]: field === "signalStrength" ? 99 : "FORGED" }), /unbekannte Feld/); assert.equal(fs.readFileSync(statePath, "utf8"), before); } });
test("search for another person remains an inactive observation", () => { const { service } = setup(); const view = action(service, "search", { searchText: "ruhig essen beim ersten Date", searchScope: "FOR_OTHER_PERSON" }); assert.equal(view.timeline[0].status, "INACTIVE"); assert.equal(view.internalModel.interpretations.length, 0); });
test("three independent searches expose different calibration outcomes", () => { const { service } = setup(); for (let index = 0; index < 3; index++) { if (index) newJourney(service, { spotId: index === 1 ? "fixture-cafe-bright" : "fixture-bar-lively" }); action(service, "search", { searchText: "gemütliches Café am Vormittag", searchScope: "SELF_CURRENT" }); } const view = service.view(); assert.deepEqual(view.candidates.map(({ current }) => current.searchContextualTargets.length), [0, 2, 2]); assert.equal(JSON.stringify(view).includes("gemütliches Café am Vormittag"), false); });
test("familiarity appears only after three independent visit journeys", () => { const { service } = setup(); action(service, "visit"); newJourney(service); action(service, "visit"); assert.equal(service.view().internalModel.interpretations.some(({ kind }) => kind === "FAMILIARITY"), false); newJourney(service); action(service, "visit"); assert.equal(service.view().internalModel.interpretations.some(({ kind }) => kind === "FAMILIARITY"), true); });
test("multiple visits in one journey never create familiarity", () => { const { service } = setup(); action(service, "visit"); action(service, "visit"); action(service, "visit"); assert.equal(service.view().internalModel.interpretations.some(({ kind }) => kind === "FAMILIARITY"), false); });
test("review and satisfaction remain separate while strongest journey signal wins", () => { const { service } = setup(); action(service, "visit"); action(service, "review"); action(service, "matched"); const view = service.view(); assert.equal(view.timeline.length, 3); assert.equal(view.internalModel.interpretations.filter(({ direction }) => direction === "POSITIVE").length, 1); });
test("satisfaction and authorized moment require a prior qualified experience in the same journey", () => { for (const actionName of ["matched", "notMatched", "neutral", "moment"]) { const { service } = setup(); assert.throws(() => action(service, actionName), /bestätigten Besuch oder ein Review/); assert.equal(service.view().timeline.length, 0); } });
test("skip and not-fit stay context-bound and never become a global aversion", () => { const { service } = setup(); action(service, "skip"); action(service, "notFit"); const view = service.view(); assert.ok(view.internalModel.interpretations.every(({ targetKey, kind }) => kind !== "AVERSION" && (!kind.includes("AFFINITY") || targetKey.includes(":decision:")))); });
test("positive and negative outcomes in the same target and context create a withheld conflict", () => { const { service } = setup(); action(service, "visit"); action(service, "matched"); newJourney(service); action(service, "visit"); action(service, "notMatched"); const view = service.view(); assert.equal(view.internalModel.conflicts.length, 1); assert.equal(view.internalModel.evaluationPreview.withheldConflictIds.length, 1); });
test("dwell is visible only as attention and never enters production projection", () => { const { service } = setup(); action(service, "dwell"); const view = service.view(); assert.ok(view.internalModel.interpretations.some(({ kind }) => kind === "INTERACTION_ATTENTION")); assert.equal(view.internalModel.evaluationPreview.items.length, 0); assert.equal(view.internalModel.productionProjection.items.length, 0); });
test("moment without external experience authority is rejected and leaves no observation", () => { const { service } = setup(); const view = service.applyAction({ actionName: "momentWithoutAuthority" }); assert.equal(view.timeline.length, 0); assert.equal(view.rejectedAttempts[0].reason, "MISSING_QUALIFIED_EXPERIENCE_AUTHORITY"); });
test("retry deduplicates and correction preserves append-only history", () => { const { service } = setup(); action(service, "visit"); action(service, "matched"); service.retryLast(); assert.equal(service.view().timeline.length, 2); service.correctLast(); const view = service.view(); assert.equal(view.timeline.length, 3); assert.equal(view.timeline[1].status, "CORRECTED"); assert.equal(view.rejectedAttempts[0].reason, "DELIVERY_RETRY_DEDUPLICATED"); });
test("full, incremental and replay operations remain byte-identical", () => { const { service } = setup(); action(service, "search", { searchText: "gemütliches Café am Vormittag", searchScope: "SELF_CURRENT" }); assert.equal(service.rebuild("FULL").operation.byteIdentical, true); assert.equal(service.rebuild("INCREMENTAL").operation.byteIdentical, true); assert.equal(service.rebuild("REPLAY").operation.byteIdentical, true); });
test("withdrawal and reset remove subject, actions and rebuild checkpoint", () => { for (const lifecycleAction of ["WITHDRAW", "RESET"]) { const { service, statePath } = setup(); action(service, "visit"); action(service, "matched"); service.lifecycle(lifecycleAction, true); const raw = JSON.parse(fs.readFileSync(statePath, "utf8")); const user = raw.users[0]; assert.equal(user.subjectBindingHash, null); assert.equal(user.actions.length, 0); assert.equal(user.checkpoint.stateHash, null); assert.equal(service.view().internalModel.interpretations.length, 0); } });
test("erasure removes the complete selected test-user record", () => { const { service, statePath } = setup(); service.lifecycle("ERASE", true); assert.equal(JSON.parse(fs.readFileSync(statePath, "utf8")).users.length, 0); assert.equal(service.view().selectedUser, null); });
test("tampered persistent state fails closed", () => { const { service, statePath } = setup(); const value = JSON.parse(fs.readFileSync(statePath, "utf8")); value.users[0].actions.push({ ownerTier: "premium" }); fs.writeFileSync(statePath, JSON.stringify(value)); assert.throws(() => service.view(), /beschädigt|unbekannten/); });
test("fully rehashed inner state manipulation still fails schema validation", () => { const { service, statePath } = setup(); const value = JSON.parse(fs.readFileSync(statePath, "utf8")); value.users[0].ownerTier = "premium"; const body = Object.fromEntries(Object.entries(value).filter(([key]) => key !== "integrityHash")); value.integrityHash = contentHash(body); fs.writeFileSync(statePath, JSON.stringify(value)); assert.throws(() => service.view(), /unbekannte Feld ownerTier/); });
test("privacy export is separate, synthetic and contains no secrets", () => { const { service } = setup(); action(service, "save"); const exported = service.privacyExport(); assert.equal(exported.authority, "LOCAL_PRIVACY_LEGAL_TEST_ONLY"); assert.equal(exported.productionAuthorized, false); assert.doesNotMatch(JSON.stringify(exported), /service_role|token|secret/i); });
test("service output cannot carry production, ranking or eligibility authority", () => { const { service } = setup(); action(service, "visit"); action(service, "matched"); const view = service.view(); assert.deepEqual(view.boundaries, { localOnly: true, productionAuthorized: false, rankingAuthority: false, eligibilityAuthority: false, worldSource: "SYNTHETIC_FIXTURE", rawSearchTextStored: false, retentionDurationsConfigured: false }); assert.equal(view.internalModel.productionProjection.containsPersonalModelData, false); });
test("Founder view explains all five selected calibration rules without exposing authority codes", () => { const { service } = setup(); const selections = service.view().founderSelections; assert.equal(selections.length, 5); assert.deepEqual(selections.map(({ key }) => key), ["searchContextualMaturity", "searchLongTermPromotion", "skipMaturity", "conceptTasteMinimumDistinctSpots", "retention"]); assert.match(selections[0].selection, /3 unabhängige/); assert.match(selections[1].selection, /6 unabhängige/); assert.match(selections[2].selection, /3 unabhängige/); assert.match(selections[3].selection, /3 (verschiedene|unterschiedliche) Spots/); assert.match(selections[4].boundary, /Legal-\/CTO-Freigabe/); assert.doesNotMatch(JSON.stringify(selections), /CALIBRATION_ONLY|PRODUCT_ACTIVATION_NOT_AUTHORIZED|[a-f0-9]{64}/); });
test("browser assets contain no external services secrets or end-user taste dashboard", () => { for (const file of ["index.html", "app.js", "styles.css"]) { const source = fs.readFileSync(new URL(`phase3d-founder-lab-ui/${file}`, import.meta.url), "utf8"); assert.doesNotMatch(source, /supabase|service[_-]?role|api[_-]?key|bearer\s|taste dashboard/i); } });
test("checked-in release summary binds the exact local UI and server sources", () => {
  const files = [
    "scripts/user-intelligence/phase3d-founder-lab-service.mjs",
    "scripts/user-intelligence/phase3d-founder-lab-ui-server.mjs",
    "scripts/user-intelligence/phase3d-founder-lab-ui/index.html",
    "scripts/user-intelligence/phase3d-founder-lab-ui/styles.css",
    "scripts/user-intelligence/phase3d-founder-lab-ui/app.js",
  ];
  const release = {
    contractVersion: "backyrd.user-intelligence.founder-lab-ui-release@3d-1",
    bindAddress: "127.0.0.1",
    productionAuthorized: false,
    sourceFiles: files.map((file) => ({ file, contentHash: contentHash(fs.readFileSync(file, "utf8")) })),
  };
  const summary = JSON.parse(fs.readFileSync(new URL("../../docs/user-intelligence-vnext/phase3d/phase3d-release-summary.json", import.meta.url), "utf8"));
  assert.equal(summary.interactiveUiHash, contentHash(release));
});
test("HTTP server binds only to loopback and rejects external host headers", async (t) => { const directory = fs.mkdtempSync(path.join(os.tmpdir(), "phase3d-http-")); assert.throws(() => startFounderLabUiServer({ host: "0.0.0.0", port: 0, statePath: path.join(directory, "bad.json") }), /127\.0\.0\.1/); const { server, url } = await startFounderLabUiServer({ port: 0, statePath: path.join(directory, "state.json"), now: fixedNow }); t.after(() => server.close()); assert.equal((await fetch(`${url}/api/health`)).status, 200); const status = await new Promise((resolve, reject) => { const target = new URL(url); const request = http.request({ hostname: target.hostname, port: target.port, path: "/api/health", headers: { Host: "evil.example" } }, (response) => { response.resume(); resolve(response.statusCode); }); request.on("error", reject); request.end(); }); assert.equal(status, 403); });
test("HTTP errors are German structured responses without stack traces", async (t) => { const directory = fs.mkdtempSync(path.join(os.tmpdir(), "phase3d-errors-")); const { server, url } = await startFounderLabUiServer({ port: 0, statePath: path.join(directory, "state.json"), now: fixedNow }); t.after(() => server.close()); const response = await fetch(`${url}/api/actions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ actionName: "forged", policy: "client-choice" }) }); const payload = await response.json(); assert.equal(response.status, 400); assert.equal(payload.stateUnchanged, true); assert.equal("stack" in payload, false); });
test("HTTP responses enforce no-store CSP and reject a foreign browser origin", async (t) => { const directory = fs.mkdtempSync(path.join(os.tmpdir(), "phase3d-headers-")); const { server, url } = await startFounderLabUiServer({ port: 0, statePath: path.join(directory, "state.json"), now: fixedNow }); t.after(() => server.close()); const page = await fetch(url); assert.equal(page.headers.get("cache-control"), "no-store"); assert.match(page.headers.get("content-security-policy"), /connect-src 'self'/); const rejected = await fetch(`${url}/api/users`, { method: "POST", headers: { "Content-Type": "application/json", Origin: "https://evil.example" }, body: JSON.stringify({ label: "X" }) }); assert.equal(rejected.status, 403); });
