const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
let state = null; let selectedRule = "searchContextualMaturity"; let lateNext = false;
const german = { morning:"Vormittag",midday:"Mittag",evening:"Abend",night:"Nacht",alone:"Allein",friends:"Mit Freunden",partner:"Mit Partner:in",family:"Mit Familie",first_date:"Erstes Date",short:"kurz",medium:"mittel",open:"offen", ACTIVE:"Aktiv",WITHDRAWN:"Consent widerrufen",RESET:"Zurückgesetzt",ERASED:"Gelöscht", POSITIVE:"positiv",NEGATIVE:"negativ",NEUTRAL:"neutral",UNKNOWN:"unsicher" };
const safe = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const request = async (url, options = {}) => { const response = await fetch(url, { headers:{"Content-Type":"application/json"},...options }); const payload = await response.json(); if (!response.ok || !payload.ok) throw payload; return payload.data; };
function notice(message, error=false){const el=$("#notice");el.textContent=message;el.className=`notice${error?" error":""}`;el.hidden=false;setTimeout(()=>{el.hidden=true},5000)}
async function refresh(message){ state=await request("/api/state"); if(message) notice(message); render(); }
async function mutate(url, body){document.body.classList.add("loading");try{state=await request(url,{method:"POST",body:JSON.stringify(body)});notice(state.message||"Lokaler Lab-Stand aktualisiert.");render()}catch(error){notice(`${error.message} ${error.stateUnchanged?"Der Zustand blieb unverändert.":""} ${error.nextAction||""}`,true)}finally{document.body.classList.remove("loading")}}
function render(){renderUsers();renderSituation();renderActions();renderTimeline();renderModel();renderCandidates();renderExpert()}
function renderUsers(){const select=$("#user-select");select.innerHTML=`<option value="">Testnutzer auswählen</option>${state.users.map(u=>`<option value="${safe(u.userId)}" ${u.userId===state.selectedUser?.userId?"selected":""}>${safe(u.label)}</option>`).join("")}`;const u=state.selectedUser;$("#user-status").innerHTML=u?`<b>${safe(u.label)}</b><br><span>Consent: ${safe(u.consent)} · ${safe(german[u.lifecycle]||u.lifecycle)}</span><br><small>${u.hasModel?"Aktives lokales Modell":"Noch kein persönliches Modell"} · zuletzt ${new Date(u.updatedAt).toLocaleString("de-CH")}</small>`:"Kein aktiver Testnutzer"}
function renderSituation(){const spots=$("#spot");const selected=state.selectedUser?.currentJourney?.spotId;spots.innerHTML=state.fixtureSpots.map(s=>`<option value="${safe(s.spotId)}" ${s.spotId===selected?"selected":""}>${safe(s.label)}</option>`).join("");const j=state.selectedUser?.currentJourney;if(j){$("#day-phase").value=j.context.dayPhase;$("#company").value=j.context.companyType;$("#time-budget").value=j.context.timeBudget;$("#intent").value=j.context.intentLabel;$("#journey-status").innerHTML=`<b>Aktive Journey</b> · ${safe(j.spotId)} · ${safe(german[j.context.dayPhase])} · ${safe(german[j.context.companyType])}<br><small>Neue Journey = neue mögliche Independence Unit. Fortsetzen = dieselbe Journey.</small>`}else $("#journey-status").textContent="Noch keine Situation gestartet."}
function renderActions(){const skip=new Set(["search"]);$("#action-grid").innerHTML=state.actions.filter(a=>!skip.has(a.actionName)).map(a=>`<button class="action-card" data-action="${safe(a.actionName)}"><b>${safe(a.label)}</b><span>${safe(a.possibleLearning)}</span><small>Nicht daraus gelernt: ${safe(a.forbiddenLearning)}</small></button>`).join("")}
function renderTimeline(){const rows=state.timeline;$("#timeline-count").textContent=`${rows.length} Einträge`;const el=$("#timeline");if(!rows.length){el.className="timeline empty";el.textContent="Noch keine Beobachtung.";return}el.className="timeline";el.innerHTML=[...rows].reverse().map(r=>`<article class="timeline-item" data-event="${safe(r.eventType)}"><time>${new Date(r.occurredAt).toLocaleString("de-CH")}</time><div><b>${safe(r.action)}</b><small>${safe(r.contextLabel)} · ${safe(r.target)}</small><div class="tags"><span class="tag ${r.direction.startsWith("POSITIVE")?"positive":r.direction.startsWith("NEGATIVE")?"negative":"neutral"}">${safe(r.direction)}</span><span class="tag">${safe(r.status)}</span><span class="tag">${r.withheld?"zurückgehalten":"auswertbar"}</span></div></div><small>${safe(r.journeyId)}<br>${safe(r.authorityStatus)}</small></article>`).join("")}
const friendlyKind=(kind)=>({DIRECT_SPOT_PLANNING:"Planning State",FAMILIARITY:"Familiarity",RECENT_SEARCH_INTENT:"Kurzfristige Absicht",CONTEXTUAL_SEARCH_READINESS:"Contextual Hypothese",CONTEXTUAL_CONCEPT_TASTE:"Nur für diese Situation",CONCEPT_PROMOTION_READINESS:"Mögliche Long-Term-Hypothese",LONG_TERM_CONCEPT_TASTE:"Mögliche langfristige Präferenz",AVERSION:"Aversion",EXPLORATION_REQUEST:"Exploration",SEMANTIC_CONFLICT:"Konflikt",INTERACTION_ATTENTION:"Getrennte Attention-Beobachtung",DIRECT_SPOT_AFFINITY:"Direkte Spot-Beziehung",EXPERIENCE_SUPPORT:"Experience gestützt"}[kind]||kind);
function renderModel(){const m=state.internalModel;$("#model-summary").innerHTML=`<div class="metric"><strong>${m.observations}</strong><span>Sichere Beobachtungen</span></div><div class="metric"><strong>${m.interpretations.length}</strong><span>Vorsichtige Ableitungen</span></div><div class="metric"><strong>${m.conflicts.length}</strong><span>Widersprüchliche Erfahrungen</span></div><div class="metric"><strong>${m.evaluationPreview?.items?.length||0}</strong><span>Evaluation Preview · nicht Production</span></div>`;const rows=[...m.interpretations.map(i=>({title:friendlyKind(i.kind),copy:i.maturity==="TRANSITION_NOT_CONFIGURED"?"Diese Regel ist noch nicht festgelegt":i.kind==="FAMILIARITY"?"Drei unabhängige Besuche – Spot ist vertraut":i.kind==="RECENT_SEARCH_INTENT"?"Einmalige aktuelle Suchabsicht":i.kind==="CONTEXTUAL_SEARCH_READINESS"?"Wiederkehrendes Muster – Promotion noch nicht freigegeben":i.direction==="POSITIVE"?"Vorsichtige positive Hypothese":i.direction==="NEGATIVE"?"Vorsichtige negative Hypothese":"Unsicherheit bleibt erhalten",meta:`${i.targetKey} · ${german[i.direction]||i.direction}`})),...m.conflicts.map(c=>({title:"Widersprüchliche Erfahrungen",copy:"Keine Richtung wird verwendet",meta:c.targetKey}))];$("#interpretations").innerHTML=rows.length?rows.map(i=>`<article class="interpretation"><b>${safe(i.title)}</b><p>${safe(i.copy)}</p><small>${safe(i.meta)}</small></article>`).join(""):`<article class="interpretation"><b>Noch nicht ausreichend bestätigt</b><p>Führe kontrollierte Handlungen aus. Fehlende Evidence ist keine negative Präferenz.</p></article>`}
const rules={searchContextualMaturity:"Search Contextual Maturity",searchLongTermPromotion:"Search Long-Term Promotion",skipMaturity:"Skip Maturity",conceptTaste:"Spots für Concept Taste",retention:"Retention"};
function outcomeText(candidate){const current=candidate.current;if(!current)return"Noch keine Evidence";if(selectedRule==="searchContextualMaturity")return current.searchContextualTargets.length?"Würde hypothetisch eine contextgebundene Hypothese freigeben":"Hält weiterhin zurück";if(selectedRule==="searchLongTermPromotion")return current.searchLongTermTargets.length?"Long-Term-Bereitschaft im Lab erreicht":"Hält weiterhin zurück";if(selectedRule==="skipMaturity")return current.maturedSkipTargets.length?"Begrenzte situative Reife im Lab":"Hält weiterhin zurück";if(selectedRule==="conceptTaste")return current.conceptTasteTargets.length?"Concept-Bereitschaft im Lab erreicht":"Hält weiterhin zurück";return"Legal-/CTO-Entscheidung erforderlich; keine Frist konfiguriert"}
function requirement(rule){if(rule.independentJourneys!==undefined)return`${rule.independentJourneys} unabhängige Journeys`;if(rule.distinctSpots!==undefined)return`${rule.distinctSpots} unterschiedliche Spots`;return`Strategie: ${rule.strategy} · keine Zeitdauer`}
function renderCandidates(){$("#rule-tabs").innerHTML=Object.entries(rules).map(([id,label])=>`<button data-rule="${id}" class="${id===selectedRule?"active":""}">${label}</button>`).join("");$("#candidate-grid").innerHTML=state.candidates.map(c=>`<article class="candidate"><div class="labels">CALIBRATION_ONLY · NICHT PRODUCTION-AUTORISIERT</div><h3>${safe(c.title)}</h3><dl><dt>Benötigte Evidence</dt><dd>${safe(requirement(c.rules[selectedRule]))}</dd><dt>Aktueller Zustand</dt><dd>${safe(outcomeText(c))}</dd><dt>Vorteil</dt><dd>${safe(c.benefits.join(" · "))}</dd><dt>Risiko</dt><dd>${safe(c.risks.join(" · "))}</dd><dt>Privacy</dt><dd>${selectedRule==="retention"?"Fristen bleiben unkonfiguriert":"Nur minimierte lokale Fixture-Daten"}</dd></dl><div class="outcome">Keine Ranking- oder Eligibility-Wirkung</div></article>`).join("")}
function renderExpert(){$("#expert-view").textContent=JSON.stringify({selectedUser:state.selectedUser,expert:state.expert,rejectedAttempts:state.rejectedAttempts,boundaries:state.boundaries,productionProjection:state.internalModel.productionProjection},null,2)}
function journey(mode){return mutate("/api/journey",{mode,spotId:$("#spot").value,dayPhase:$("#day-phase").value,companyType:$("#company").value,timeBudget:$("#time-budget").value,requestedMoodConcept:null,intentLabel:$("#intent").value})}
async function action(name){const body={actionName:name,searchText:name==="search"?$("#search-text").value:undefined,searchScope:name==="search"?$("#search-scope").value:undefined,deliveryMode:lateNext?"LATE":"NORMAL"};lateNext=false;await mutate("/api/actions",body)}
$("#new-user").addEventListener("click",()=>{const label=$("#new-user-label").value.trim();if(label)mutate("/api/users",{label});else notice("Bitte einen lokalen Namen eingeben.",true)});
$("#user-select").addEventListener("change",e=>e.target.value&&mutate("/api/select-user",{userId:e.target.value}));$("#new-journey").addEventListener("click",()=>journey("NEW"));$("#continue-journey").addEventListener("click",()=>journey("CONTINUE"));$("#actions-section").addEventListener("click",e=>{const button=e.target.closest("[data-action],[data-special]");if(!button)return;if(button.dataset.action)action(button.dataset.action);else if(button.dataset.special==="late"){lateNext=true;notice("Die nächste Handlung wird mit einem früheren zulässigen Zeitpunkt eingespielt.")}else action(button.dataset.special)});$("#candidates-section").addEventListener("click",e=>{const b=e.target.closest("[data-rule]");if(b){selectedRule=b.dataset.rule;renderCandidates()}});$$('[data-rebuild]').forEach(b=>b.addEventListener("click",async()=>{await mutate("/api/rebuild",{mode:b.dataset.rebuild});$("#integrity-status").textContent=state.operation?.message||state.message||"Prüfung abgeschlossen."}));
let pendingLifecycle=null;$$('[data-lifecycle]').forEach(b=>b.addEventListener("click",()=>{pendingLifecycle=b.dataset.lifecycle;const copy={WITHDRAW:"Consent wird widerrufen. Events, Modell und Rebuild-Material dieses lokalen Testnutzers werden entfernt.",RESET:"Modell, Events, Checkpoint und Rebuild-Material dieses lokalen Testnutzers werden vollständig zurückgesetzt.",ERASE:"Der lokale Testnutzer und sämtliche zugehörigen Daten werden gelöscht."};$("#confirm-title").textContent=b.textContent;$("#confirm-copy").textContent=copy[pendingLifecycle];$("#confirm-dialog").showModal()}));$("#confirm-dialog").addEventListener("close",()=>{if($("#confirm-dialog").returnValue==="confirm"&&pendingLifecycle)mutate("/api/lifecycle",{action:pendingLifecycle,confirmed:true});pendingLifecycle=null});
refresh().catch(error=>notice(error.message||"Lab konnte nicht geladen werden.",true));
