import { sha256 } from "./canonical.js";

export const LEGACY_MAPPING_VERSION = "backyrd.world-knowledge.legacy-mapping@1.1" as const;
export const MAPPING_STATUSES = ["DIRECT", "NORMALIZED", "AMBIGUOUS", "SUBJECTIVE", "MISSING_PROVENANCE", "UNSUPPORTED", "DEPRECATED", "PROHIBITED", "NO_TARGET_KEY"] as const;
export type MappingStatus = typeof MAPPING_STATUSES[number];
export interface LegacyMappingRow { readonly sourceSystem: string; readonly location: string; readonly field: string; readonly legacyType: string; readonly meaning: string; readonly writeAuthority: string; readonly sourceTrust: string; readonly targetKey: string | null; readonly transformation: string; readonly status: MappingStatus; readonly informationLoss: string; readonly conflictRisk: "LOW" | "MEDIUM" | "HIGH"; readonly verificationRequired: boolean; readonly engineEligibility: "POSSIBLE_AFTER_POLICY" | "EXPLANATION_ONLY" | "PROHIBITED"; readonly recommendation: "KEEP" | "ADAPT" | "EXTEND" | "REPLACE" | "DEPRECATE" | "DO_NOT_MIGRATE" | "UNKNOWN_NEEDS_DECISION" }
const row = (value: LegacyMappingRow) => Object.freeze(value);
export const LEGACY_MAPPING_MATRIX: readonly LegacyMappingRow[] = Object.freeze([
  row({ sourceSystem:"spots",location:"public.spots",field:"id",legacyType:"uuid",meaning:"Canonical database spot identity",writeAuthority:"database/admin flows",sourceTrust:"identity key",targetKey:null,transformation:"Bind as World scope.spotId",status:"DIRECT",informationLoss:"none",conflictRisk:"LOW",verificationRequired:false,engineEligibility:"POSSIBLE_AFTER_POLICY",recommendation:"KEEP" }),
  ...([ ["name","identity.name"],["address","location.address_line1"],["city","location.locality"],["country","location.country_code"],["lat","location.latitude"],["lng","location.longitude"],["website","contact.website"],["phone","contact.phone"] ] as const).map(([field,targetKey]) => row({ sourceSystem:"spots",location:"public.spots",field,legacyType:["lat","lng"].includes(field)?"numeric":"text",meaning:`Legacy ${field}`,writeAuthority:"admin/import/legacy functions",sourceTrust:"no field-level evidence",targetKey,transformation:field==="country"?"Normalize only ISO alpha-2; otherwise review":"Validate through registry type",status:"MISSING_PROVENANCE",informationLoss:"actor/source/freshness absent",conflictRisk:"MEDIUM",verificationRequired:true,engineEligibility:"POSSIBLE_AFTER_POLICY",recommendation:"ADAPT" })),
  row({sourceSystem:"spots",location:"public.spots",field:"email",legacyType:"text",meaning:"Public or owner contact is not distinguished",writeAuthority:"admin/import",sourceTrust:"no provenance",targetKey:null,transformation:"Do not infer public visibility",status:"AMBIGUOUS",informationLoss:"privacy classification absent",conflictRisk:"HIGH",verificationRequired:true,engineEligibility:"PROHIBITED",recommendation:"UNKNOWN_NEEDS_DECISION"}),
  row({sourceSystem:"spots",location:"public.spots",field:"category_id",legacyType:"uuid",meaning:"Single legacy category",writeAuthority:"admin/import",sourceTrust:"taxonomy relation only",targetKey:"classification.primary_category",transformation:"Explicit allow-listed category mapping",status:"NORMALIZED",informationLoss:"legacy naming/version not embedded",conflictRisk:"MEDIUM",verificationRequired:true,engineEligibility:"POSSIBLE_AFTER_POLICY",recommendation:"ADAPT"}),
  row({sourceSystem:"spots",location:"public.spots",field:"price_level",legacyType:"integer",meaning:"Ordinal price level",writeAuthority:"admin/import",sourceTrust:"no currency/range/provenance",targetKey:"operation.price_range",transformation:"None: ordinal cannot become money range",status:"AMBIGUOUS",informationLoss:"currency and amount missing",conflictRisk:"HIGH",verificationRequired:true,engineEligibility:"PROHIBITED",recommendation:"REPLACE"}),
  row({sourceSystem:"spots",location:"public.spots",field:"status",legacyType:"enum",meaning:"Lifecycle/distribution state",writeAuthority:"admin/import/operations",sourceTrust:"operational database state",targetKey:null,transformation:"Keep as spot lifecycle, not current venue state",status:"NO_TARGET_KEY",informationLoss:"none",conflictRisk:"HIGH",verificationRequired:false,engineEligibility:"PROHIBITED",recommendation:"KEEP"}),
  row({sourceSystem:"spots",location:"public.spots",field:"google_place_id",legacyType:"text",meaning:"External provider identity",writeAuthority:"import/admin",sourceTrust:"provider reference",targetKey:null,transformation:"Bind later as namespaced external identity",status:"NO_TARGET_KEY",informationLoss:"namespace currently implicit",conflictRisk:"HIGH",verificationRequired:true,engineEligibility:"PROHIBITED",recommendation:"EXTEND"}),
  row({sourceSystem:"spots",location:"public.spots",field:"description",legacyType:"text",meaning:"Mixed editorial or owner description",writeAuthority:"admin/owner/import",sourceTrust:"actor/source not field-bound",targetKey:"description.highlight",transformation:"Only after provenance and authorship classification",status:"AMBIGUOUS",informationLoss:"objective and subjective text mixed",conflictRisk:"HIGH",verificationRequired:false,engineEligibility:"EXPLANATION_ONLY",recommendation:"ADAPT"}),
  row({sourceSystem:"spots",location:"public.spots/photos",field:"header_photo_path/photo_url",legacyType:"text",meaning:"Display media",writeAuthority:"admin/owner/provider",sourceTrust:"storage/provider metadata varies",targetKey:null,transformation:"Keep in media domain",status:"NO_TARGET_KEY",informationLoss:"none",conflictRisk:"LOW",verificationRequired:false,engineEligibility:"PROHIBITED",recommendation:"KEEP"}),
  row({sourceSystem:"spot_hours",location:"public.spot_hours",field:"day_of_week/open_time/close_time",legacyType:"text/time/time",meaning:"Weekly venue hours",writeAuthority:"admin/import",sourceTrust:"no source, timezone, observation or validity",targetKey:"hours.regular",transformation:"Validate weekdays/times and group schedule",status:"MISSING_PROVENANCE",informationLoss:"timezone/source/freshness absent",conflictRisk:"HIGH",verificationRequired:true,engineEligibility:"POSSIBLE_AFTER_POLICY",recommendation:"ADAPT"}),
  ...([ ["restaurant.takeaway","operation.takeaway"],["restaurant.cuisines","offering.cuisines"],["restaurant.payment_methods","operation.payment_methods"],["restaurant.capacity","capacity.seats_total"],["restaurant.reservation_policy","rule.reservation"],["restaurant.service_types","operation.service_model"],["opening.special_overrides","hours.special"] ] as const).map(([field,targetKey]) => row({sourceSystem:"gold-authoring",location:"backyrd_spot_accepted_facts_v1",field,legacyType:"jsonb",meaning:`Accepted Gold authoring value ${field}`,writeAuthority:"founder/admin SECURITY DEFINER RPC",sourceTrust:"source row exists; legacy acceptance/0.95 is not World verification",targetKey,transformation:"Allow-listed value-level transform with source binding when present",status:"NORMALIZED",informationLoss:"legacy verification semantics discarded",conflictRisk:"MEDIUM",verificationRequired:true,engineEligibility:"POSSIBLE_AFTER_POLICY",recommendation:"ADAPT"})),
  row({sourceSystem:"gold-authoring",location:"backyrd_spot_accepted_facts_v1",field:"accessibility.basic/accessibility.capabilities",legacyType:"jsonb",meaning:"Mixed accessibility summary/components",writeAuthority:"founder/admin SECURITY DEFINER RPC",sourceTrust:"accepted fact plus source, not World verification",targetKey:null,transformation:"Map only individually proven component keys",status:"AMBIGUOUS",informationLoss:"summary may overstate complete accessibility",conflictRisk:"HIGH",verificationRequired:true,engineEligibility:"POSSIBLE_AFTER_POLICY",recommendation:"ADAPT"}),
  row({sourceSystem:"gold-authoring",location:"backyrd_spot_sources_v1",field:"source_type/reference/retrieved_at/observed_at/checked_at",legacyType:"text/jsonb/timestamptz",meaning:"Evidence and provenance candidate",writeAuthority:"admin/research/import",sourceTrust:"source metadata only",targetKey:null,transformation:"Adapt to Source Reference; do not infer verification",status:"NORMALIZED",informationLoss:"actor/source labels partially conflated",conflictRisk:"MEDIUM",verificationRequired:false,engineEligibility:"PROHIBITED",recommendation:"EXTEND"}),
  row({sourceSystem:"gold-authoring",location:"backyrd_spot_fact_proposals_v1",field:"proposal_hash/supersedes/status",legacyType:"text/uuid/enum",meaning:"Proposal lineage and workflow",writeAuthority:"admin/research/owner",sourceTrust:"proposal-level audit",targetKey:null,transformation:"Preserve as migration evidence; create new World claims",status:"NORMALIZED",informationLoss:"workflow statuses differ",conflictRisk:"MEDIUM",verificationRequired:true,engineEligibility:"PROHIBITED",recommendation:"ADAPT"}),
  row({sourceSystem:"spot-intelligence",location:"public.spot_intelligence_v1",field:"best_for/occasion_tags/atmosphere_tags",legacyType:"text[]",meaning:"Subjective suitability and mood descriptors",writeAuthority:"admin/owner/import/enrichment",sourceTrust:"row-level is_verified",targetKey:"research.subjective_fits",transformation:"Research/explanation only",status:"SUBJECTIVE",informationLoss:"subject and context absent",conflictRisk:"HIGH",verificationRequired:false,engineEligibility:"EXPLANATION_ONLY",recommendation:"DO_NOT_MIGRATE"}),
  row({sourceSystem:"n4",location:"backyrd_spot_suitability_facts_v1",field:"value/confidence",legacyType:"jsonb/numeric",meaning:"Derived suitability plus numeric N4 confidence",writeAuthority:"system derivation",sourceTrust:"mapping lineage, not World evidence",targetKey:null,transformation:"Do not convert suitability or numeric confidence",status:"UNSUPPORTED",informationLoss:"cannot preserve intent-free objective meaning",conflictRisk:"HIGH",verificationRequired:true,engineEligibility:"PROHIBITED",recommendation:"DO_NOT_MIGRATE"}),
  ...["owner_id","owner_tier","subscription","payment","advertising","sponsorship"].map((field) => row({sourceSystem:"commercial-owner",location:"spots/owner platform",field,legacyType:"mixed",meaning:"Ownership or commercial context",writeAuthority:"owner/billing/admin",sourceTrust:"not factual trust",targetKey:null,transformation:"Exclude",status:"PROHIBITED",informationLoss:"intentional boundary",conflictRisk:"LOW",verificationRequired:false,engineEligibility:"PROHIBITED",recommendation:"DO_NOT_MIGRATE"})),
  row({sourceSystem:"events",location:"events and spot relation",field:"spot_id",legacyType:"uuid",meaning:"Event occurs at a spot",writeAuthority:"event/admin flows",sourceTrust:"separate event domain",targetKey:null,transformation:"Retain relation outside World claims",status:"NO_TARGET_KEY",informationLoss:"none",conflictRisk:"LOW",verificationRequired:false,engineEligibility:"PROHIBITED",recommendation:"KEEP"}),
]);
export const LEGACY_MAPPING_HASH = sha256({ version: LEGACY_MAPPING_VERSION, rows: LEGACY_MAPPING_MATRIX });
