import { hashBody, sha256 } from "./canonical.js";
import { CLAIM_CONTRACT_VERSION, RESOLUTION_CONTRACT_VERSION, WORLD_KNOWLEDGE_PORT_VERSION, createClaim, type ClaimValue, type WorldKnowledgeClaim } from "./contracts.js";
import { LEGACY_MAPPING_HASH, LEGACY_MAPPING_VERSION } from "./legacy-mapping.js";
import { buildWorldKnowledgeSnapshot, parseBuildWorldKnowledgeInput, parseWorldKnowledgeSnapshot, type PortKnowledgeEntry, type WorldKnowledgeSnapshot } from "./port.js";
import { PRIMARY_CATEGORIES, REGISTRY_HASH, REGISTRY_VERSION, type PrimaryCategory } from "./registry.js";
import { resolveWorldKnowledge } from "./resolver.js";
import { array, ContractValidationError, identifier, number, object, required, string, timestamp } from "./schema.js";
import { UNCONFIGURED_SOURCE_POLICY } from "./source-policy.js";

export const LEGACY_ADAPTER_VERSION = "backyrd.world-knowledge.legacy-adapter@1.0" as const;
export interface LegacySpotInput { readonly spotId: string; readonly observedAt: string; readonly sourceReferenceId: string | null; readonly name: string | null; readonly address: string | null; readonly city: string | null; readonly country: string | null; readonly latitude: number | null; readonly longitude: number | null; readonly timezone: string | null; readonly categoryName: string | null; readonly website: string | null; readonly phone: string | null; readonly hours: readonly { readonly day: string; readonly open: string; readonly close: string }[]; readonly facts: Readonly<Record<string, unknown>>; readonly commercialContext: Readonly<Record<string, unknown>> }
export interface LegacyAdapterResult { readonly adapterVersion: typeof LEGACY_ADAPTER_VERSION; readonly registryVersion: typeof REGISTRY_VERSION; readonly registryHash: string; readonly mappingVersion: typeof LEGACY_MAPPING_VERSION; readonly mappingHash: string; readonly inputHash: string; readonly claims: readonly WorldKnowledgeClaim[]; readonly audit: readonly { readonly legacyField: string; readonly outcome: "MAPPED" | "REQUIRES_REVIEW" | "EXCLUDED"; readonly targetKey: string | null; readonly reasonCode: string }[]; readonly snapshot: WorldKnowledgeSnapshot; readonly resultHash: string }

const categoryMap: Readonly<Record<string, PrimaryCategory>> = Object.freeze({ restaurant:"EAT", eat:"EAT", bar:"DRINKS", drinks:"DRINKS", cafe:"COFFEE_DAYTIME", café:"COFFEE_DAYTIME", nightlife:"NIGHTLIFE", museum:"CULTURE_ARTS", culture:"CULTURE_ARTS", entertainment:"ENTERTAINMENT", activity:"ACTIVITIES_PLAY", sport:"SPORT_MOVEMENT", outdoor:"OUTDOOR_NATURE", wellness:"WELLNESS_RELAXATION", shopping:"SHOPPING_MARKETS", hotel:"STAY", stay:"STAY", community:"COMMUNITY_SOCIAL", attraction:"ATTRACTIONS_LANDMARKS", temporary:"TEMPORARY_PLACES", other:"OTHER", sonstiges:"OTHER" });
const timePattern = /^(?:[01]\d|2[0-3]):[0-5]\d$/; const dayMap: Readonly<Record<string,string>> = Object.freeze({monday:"MONDAY",tuesday:"TUESDAY",wednesday:"WEDNESDAY",thursday:"THURSDAY",friday:"FRIDAY",saturday:"SATURDAY",sunday:"SUNDAY",montag:"MONDAY",dienstag:"TUESDAY",mittwoch:"WEDNESDAY",donnerstag:"THURSDAY",freitag:"FRIDAY",samstag:"SATURDAY",sonntag:"SUNDAY"});

export function parseLegacySpotInput(value: unknown): LegacySpotInput {
  const input = object(value, "$", ["spotId","observedAt","sourceReferenceId","name","address","city","country","latitude","longitude","timezone","categoryName","website","phone","hours","facts","commercialContext"]); const nullableText = (key:string,max=500) => { const raw=required(input,key); return raw===null?null:string(raw,`$.${key}`,{min:1,max}); }; const source=nullableText("sourceReferenceId",180); if(source && !source.startsWith("source:")) throw new ContractValidationError("$.sourceReferenceId","expected source namespace");
  const nullableNumber=(key:string,min:number,max:number)=>{const raw=required(input,key);return raw===null?null:number(raw,`$.${key}`,{min,max});};
  const hours=array(required(input,"hours"),"$.hours").map((value,index)=>{const path=`$.hours[${index}]`;const row=object(value,path,["day","open","close"]);return{day:string(required(row,"day",path),`${path}.day`,{min:1,max:20}),open:string(required(row,"open",path),`${path}.open`,{min:1,max:8}),close:string(required(row,"close",path),`${path}.close`,{min:1,max:8})};});
  return {spotId:identifier(required(input,"spotId"),"$.spotId"),observedAt:timestamp(required(input,"observedAt"),"$.observedAt"),sourceReferenceId:source,name:nullableText("name",160),address:nullableText("address",240),city:nullableText("city",120),country:nullableText("country",80),latitude:nullableNumber("latitude",-90,90),longitude:nullableNumber("longitude",-180,180),timezone:nullableText("timezone",80),categoryName:nullableText("categoryName",100),website:nullableText("website"),phone:nullableText("phone",40),hours,facts:object(required(input,"facts"),"$.facts"),commercialContext:object(required(input,"commercialContext"),"$.commercialContext")};
}

export function adaptLegacySpot(value: unknown): LegacyAdapterResult {
  const input=parseLegacySpotInput(value); const inputHash=sha256(input); const claims:WorldKnowledgeClaim[]=[]; const audit:LegacyAdapterResult["audit"][number][]=[]; let sequence=0;
  const add=(legacyField:string,targetKey:string,value:ClaimValue,state:"KNOWN_VALUE"|"KNOWN_TRUE"|"KNOWN_FALSE"="KNOWN_VALUE")=>{sequence+=1;claims.push(createClaim({claimId:`adapter:${inputHash.slice(0,20)}:${String(sequence).padStart(3,"0")}`,attributeKey:targetKey,scope:{spotId:input.spotId,area:"SPOT"},knowledgeState:state,value,actorType:"SYSTEM",sourceType:"LEGACY_IMPORT",sourceReferenceId:input.sourceReferenceId,provenanceSessionId:`adapter:${inputHash.slice(0,20)}`,verificationState:"UNVERIFIED",observedAt:input.observedAt,validFrom:null,validUntil:null,stance:"SUPPORTS",visibility:"INTERNAL",supersedesClaimId:null}));audit.push({legacyField,outcome:"MAPPED",targetKey,reasonCode:input.sourceReferenceId?"LEGACY_SOURCE_BOUND_NOT_VERIFIED":"MISSING_PROVENANCE_ASSERTED_ONLY"});};
  for(const [legacy,key,value] of [["name","identity.name",input.name],["address","location.address_line1",input.address],["city","location.locality",input.city],["latitude","location.latitude",input.latitude],["longitude","location.longitude",input.longitude],["timezone","location.timezone",input.timezone],["website","contact.website",input.website],["phone","contact.phone",input.phone]] as const) if(value!==null){try{add(legacy,key,value);}catch{audit.push({legacyField:legacy,outcome:"REQUIRES_REVIEW",targetKey:key,reasonCode:"REGISTRY_VALUE_INVALID"});}}
  if(input.country!==null){const normalized=input.country.trim().toUpperCase();if(/^[A-Z]{2}$/.test(normalized))add("country","location.country_code",normalized);else audit.push({legacyField:"country",outcome:"REQUIRES_REVIEW",targetKey:"location.country_code",reasonCode:"COUNTRY_NOT_ISO_ALPHA_2"});}
  if(input.categoryName!==null){const mapped=categoryMap[input.categoryName.trim().toLocaleLowerCase("de-CH")];if(mapped&&PRIMARY_CATEGORIES.includes(mapped))add("categoryName","classification.primary_category",mapped);else audit.push({legacyField:"categoryName",outcome:"REQUIRES_REVIEW",targetKey:"classification.primary_category",reasonCode:"CATEGORY_MAPPING_AMBIGUOUS"});}
  if(input.hours.length){const schedule=[] as {day:string;intervals:{start:string;end:string}[]}[];let valid=true;for(const row of input.hours){const day=dayMap[row.day.toLocaleLowerCase("de-CH")];if(!day||!timePattern.test(row.open)||!timePattern.test(row.close)||row.open===row.close){valid=false;break;}const existing=schedule.find((item)=>item.day===day);if(existing)existing.intervals.push({start:row.open,end:row.close});else schedule.push({day,intervals:[{start:row.open,end:row.close}]});}if(valid&&input.timezone)add("hours","hours.regular",schedule as ClaimValue);else audit.push({legacyField:"hours",outcome:"REQUIRES_REVIEW",targetKey:"hours.regular",reasonCode:valid?"TIMEZONE_MISSING":"OPENING_HOURS_INVALID"});}
  for(const key of Object.keys(input.facts).sort()) audit.push({legacyField:`facts.${key}`,outcome:"REQUIRES_REVIEW",targetKey:null,reasonCode:"NO_SAFE_ALLOWLISTED_TRANSFORMATION"});
  for(const key of Object.keys(input.commercialContext).sort()) audit.push({legacyField:`commercialContext.${key}`,outcome:"EXCLUDED",targetKey:null,reasonCode:"COMMERCIAL_OR_OWNER_CONTEXT_PROHIBITED"});
  const resolution=resolveWorldKnowledge({contractVersion:RESOLUTION_CONTRACT_VERSION,registryVersion:REGISTRY_VERSION,asOf:input.observedAt,claims,sourcePolicy:UNCONFIGURED_SOURCE_POLICY,verificationRecords:[]}); const snapshot=buildWorldKnowledgeSnapshot(parseBuildWorldKnowledgeInput({contractVersion:WORLD_KNOWLEDGE_PORT_VERSION,spotId:input.spotId,resolution}));
  const body={adapterVersion:LEGACY_ADAPTER_VERSION,registryVersion:REGISTRY_VERSION,registryHash:REGISTRY_HASH,mappingVersion:LEGACY_MAPPING_VERSION,mappingHash:LEGACY_MAPPING_HASH,inputHash,claims,audit:audit.sort((a,b)=>`${a.legacyField}:${a.outcome}`.localeCompare(`${b.legacyField}:${b.outcome}`)),snapshot}; return {...body,resultHash:hashBody(body,[])};
}

const decisionUseCase = (key:string) => key.startsWith("hours.") || key === "state.current" ? "OPENING_HOURS_ELIGIBILITY" : key === "operation.price_range" || key === "operation.price_level" ? "PRICE" : key.startsWith("accessibility.") ? "ACCESSIBILITY" : ["operation.takeaway","rule.reservation","rule.external_food","rule.external_drink"].includes(key) ? "HARD_CONSTRAINTS" : "DISCOVERY";
const decisionEntries = (entries:readonly PortKnowledgeEntry[]) => entries.filter((entry)=>entry.authorizedUseCases.includes(decisionUseCase(entry.key)));
export function projectForDecision(snapshotValue: unknown, acceptedPolicies: readonly {readonly policyVersion:string;readonly policyHash:string}[] = [UNCONFIGURED_SOURCE_POLICY]) {
  const snapshot=parseWorldKnowledgeSnapshot(snapshotValue,acceptedPolicies); const structural=new Map(snapshot.structuralAuthorizations.map((item)=>[item.key,item])); const allowed=(key:string)=>structural.get(key)?.authorizedUseCases.includes("DISCOVERY")===true;
  const body={contractVersion:"backyrd.world-knowledge.decision-projection@1.0",snapshotHash:snapshot.snapshotHash,sourcePolicyVersion:snapshot.sourcePolicyVersion,sourcePolicyHash:snapshot.sourcePolicyHash,spotId:snapshot.spot.spotId,classification:{primaryCategory:allowed("classification.primary_category")?snapshot.spot.classification.primaryCategory:null,placeTypes:allowed("classification.place_types")?snapshot.spot.classification.placeTypes:[]},facts:decisionEntries(snapshot.facts),operationalRules:decisionEntries(snapshot.operationalRules),currentStates:decisionEntries(snapshot.currentStates),capabilities:[],conflicts:snapshot.conflicts,explicitUnknowns:snapshot.explicitUnknowns,readiness:snapshot.readiness};return{...body,projectionHash:hashBody(body,[])};
}

export function profileLegacySpots(values: readonly unknown[]) { const parsed=values.map(parseLegacySpotInput); return {totalSpots:parsed.length,coverage:{name:parsed.filter(v=>v.name).length,address:parsed.filter(v=>v.address).length,coordinates:parsed.filter(v=>v.latitude!==null&&v.longitude!==null).length,timezone:parsed.filter(v=>v.timezone).length,category:parsed.filter(v=>v.categoryName).length,hours:parsed.filter(v=>v.hours.length).length,sourceReference:parsed.filter(v=>v.sourceReferenceId).length},invalidHours:parsed.filter(v=>v.hours.some(h=>!dayMap[h.day.toLocaleLowerCase("de-CH")]||!timePattern.test(h.open)||!timePattern.test(h.close)||h.open===h.close)).length,ambiguousCategories:parsed.filter(v=>v.categoryName!==null&&!categoryMap[v.categoryName.trim().toLocaleLowerCase("de-CH")]).length}; }
