"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { HUMAN_ACCESSIBILITY_LABELS, HUMAN_CONTEXT_LABELS, HUMAN_OBJECT_FIELD_LABELS, HUMAN_SPOT_FIELDS, HUMAN_SPOT_SECTIONS, HUMAN_VALUE_LABELS } from "@backyrd/canonical-semantics";
import { getOwnerGoldProfile, submitOwnerGoldProposal, type OwnerGoldProfile } from "@/lib/owner-api";

type Field = OwnerGoldProfile["catalog"][number];
const SECTIONS = ["ACTIVITY_DETAILS", "SUITABILITY", "AUDIENCE_SOCIAL"];
const SCOPES = [["SPOT", "Gilt allgemein für den Ort"], ["EVENT", "Nur für ein Event"], ["PROGRAM", "Nur für ein Angebot"], ["TEMPORARY", "Nur vorübergehend"]] as const;
function config(key:string){return HUMAN_SPOT_FIELDS[key as keyof typeof HUMAN_SPOT_FIELDS]??{question:key};}
function label(value:unknown):string{if(value==null)return"Noch nicht bekannt";if(Array.isArray(value))return value.map(label).join(", ")||"Keine Auswahl";if(typeof value==="object")return Object.entries(value).map(([key,item])=>`${HUMAN_CONTEXT_LABELS[key as keyof typeof HUMAN_CONTEXT_LABELS]??HUMAN_ACCESSIBILITY_LABELS[key as keyof typeof HUMAN_ACCESSIBILITY_LABELS]??HUMAN_OBJECT_FIELD_LABELS[key as keyof typeof HUMAN_OBJECT_FIELD_LABELS]??"Angabe"}: ${label(item)}`).join(" · ");const key=String(value);if(key==="SUITABLE")return"Ja / gut geeignet";if(key==="NOT_SUITABLE")return"Nein / eher nicht";if(key==="true")return"Ja";if(key==="false")return"Nein";return HUMAN_VALUE_LABELS[key as keyof typeof HUMAN_VALUE_LABELS]??key.replaceAll("_"," ").toLocaleLowerCase("de-CH");}
function initial(field:Field):unknown{if(field.field_key==="suitability.age")return{min_age:null,max_age:null,adult_supervision_required:"UNKNOWN"};if(field.field_key==="social.suitability")return Object.fromEntries(Object.keys(HUMAN_CONTEXT_LABELS).map((key)=>[key,"UNKNOWN"]));if(field.field_key==="accessibility.capabilities")return Object.fromEntries(Object.keys(HUMAN_ACCESSIBILITY_LABELS).map((key)=>[key,"UNKNOWN"]));if(field.value_kind==="MULTI_SELECT")return[];if(["RANGE","STRUCTURED_OBJECT"].includes(field.value_kind))return{};return"";}

function Control({field,value,onChange,disabled}:{field:Field;value:unknown;onChange:(value:unknown)=>void;disabled:boolean}){
  const meta=config(field.field_key);const labels="labels" in meta?meta.labels:undefined;
  if(field.field_key==="suitability.age"){const age=(value&&typeof value==="object"?value:{}) as Record<string,unknown>;const supervision=age.adult_supervision_required===true?"YES":age.adult_supervision_required===false?"NO":String(age.adult_supervision_required??"UNKNOWN");return <div className="grid gap-2 md:grid-cols-3"><input disabled={disabled} type="number" min="0" max="120" placeholder="Ab Alter" value={String(age.min_age??"")} onChange={(e)=>onChange({...age,min_age:e.target.value===""?null:Number(e.target.value)})}/><input disabled={disabled} type="number" min="0" max="120" placeholder="Bis Alter" value={String(age.max_age??"")} onChange={(e)=>onChange({...age,max_age:e.target.value===""?null:Number(e.target.value)})}/><select disabled={disabled} value={supervision} onChange={(e)=>onChange({...age,adult_supervision_required:e.target.value==="YES"?true:e.target.value==="NO"?false:"UNKNOWN"})}><option value="UNKNOWN">Begleitung unbekannt</option><option value="YES">Begleitung nötig</option><option value="NO">Keine Begleitung nötig</option></select></div>}
  if(["social.suitability","accessibility.capabilities"].includes(field.field_key)){const current=(value&&typeof value==="object"?value:{}) as Record<string,unknown>;const items=field.field_key==="social.suitability"?HUMAN_CONTEXT_LABELS:HUMAN_ACCESSIBILITY_LABELS;return <div className="grid gap-2 md:grid-cols-2">{Object.entries(items).map(([key,text])=><label key={key} className="text-xs text-white/55">{text}<select disabled={disabled} value={String(current[key]??"UNKNOWN")} onChange={(e)=>onChange({...current,[key]:e.target.value})}><option value="UNKNOWN">Weiß ich nicht</option><option value="SUITABLE">Ja / gut geeignet</option><option value="NOT_SUITABLE">Nein / eher nicht</option></select></label>)}</div>}
  if(field.field_key==="duration.approximate"){const range=(value&&typeof value==="object"?value:{}) as Record<string,unknown>;return <div className="grid gap-2 md:grid-cols-2"><input disabled={disabled} type="number" min="0" placeholder="Mindestens (Minuten)" value={String(range.min??"")} onChange={(e)=>onChange({...range,min:e.target.value===""?null:Number(e.target.value)})}/><input disabled={disabled} type="number" min="0" placeholder="Höchstens (Minuten)" value={String(range.max??"")} onChange={(e)=>onChange({...range,max:e.target.value===""?null:Number(e.target.value)})}/></div>}
  if(field.value_kind==="ENUM")return <select disabled={disabled} value={String(value??"")} onChange={(e)=>onChange(e.target.value)}><option value="">Bitte auswählen</option>{field.allowed_values.map((item)=><option key={String(item)} value={String(item)}>{labels?.[String(item) as keyof typeof labels]??label(item)}</option>)}</select>;
  if(field.value_kind==="MULTI_SELECT"&&field.allowed_values.length){const selected=Array.isArray(value)?value:[];return <div className="flex flex-wrap gap-2">{field.allowed_values.map((item)=><label key={String(item)} className={`rounded-full border px-3 py-2 text-xs ${selected.includes(item)?"border-pink-400 bg-pink-400/10":"border-white/10"}`}><input className="mr-2" disabled={disabled} type="checkbox" checked={selected.includes(item)} onChange={(e)=>onChange(e.target.checked?[...selected,item]:selected.filter((entry)=>entry!==item))}/>{label(item)}</label>)}</div>}
  return <textarea disabled={disabled} rows={3} value={typeof value==="string"?value:JSON.stringify(value??"",null,2)} onChange={(e)=>onChange(e.target.value)}/>;
}

export function OwnerGoldAuthoring({spotId}:{spotId:string}){
  const[profile,setProfile]=useState<OwnerGoldProfile|null>(null);const[drafts,setDrafts]=useState<Record<string,unknown>>({});const[sourceUrl,setSourceUrl]=useState("");const[sourceReference,setSourceReference]=useState("");const[scope,setScope]=useState<"SPOT"|"EVENT"|"PROGRAM"|"TEMPORARY">("SPOT");const[busy,setBusy]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);
  const load=useCallback(async()=>setProfile(await getOwnerGoldProfile(spotId)),[spotId]);useEffect(()=>{void getOwnerGoldProfile(spotId).then(setProfile).catch((error:unknown)=>setMessage(error instanceof Error?error.message:"Spot-Verständnis konnte nicht geladen werden."));},[spotId]);
  const accepted=useMemo(()=>new Map((profile?.acceptedFacts??[]).map((fact)=>[fact.field_key,fact])),[profile]);
  async function submit(field:Field){setBusy(field.field_key);setMessage(null);try{await submitOwnerGoldProposal({spotId,fieldKey:field.field_key,value:drafts[field.field_key]??accepted.get(field.field_key)?.value??initial(field),sourceUrl:sourceUrl.trim()||null,sourceReference:sourceReference.trim()||null,evidenceScope:scope});setMessage("Danke. Deine Angabe wurde mit Quelle zur Prüfung gespeichert.");await load();}catch(error){setMessage(error instanceof Error?error.message:"Angabe konnte nicht gespeichert werden.");}finally{setBusy(null)}}
  if(!profile)return <section className="rounded-[2rem] border border-white/10 bg-white/[0.04] p-6">{message??"Backyrd-Verständnis wird geladen …"}</section>;
  const isPro=profile.actor.capability==="DEEP";
  return <section className="rounded-[2rem] border border-white/10 bg-white/[0.04] p-6"><header className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-semibold">Erkläre Backyrd deinen Spot</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/50">Je genauer diese Angaben sind, desto besser kann Backyrd erkennen, wann dein Spot zu einer Suche passt. „Weiß ich nicht“ ist völlig in Ordnung.</p></div><span className="rounded-full border border-white/10 px-4 py-2 text-sm">Owner {profile.actor.ownerTier}</span></header>{message&&<p role="status" className="mt-4 rounded-2xl border border-white/10 p-4 text-sm">{message}</p>}
    <div className="mt-6 grid gap-4 rounded-3xl border border-white/10 bg-black/20 p-5 md:grid-cols-3"><label className="text-sm">Woher stammt die Information?<select className="mt-2 w-full" value={sourceUrl?"OFFICIAL_WEBSITE":"OWNER_CLAIM"} onChange={(e)=>{if(e.target.value==="OWNER_CLAIM")setSourceUrl("");else setSourceReference("")}}><option value="OWNER_CLAIM">Betreiberangabe / eigene Kenntnis</option><option value="OFFICIAL_WEBSITE">Offizielle Website</option></select></label><label className="text-sm">Website oder Referenz<input className="mt-2 w-full" value={sourceUrl||sourceReference} onChange={(e)=>{if(e.target.value.startsWith("http")){setSourceUrl(e.target.value);setSourceReference("")}else{setSourceReference(e.target.value);setSourceUrl("")}}} placeholder="https://… oder kurze Referenz"/></label><label className="text-sm">Gültigkeit<select className="mt-2 w-full" value={scope} onChange={(e)=>setScope(e.target.value as typeof scope)}>{SCOPES.map(([key,text])=><option key={key} value={key}>{text}</option>)}</select></label></div>
    {SECTIONS.map((sectionKey)=>{const section=HUMAN_SPOT_SECTIONS.find((item)=>item.key===sectionKey);const fields=profile.catalog.filter((field)=>field.section===sectionKey&&config(field.field_key).question!==field.field_key);if(!fields.length)return null;return <div key={sectionKey} className="mt-7"><h3 className="text-lg font-semibold">{section?.label}</h3><p className="mt-1 text-sm text-white/40">{section?.description}</p><div className="mt-4 grid gap-3">{fields.map((field)=>{const current=accepted.get(field.field_key);const locked=field.capability==="DEEP"&&!isPro;const meta=config(field.field_key);return <article key={field.field_key} className="grid gap-5 rounded-3xl border border-white/10 bg-black/20 p-5 md:grid-cols-[minmax(220px,.7fr)_1.3fr]"><div><h4 className="font-semibold">{meta.question}</h4>{"help" in meta&&meta.help&&<p className="mt-2 text-xs leading-5 text-white/40">{meta.help}</p>}<p className="mt-3 text-xs text-white/55">{current?`Aktuell bestätigt: ${label(current.value)}`:"Noch nicht bestätigt"}</p>{locked&&<p className="mt-3 rounded-2xl bg-pink-400/10 p-3 text-xs leading-5 text-pink-100">Mit Owner Pro kannst du Backyrd deinen Spot noch genauer erklären. Bestehende bestätigte Angaben bleiben erhalten.</p>}</div><div className="grid gap-3 [&_input]:rounded-xl [&_input]:border [&_input]:border-white/10 [&_input]:bg-black/30 [&_input]:p-3 [&_select]:rounded-xl [&_select]:border [&_select]:border-white/10 [&_select]:bg-black/30 [&_select]:p-3 [&_textarea]:rounded-xl [&_textarea]:border [&_textarea]:border-white/10 [&_textarea]:bg-black/30 [&_textarea]:p-3"><Control field={field} value={drafts[field.field_key]??current?.value??initial(field)} onChange={(value)=>setDrafts((state)=>({...state,[field.field_key]:value}))} disabled={locked}/>{!locked&&<button type="button" disabled={busy!==null} onClick={()=>void submit(field)} className="justify-self-start rounded-full bg-white px-5 py-2.5 text-sm font-semibold text-black disabled:opacity-50">{busy===field.field_key?"Wird gespeichert …":"Zur Prüfung speichern"}</button>}</div></article>})}</div></div>})}
    <div className="mt-8 grid gap-5 md:grid-cols-2"><div><h3 className="font-semibold">Was noch offen ist</h3><ul className="mt-3 space-y-2 text-sm text-white/55">{profile.readiness.gaps.map((gap)=><li key={`${gap.state}:${gap.item}`}>{gap.state==="UNKNOWN"?"○":"!"} {gap.label??gap.item}{gap.detail&&<small className="block pl-5 text-white/35">{gap.detail}</small>}</li>)}</ul></div><div><h3 className="font-semibold">Bereits bestätigt</h3><ul className="mt-3 space-y-2 text-sm text-white/55">{profile.acceptedFacts.map((fact)=><li key={fact.id}>✓ {config(fact.field_key).question}: {label(fact.value)}</li>)}</ul></div></div>
  </section>;
}
