"use client";

import { useMemo, useRef, useState, type Dispatch, type SetStateAction } from "react";
import { analysisReport, catalog, deriveFits, engineSnapshot, resolveKnowledge, type CatalogDefinition, type ClaimStatus, type Evidence, type PrototypeState, type Role } from "@/lib/world-knowledge/model";
import { isUnlocked } from "./world-knowledge-prototype";

export const guidedSteps = [
  { id: "basics", label: "Grundinformationen", title: "Philipps Casa erfassen", help: "Trage die wichtigsten Informationen, Kontaktangaben, Küche, Bezahlung und Öffnungszeiten an einem Ort ein." },
  { id: "place-type", label: "Art des Ortes", title: "Was für ein Ort ist Philipps Casa?", help: "Mehrere Begriffe sind möglich. Wähle nur aus, was den Ort wirklich beschreibt." },
  { id: "intents", label: "Wofür eignet sich der Ort?", title: "Wofür würden Menschen Philipps Casa wählen?", help: "Ordne typische Besuche und Anlässe aus Sicht der Gäste ein." },
  { id: "capabilities", label: "Was kann man dort machen?", title: "Was ist bei Philipps Casa möglich?", help: "Die Möglichkeiten sind nach Essen, praktischem Besuch und gemeinsamen Aktivitäten geordnet." },
  { id: "situation", label: "Atmosphäre und Situation", title: "Wann und für wen passt Philipps Casa?", help: "Wähle passende Situationen. Direkte Eindrücke und spätere Ableitungen bleiben technisch getrennt." },
  { id: "amenities", label: "Ausstattung und Einschränkungen", title: "Was sollten Gäste vorher wissen?", help: "Ausstattung und mögliche Einschränkungen sind thematisch sortiert. Dieser Bereich ist vollständig optional." },
  { id: "review", label: "Vorschau und Analyse", title: "So könnte Philipps Casa in der App aussehen", help: "Die Vorschau zeigt live, wie deine Angaben später für Gäste verständlich werden könnten. Speichere den Stand oder starte die Analyse." },
] as const;

export type GuidedStepId = (typeof guidedSteps)[number]["id"];

const labelTranslations: Record<string, string> = {
  African: "Afrikanisch", Asian: "Asiatisch", Chinese: "Chinesisch", French: "Französisch", Fusion: "Fusion-Küche", Indian: "Indisch", Italian: "Italienisch", Japanese: "Japanisch", Korean: "Koreanisch", "Latin American": "Lateinamerikanisch", Mediterranean: "Mediterran", Mexican: "Mexikanisch", "Middle Eastern": "Nahöstlich", Seafood: "Fisch und Meeresfrüchte", Swiss: "Schweizerisch", Thai: "Thailändisch", Vietnamese: "Vietnamesisch",
  Bakery: "Bäckerei", "Breakfast Spot": "Frühstückslokal", "Brunch Spot": "Brunch-Lokal", "Dessert Shop": "Dessert-Lokal", "Food Court": "Food-Court", "Food Hall": "Food-Hall", "Supper Club": "Supper Club", "Vegan Restaurant": "Veganes Restaurant", "Vegetarian Restaurant": "Vegetarisches Restaurant",
  "Casual Dining": "Lockeres Restaurant", "Farm-to-Table": "Regionale Hofküche", "Fast Casual": "Schnelle Qualitätsküche", "Fine Dining": "Gehobene Küche", "Ice Cream": "Glace", "Pop-up Dining": "Pop-up-Gastronomie", "Street Food": "Street Food", Takeaway: "Take-away",
  "Alcohol-free drinks": "Alkoholfreie Getränke", Beer: "Bier", Breakfast: "Frühstück", Brunch: "Brunch", Coffee: "Kaffee", Delivery: "Lieferung", Dinner: "Abendessen", "Full meal": "Vollständige Mahlzeit", "Group dining": "Gemeinsam essen", Lunch: "Mittagessen", "Outdoor dining": "Draußen essen", "Private dining": "Privater Essbereich", "Quick meal": "Schnell etwas essen", "Sharing food": "Gerichte teilen", Snacks: "Snacks", Tea: "Tee", Wine: "Wein",
  "Booking required": "Buchung erforderlich", "Child-friendly": "Kinderfreundlich", "Covered outdoor": "Überdachter Außenbereich", "Dog-friendly": "Hundefreundlich", "Indoor seating": "Innenplätze", "Laptop-friendly": "Laptopfreundlich", "Large-group suitable": "Für große Gruppen geeignet", "Late-night capable": "Bis spät geöffnet", "Outdoor seating": "Außenplätze", "Queue likely": "Wartezeit möglich", "Rain-safe": "Bei Regen geeignet", "Reservation possible": "Reservation möglich", "Solo-friendly": "Gut alleine besuchbar", "Ticket required": "Ticket erforderlich", "Walk-in possible": "Spontaner Besuch möglich", "Wheelchair accessible": "Rollstuhlgängig", "Work-friendly": "Zum Arbeiten geeignet",
  Business: "Geschäftlicher Anlass", "Business meeting": "Geschäftliches Treffen", Celebration: "Feier", "Feier / Celebration": "Feier", "Geburtstag / Celebration": "Geburtstag oder Feier", "Community gathering": "Community-Treffen", "Family outing": "Familienausflug", "Group gathering": "Gruppentreffen", "Meet friends": "Freunde treffen", "Meet new people": "Neue Leute kennenlernen", Networking: "Netzwerken", "Business Meeting": "Geschäftliches Treffen", "Members only": "Nur für Mitglieder", "Security Check": "Sicherheitskontrolle", "Deposit/Vorauszahlung": "Anzahlung / Vorauszahlung", "No-show Fee": "Gebühr bei Nichterscheinen", "Outdoor-only": "Nur Außenbereich",
};

const familyTranslations: Record<string, string> = {
  "Food & Drink": "Essen und Trinken", "Practical Visit Capabilities": "Praktisch beim Besuch", Social: "Gemeinsam und sozial", "Decision Intents": "Besuch und Anlass",
  "Budget Situation": "Budget", "Companion Fit": "Begleitung", "Group Size Fit": "Gruppengröße", "Occasion Fit": "Anlass", "Planning Fit": "Planung", "Time Fit": "Tageszeit", "Visit Length Fit": "Dauer", "Weather Fit": "Wetter",
  "Amenities / Accessibility": "Barrierefreiheit", "Amenities / Comfort & Facilities": "Komfort und Infrastruktur", "Amenities / Family": "Familie", "Amenities / Outdoor": "Außenbereiche", "Amenities / Pets": "Tiere", "Amenities / Service & Payment": "Service und Bezahlung", "Amenities / Transport": "Anreise",
  "Constraints / Age & Entry": "Alter und Einlass", "Constraints / Booking": "Buchung", "Constraints / Food & Consumption": "Essen und Konsumation", "Constraints / Operational Constraints": "Betriebliche Einschränkungen", "Constraints / Physical Restrictions": "Räumliche Einschränkungen", Subcategories: "Passende Auswahl",
};

export function guidedLabel(definition: CatalogDefinition) { return labelTranslations[definition.label] ?? definition.label; }

function evidenceFor(role: Role): Evidence {
  const today = new Date().toISOString().slice(0, 10);
  return { sourceType: role === "ADMIN" ? "ADMIN_OBSERVATION" : "OWNER_CLAIM", sourceName: role === "ADMIN" ? "Geführte Admin-Erfassung" : "Philipps Casa · verifizierter Owner", observedAt: today, validFrom: today, validUntil: "", verificationState: role === "ADMIN" ? "UNVERIFIED" : "PENDING", reference: "Automatisch aus der geführten Erfassung angelegt.", stance: "SUPPORTS", privateReference: false };
}

function definitionsFor(step: GuidedStepId, state: PrototypeState) {
  const categories = new Set([state.spot.primaryCategory, ...state.spot.secondaryCategories]);
  return catalog.definitions.filter((item) => {
    if (!item.applicableCategories.some((key) => categories.has(key))) return false;
    if (step === "place-type") return item.semanticClass === "SUBCATEGORY";
    if (step === "intents") return item.semanticClass === "DECISION_INTENT";
    if (step === "capabilities") return item.semanticClass === "CAPABILITY";
    if (step === "situation") return item.semanticClass === "DIRECT_FIT";
    if (step === "amenities") return item.group === "AMENITIES_CONSTRAINTS" || item.group === "CHARACTERISTICS";
    return false;
  });
}

function selectedIds(state: PrototypeState) { return new Set(resolveKnowledge(state).filter((item) => item.status === "KNOWN_TRUE" || item.status === "KNOWN_VALUE").map((item) => item.definition.id)); }
function activeClaim(state: PrototypeState, definitionId: string) {
  const retracted = new Set(state.claims.filter((claim) => claim.operation === "RETRACT").map((claim) => claim.supersedesClaimId));
  return [...state.claims].reverse().find((claim) => claim.definitionId === definitionId && claim.operation !== "RETRACT" && !retracted.has(claim.id));
}
function appendGuidedClaim(state: PrototypeState, definition: CatalogDefinition, role: Role, status?: ClaimStatus) {
  const previous = activeClaim(state, definition.id); const claims = [...state.claims]; const createdAt = new Date().toISOString();
  if (previous) claims.push({ id: crypto.randomUUID(), definitionId: definition.id, status: "UNKNOWN", value: null, actor: role, createdAt, evidence: evidenceFor(role), operation: "RETRACT", supersedesClaimId: previous.id });
  if (status) claims.push({ id: crypto.randomUUID(), definitionId: definition.id, status, value: status === "KNOWN_TRUE" ? true : status === "KNOWN_FALSE" ? false : null, actor: role, createdAt, evidence: evidenceFor(role), operation: "ASSERT" });
  return claims;
}

const priority: Record<string, string[]> = {
  "place-type": ["Restaurant", "Brasserie", "Bistro", "Café", "Cafe", "Pub", "Imbiss", "Take Away", "Fast-Food", "Bar", "Bakery"],
  intents: ["Frühstücken", "Brunchen", "Mittagessen", "Abendessen", "Date", "Freunde treffen", "Familienzeit", "Business", "Geburtstag / Celebration"],
  capabilities: ["Breakfast", "Brunch", "Lunch", "Dinner", "Coffee", "Tea", "Wine", "Full meal", "Quick meal", "Group gathering", "Work-friendly"],
  situation: ["Date", "Freunde", "Familie", "Alleine", "Kleine Gruppe", "Große Gruppe", "Ruhig", "Gemütlich", "Lebhaft", "Arbeiten"],
  amenities: ["WLAN", "Steckdosen", "Terrasse", "überdachte Außenplätze", "Rollstuhl-WC", "Hochstuhl", "Reservation online", "stufenloser Zugang"],
};

export function GuidedWorkflow({ state, setState, role, onSave, onAnalyze, onOpenExpert }: { state: PrototypeState; setState: Dispatch<SetStateAction<PrototypeState>>; role: Role; onSave(): void; onAnalyze(): void; onOpenExpert(): void }) {
  const [step, setStep] = useState<GuidedStepId>("basics"); const headingRef = useRef<HTMLHeadingElement>(null); const currentIndex = guidedSteps.findIndex((item) => item.id === step); const current = guidedSteps[currentIndex]; const selected = useMemo(() => selectedIds(state), [state]);
  const navigate = (next: GuidedStepId) => { setState((value) => ({ ...value, guidedProgress: { ...value.guidedProgress, visitedSteps: [...new Set([...value.guidedProgress.visitedSteps, next])] } })); setStep(next); requestAnimationFrame(() => headingRef.current?.focus()); };
  const skip = () => { setState((value) => ({ ...value, guidedProgress: { ...value.guidedProgress, skippedSteps: [...new Set([...value.guidedProgress.skippedSteps, step])] } })); if (currentIndex < guidedSteps.length - 1) navigate(guidedSteps[currentIndex + 1].id); };
  const next = () => currentIndex < guidedSteps.length - 1 ? navigate(guidedSteps[currentIndex + 1].id) : onAnalyze();
  const toggle = (definition: CatalogDefinition) => { if (!isUnlocked(definition, role)) return; setState((currentState) => ({ ...currentState, claims: appendGuidedClaim(currentState, definition, role, selected.has(definition.id) ? undefined : "KNOWN_TRUE") })); };
  return <div className="wk-guide-layout"><aside className="wk-guide-steps" aria-label="Schritte der Spot-Erfassung"><div className="wk-guide-progress"><span>Spot-Erfassung</span><strong>Schritt {currentIndex + 1} von {guidedSteps.length}</strong><i><b style={{ width: `${((currentIndex + 1) / guidedSteps.length) * 100}%` }} /></i></div><nav>{guidedSteps.map((item, index) => { const count = item.id === "basics" || item.id === "review" ? 0 : definitionsFor(item.id, state).filter((definition) => selected.has(definition.id)).length; const skipped = state.guidedProgress.skippedSteps.includes(item.id); const visited = state.guidedProgress.visitedSteps.includes(item.id); const basicsComplete = Boolean(state.spot.name && state.spot.address && state.spot.city && state.spot.primaryCategory); const summary = item.id === "basics" ? (basicsComplete ? "Grundinformationen vollständig" : "Notwendige Angaben prüfen") : item.id === "review" ? "Live-Vorschau ansehen" : count ? `${count} ${count === 1 ? "Angabe" : "Angaben"} ausgewählt` : skipped ? "Später ausfüllen" : visited ? "Noch nichts ausgewählt" : "Noch nicht bearbeitet"; return <button type="button" key={item.id} data-active={step === item.id} onClick={() => navigate(item.id)}><span>{index + 1}</span><div><strong>{item.label}</strong><small>{summary}</small></div></button>; })}</nav><button className="wk-open-expert" type="button" onClick={onOpenExpert}>Erweiterte Angaben und Quellen <span>→</span></button></aside>
    <main className="wk-guide-main"><div className="wk-guide-intro"><div><span className="wk-kicker">PHILIPPS CASA BESCHREIBEN</span><h1 ref={headingRef} tabIndex={-1}>{current.title}</h1><p>{current.help}</p></div><div className="wk-guide-reminder"><strong>Du musst nicht alles ausfüllen.</strong><span>Wähle nur aus, was wirklich auf den Spot zutrifft. Alles andere kann offenbleiben.</span></div></div>{step === "basics" && <Basics state={state} setState={setState} role={role} selected={selected} onToggle={toggle} />}{(["place-type", "intents", "capabilities", "situation", "amenities"] as GuidedStepId[]).includes(step) && <SelectionStep step={step} state={state} role={role} selected={selected} onToggle={toggle} />}{step === "review" && <Review state={state} onSave={onSave} onAnalyze={onAnalyze} onOpenExpert={onOpenExpert} />}<footer className="wk-guide-actions"><button type="button" className="wk-guide-secondary" onClick={skip} disabled={step === "review"}>Später ausfüllen</button><span>Deine bisherigen Angaben bleiben erhalten.</span><button type="button" className="wk-guide-next" onClick={next}>{step === "review" ? "Analyse starten" : "Weiter"} <span>→</span></button></footer></main></div>;
}

const cuisineChoices = ["Swiss", "Italian", "French", "Mediterranean", "Asian", "Japanese", "Burger", "Pizza", "Vegetarian Restaurant", "Vegan Restaurant"];
const offeringChoices = ["Casual Dining", "Fine Dining", "Fast Casual", "Farm-to-Table", "Street Food", "Buffet", "Patisserie"];
const paymentChoices = ["Bargeld", "Kartenzahlung", "Mobile Payment", "Rechnung möglich"];

function Basics({ state, setState, role, selected, onToggle }: { state: PrototypeState; setState: Dispatch<SetStateAction<PrototypeState>>; role: Role; selected: Set<string>; onToggle(definition: CatalogDefinition): void }) {
  const patchSpot = (patch: Partial<PrototypeState["spot"]>) => setState((current) => ({ ...current, spot: { ...current.spot, ...patch } })); const relevant = catalog.definitions.filter((item) => item.applicableCategories.includes(state.spot.primaryCategory));
  const cuisines = relevant.filter((item) => item.semanticClass === "CUISINE" && cuisineChoices.includes(item.label)); const offerings = relevant.filter((item) => item.semanticClass === "OFFERING" && offeringChoices.includes(item.label)); const payments = relevant.filter((item) => paymentChoices.includes(item.label)); const takeawayDefinition = relevant.find((item) => item.semanticClass === "CAPABILITY" && item.label === "Takeaway");
  const setTakeaway = (value: PrototypeState["spot"]["takeaway"]) => setState((current) => ({ ...current, spot: { ...current.spot, takeaway: value }, claims: takeawayDefinition ? appendGuidedClaim(current, takeawayDefinition, role, value === "YES" ? "KNOWN_TRUE" : value === "NO" ? "KNOWN_FALSE" : undefined) : current.claims }));
  return <section className="wk-guide-card wk-basics-stack"><BasicSection title="Spot und Adresse" help="Diese vier Angaben bilden den notwendigen Grundrahmen."><div className="wk-friendly-fields"><label><span>Name <em>notwendig</em></span><input value={state.spot.name} onChange={(event) => patchSpot({ name: event.target.value })} /></label><label><span>Hauptkategorie <em>notwendig</em></span><select value={state.spot.primaryCategory} onChange={(event) => patchSpot({ primaryCategory: event.target.value })}>{catalog.categories.map((item) => <option value={item.key} key={item.key}>{item.label}</option>)}</select></label><label className="wide"><span>Adresse <em>notwendig</em></span><input value={state.spot.address} onChange={(event) => patchSpot({ address: event.target.value })} /></label><label><span>Ort <em>notwendig</em></span><input value={state.spot.city} onChange={(event) => patchSpot({ city: event.target.value })} /></label><label><span>Quartier</span><input value={state.spot.neighborhood} onChange={(event) => patchSpot({ neighborhood: event.target.value })} placeholder="z. B. Kreis 4" /></label></div>{state.spot.secondaryCategories.length > 0 && <p className="wk-preserved-note">Frühere Zusatzkategorien bleiben intern erhalten und können unter „Erweiterte Angaben“ geprüft werden.</p>}</BasicSection>
    <BasicSection title="Kontakt und Kanäle" help="Nur öffentliche Angaben eintragen, die Gäste verwenden dürfen."><div className="wk-friendly-fields"><label><span>Webseite</span><input type="url" value={state.spot.website} onChange={(event) => patchSpot({ website: event.target.value })} placeholder="https://…" /></label><label><span>Telefonnummer</span><input type="tel" value={state.spot.phone} onChange={(event) => patchSpot({ phone: event.target.value })} placeholder="+41 …" /></label><label><span>Instagram</span><input value={state.spot.instagram} onChange={(event) => patchSpot({ instagram: event.target.value })} placeholder="@philipps.casa" /></label><label><span>Facebook</span><input value={state.spot.facebook} onChange={(event) => patchSpot({ facebook: event.target.value })} /></label><label><span>LinkedIn</span><input value={state.spot.linkedin} onChange={(event) => patchSpot({ linkedin: event.target.value })} /></label><label><span>TikTok</span><input value={state.spot.tiktok} onChange={(event) => patchSpot({ tiktok: event.target.value })} placeholder="@philipps.casa" /></label></div></BasicSection>
    <BasicSection title="Profil, Küche und Bezahlung" help="Wähle nur passende Angaben. Nicht ausgewählte Einträge sind keine Lücken."><div className="wk-friendly-fields"><label className="wide"><span>Besonderheit</span><textarea value={state.spot.specialFeature} onChange={(event) => patchSpot({ specialFeature: event.target.value })} placeholder="Was macht Philipps Casa besonders?" rows={3} /></label><label><span>Preislevel</span><select value={state.spot.priceLevel} onChange={(event) => patchSpot({ priceLevel: event.target.value })}><option value="">Noch nicht angegeben</option><option value="$">$ · günstig</option><option value="$$">$$ · mittel</option><option value="$$$">$$$ · gehoben</option><option value="$$$$">$$$$ · exklusiv</option></select></label><fieldset className="wk-inline-radios"><legend>Take-away</legend>{[["YES", "Ja"], ["NO", "Nein"], ["UNKNOWN", "Noch offen"]].map(([value, label]) => <label key={value}><input type="radio" name="takeaway" checked={state.spot.takeaway === value} onChange={() => setTakeaway(value as PrototypeState["spot"]["takeaway"])} />{label}</label>)}</fieldset></div><CompactPicker title="Art der Küche" definitions={cuisines} selected={selected} role={role} onToggle={onToggle} /><CompactPicker title="Angebot und Stil" definitions={offerings} selected={selected} role={role} onToggle={onToggle} /><CompactPicker title="Bezahlarten" definitions={payments} selected={selected} role={role} onToggle={onToggle} /></BasicSection>
    <BasicSection title="Öffnungszeiten" help="Reguläre Zeiten, Sondertage und der heutige Status gehören direkt zu den Grundinformationen."><FriendlyHours state={state} setState={setState} /></BasicSection></section>;
}

function BasicSection({ title, help, children }: { title: string; help: string; children: React.ReactNode }) { return <section className="wk-basic-section"><div className="wk-basic-heading"><h2>{title}</h2><p>{help}</p></div>{children}</section>; }
function CompactPicker({ title, definitions, selected, role, onToggle }: { title: string; definitions: CatalogDefinition[]; selected: Set<string>; role: Role; onToggle(definition: CatalogDefinition): void }) { if (!definitions.length) return null; return <div className="wk-compact-picker"><h3>{title}</h3><div>{definitions.map((definition) => <button type="button" key={definition.id} aria-pressed={selected.has(definition.id)} data-selected={selected.has(definition.id)} disabled={!isUnlocked(definition, role)} onClick={() => onToggle(definition)}>{selected.has(definition.id) && <span aria-hidden="true">✓</span>}{guidedLabel(definition)}</button>)}</div></div>; }

function SelectionStep({ step, state, role, selected, onToggle }: { step: GuidedStepId; state: PrototypeState; role: Role; selected: Set<string>; onToggle(definition: CatalogDefinition): void }) {
  const [search, setSearch] = useState(""); const [expanded, setExpanded] = useState(false); const all = useMemo(() => definitionsFor(step, state), [step, state]);
  const ordered = useMemo(() => [...all].sort((a, b) => { const labels = priority[step] ?? []; const ai = labels.indexOf(a.label); const bi = labels.indexOf(b.label); return (ai < 0 ? 999 : ai) - (bi < 0 ? 999 : bi) || guidedLabel(a).localeCompare(guidedLabel(b), "de"); }), [all, step]);
  const matching = ordered.filter((item) => !search || `${guidedLabel(item)} ${familyTranslations[item.family] ?? item.family}`.toLocaleLowerCase("de").includes(search.toLocaleLowerCase("de"))); const shown = matching.slice(0, expanded || search ? 250 : step === "place-type" ? 16 : 18); const selectedDefinitions = all.filter((item) => selected.has(item.id)); const clusters = Object.entries(shown.reduce<Record<string, CatalogDefinition[]>>((groups, item) => { const key = familyTranslations[item.family] ?? item.family; groups[key] = [...(groups[key] ?? []), item]; return groups; }, {}));
  return <section className="wk-guide-card"><div className="wk-picker-toolbar"><label><span>In diesem Bereich suchen</span><input type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Begriff eingeben …" /></label>{selectedDefinitions.length > 0 && <div className="wk-selected-summary"><span>Ausgewählt</span><strong>{selectedDefinitions.length}</strong></div>}</div>{selectedDefinitions.length > 0 && <div className="wk-selected-chips">{selectedDefinitions.map((item) => <button type="button" key={item.id} onClick={() => onToggle(item)}>{guidedLabel(item)}<span aria-hidden="true">×</span><span className="sr-only"> entfernen</span></button>)}</div>}<div className="wk-cluster-list">{clusters.map(([title, definitions]) => <OptionGroup title={title} definitions={definitions} selected={selected} role={role} onToggle={onToggle} key={title} />)}</div>{!shown.length && <div className="wk-guide-empty">Keine passende Option gefunden. Im erweiterten Bereich bleibt der vollständige Katalog verfügbar.</div>}{!expanded && !search && ordered.length > shown.length && <button type="button" className="wk-show-more" onClick={() => setExpanded(true)}>Alle {ordered.length} Möglichkeiten anzeigen</button>}{expanded && !search && ordered.length > 18 && <button type="button" className="wk-show-more" onClick={() => setExpanded(false)}>Auf häufige Möglichkeiten reduzieren</button>}<p className="wk-picker-footnote">Nicht ausgewählt bedeutet hier nur: keine Aussage gemacht. Es bedeutet nicht „trifft nicht zu“.</p></section>;
}

function OptionGroup({ title, definitions, selected, role, onToggle }: { title: string; definitions: CatalogDefinition[]; selected: Set<string>; role: Role; onToggle(item: CatalogDefinition): void }) { return <section className="wk-option-group"><h2>{title}</h2><div className="wk-option-grid">{definitions.map((item) => { const active = selected.has(item.id); const unlocked = isUnlocked(item, role); return <button type="button" aria-pressed={active} disabled={!unlocked} data-selected={active} key={item.id} onClick={() => onToggle(item)}><span className="wk-checkmark" aria-hidden="true">{active ? "✓" : ""}</span><strong>{guidedLabel(item)}</strong>{!unlocked && <small>{item.ownerAccess === "PRO" ? "Zusätzlicher Owner-Bereich (Entwurf)" : "Nur im Admin-Bereich bearbeitbar"}</small>}</button>; })}</div></section>; }

function FriendlyHours({ state, setState }: { state: PrototypeState; setState: Dispatch<SetStateAction<PrototypeState>> }) {
  const updateDay = (index: number, patch: Partial<PrototypeState["schedule"][number]>) => setState((current) => ({ ...current, schedule: current.schedule.map((day, i) => i === index ? { ...day, ...patch } : day) })); const addException = () => setState((current) => ({ ...current, exceptions: [...current.exceptions, { id: crypto.randomUUID(), date: "", state: "CLOSED", note: "" }] })); const updateException = (id: string, patch: Partial<PrototypeState["exceptions"][number]>) => setState((current) => ({ ...current, exceptions: current.exceptions.map((item) => item.id === id ? { ...item, ...patch } : item) }));
  return <div className="wk-friendly-hours"><div className="wk-hours-heading"><strong>Reguläre Woche</strong><span>{state.spot.timezone}</span></div>{state.schedule.map((item, index) => <div className="wk-hours-row" key={item.day}><label><input type="checkbox" checked={item.enabled} onChange={(event) => updateDay(index, { enabled: event.target.checked })} />{item.day}</label>{item.enabled ? <><input aria-label={`${item.day} öffnet`} type="time" value={item.open} onChange={(event) => updateDay(index, { open: event.target.value })} /><span>bis</span><input aria-label={`${item.day} schließt`} type="time" value={item.close} onChange={(event) => updateDay(index, { close: event.target.value })} /></> : <span className="wk-closed">Geschlossen</span>}</div>)}<div className="wk-exceptions"><div className="wk-hours-heading"><div><strong>Sonderöffnungszeiten</strong><small>Zum Beispiel Weihnachten, 1. August oder Neujahr.</small></div><button type="button" onClick={addException}>Sondertag hinzufügen</button></div>{state.exceptions.map((item) => <div className="wk-exception-row" key={item.id}><input aria-label="Datum des Sondertags" type="date" value={item.date} onChange={(event) => updateException(item.id, { date: event.target.value })} /><input aria-label="Name des Sondertags" value={item.note} onChange={(event) => updateException(item.id, { note: event.target.value })} placeholder="z. B. Neujahr" /><select aria-label="Status am Sondertag" value={item.state} onChange={(event) => updateException(item.id, { state: event.target.value })}><option value="CLOSED">Geschlossen</option><option value="OPEN">Sonderöffnungszeiten</option></select>{item.state === "OPEN" && <><input aria-label="Öffnet am Sondertag" type="time" value={item.open ?? ""} onChange={(event) => updateException(item.id, { open: event.target.value })} /><input aria-label="Schließt am Sondertag" type="time" value={item.close ?? ""} onChange={(event) => updateException(item.id, { close: event.target.value })} /></>}<button type="button" aria-label="Sondertag entfernen" onClick={() => setState((current) => ({ ...current, exceptions: current.exceptions.filter((entry) => entry.id !== item.id) }))}>×</button></div>)}</div><div className="wk-today-state"><div><strong>Was gilt heute?</strong><span>Nur setzen, wenn der aktuelle Betrieb vom normalen Wochenplan abweicht.</span></div><select aria-label="Heutiger Status" value={state.currentState.service} onChange={(event) => setState((current) => ({ ...current, currentState: { ...current.currentState, service: event.target.value } }))}><option value="NORMAL">Es gilt der normale Wochenplan</option><option value="LIMITED">Heute nur eingeschränkter Betrieb</option><option value="PAUSED">Der Betrieb ist vorübergehend pausiert</option><option value="CLOSED">Heute geschlossen</option></select></div></div>;
}

function Review({ state, onSave, onAnalyze, onOpenExpert }: { state: PrototypeState; onSave(): void; onAnalyze(): void; onOpenExpert(): void }) {
  const resolved = resolveKnowledge(state); const derived = deriveFits(resolved); const positive = resolved.filter((item) => item.status === "KNOWN_TRUE" || item.status === "KNOWN_VALUE"); const byClass = (semanticClass: string) => positive.filter((item) => item.definition.semanticClass === semanticClass).map((item) => guidedLabel(item.definition)); const types = byClass("SUBCATEGORY"); const cuisines = [...byClass("CUISINE"), ...byClass("OFFERING")]; const capabilities = byClass("CAPABILITY"); const fits = byClass("DIRECT_FIT"); const amenities = positive.filter((item) => item.definition.group === "AMENITIES_CONSTRAINTS" || item.definition.group === "CHARACTERISTICS").map((item) => guidedLabel(item.definition));
  return <section className="wk-review-v3"><div className="wk-preview-copy"><span className="wk-kicker">LIVE-VORSCHAU</span><h2>Deine Angaben werden zu einer verständlichen Spotseite.</h2><p>Die Darstellung ist eine grobe Produktvorschau. Sie zeigt, welche Informationen Gäste tatsächlich sehen könnten – nicht das technische Datenmodell dahinter.</p><div className="wk-preview-checks"><div><strong>{state.spot.name && state.spot.address && state.spot.city ? "✓" : "○"} Grundprofil</strong><span>{state.spot.name && state.spot.address && state.spot.city ? "Name und Adresse sind bereit." : "Name, Adresse oder Ort fehlen noch."}</span></div><div><strong>{types.length ? "✓" : "○"} Art des Ortes</strong><span>{types.length ? types.join(" · ") : "Noch offengelassen – das ist in Ordnung."}</span></div><div><strong>{positive.length} hilfreiche Angaben</strong><span>Optionale Angaben werden nicht als Fehler gewertet.</span></div>{derived.length > 0 && <div><strong>{derived.length} nachvollziehbare Ableitung(en)</strong><span>{derived.map((item) => item.label).join(" · ")}</span></div>}</div><div className="wk-review-actions"><button type="button" onClick={onSave}>Zwischenstand speichern</button><button type="button" onClick={onAnalyze}>Analyse starten →</button></div><button type="button" className="wk-review-expert" onClick={onOpenExpert}>Quellen und technische Vorschau öffnen</button></div><MobileSpotPreview state={state} types={types} cuisines={cuisines} capabilities={capabilities} fits={fits} amenities={amenities} /></section>;
}

function MobileSpotPreview({ state, types, cuisines, capabilities, fits, amenities }: { state: PrototypeState; types: string[]; cuisines: string[]; capabilities: string[]; fits: string[]; amenities: string[] }) {
  const today = state.schedule.find((item) => item.enabled); const highlights = amenities.slice(0, 3); const offer = [...cuisines, ...capabilities].slice(0, 3); const line = (items: string[], fallback: string) => items.length ? items.join(" · ") : fallback;
  return <div className="wk-phone" aria-label="Mobile Vorschau der Spotseite"><div className="wk-phone-screen"><div className="wk-phone-hero"><div className="wk-phone-toolbar"><span>‹</span><div><span>↗</span><span>♡</span></div></div><div className="wk-phone-placeholder"><b>PC</b><small>Vorschaubild noch offen</small></div><div className="wk-phone-title"><div><span className="wk-open-dot">● {state.currentState.service === "CLOSED" ? "Geschlossen" : "Geöffnet"}</span>{state.spot.priceLevel && <span>{state.spot.priceLevel}</span>}</div><h3>{state.spot.name || "Name des Spots"}</h3><p>{state.spot.address || "Adresse"}, {state.spot.city || "Ort"}{state.spot.neighborhood ? ` · ${state.spot.neighborhood}` : ""}</p></div></div><div className="wk-phone-body"><div className="wk-phone-actions"><button type="button">⌁ Route</button><button type="button">＋ Moment</button></div><section className="wk-spot-profile"><small>SPOT PROFIL</small><h4>Das erwartet dich</h4><PreviewRow label="Was für ein Ort?" value={line(types, "Noch keine Ortsart ausgewählt")} /><PreviewRow label="Besonders hier" value={state.spot.specialFeature || line(highlights, "Noch keine Besonderheit ergänzt")} /><PreviewRow label="Angebot" value={line(offer, "Noch kein Angebot ausgewählt")} /></section>{highlights.length > 0 && <section className="wk-phone-section"><h4><i /> Eigenschaften</h4><div className="wk-phone-chips">{highlights.map((item) => <span key={item}>{item} <b>✓</b></span>)}</div></section>}{fits.length > 0 && <section className="wk-phone-section"><h4><i /> So fühlt es sich hier an</h4><div className="wk-phone-chips">{fits.slice(0, 5).map((item) => <span key={item}>{item}</span>)}</div></section>}<section className="wk-phone-section"><h4><i /> Über diesen Spot</h4><p>{state.spot.specialFeature || "Hier könnte eine kurze Beschreibung von Philipps Casa stehen."}</p></section><section className="wk-phone-section wk-phone-info"><h4><i /> Info</h4><p>⌖ <span>{state.spot.address || "Adresse"}, {state.spot.city || "Ort"}</span></p>{state.spot.phone && <p>⌕ <span>{state.spot.phone}</span></p>}{state.spot.website && <p>◎ <span>{state.spot.website}</span></p>}</section><section className="wk-phone-section"><h4><i /> Heute</h4><div className="wk-today-card"><span>{today?.day ?? "Keine Zeiten"}</span><strong>{today ? `${today.open}–${today.close}` : "Noch offen"}</strong></div></section></div></div></div>;
}
function PreviewRow({ label, value }: { label: string; value: string }) { return <div className="wk-preview-row"><span>◇</span><div><small>{label}</small><strong>{value}</strong></div></div>; }

export function FriendlyAnalysis({ state, onOpenExpert }: { state: PrototypeState; onOpenExpert(): void }) {
  const report = analysisReport(state); const resolved = resolveKnowledge(state); const snapshot = engineSnapshot(state); const useful = resolved.filter((item) => item.status === "KNOWN_TRUE" || item.status === "KNOWN_VALUE").slice(0, 12); const conflicts = resolved.filter((item) => item.status === "DISPUTED"); const expired = resolved.filter((item) => item.status === "EXPIRED"); const suggestions = [resolved.some((item) => item.definition.semanticClass === "SUBCATEGORY") ? null : "Art des Ortes ergänzen", resolved.some((item) => item.definition.semanticClass === "CAPABILITY") ? null : "Mindestens eine konkrete Möglichkeit ergänzen", resolved.some((item) => item.definition.group === "AMENITIES_CONSTRAINTS") ? null : "Hilfreiche Ausstattung ergänzen"].filter(Boolean) as string[];
  return <main className="wk-friendly-analysis"><div className="wk-analysis-hero"><span>ANALYSE ABGESCHLOSSEN</span><h1>Das weiß Backyrd über {state.spot.name}.</h1><p>Optionale Angaben bleiben optional. Die Hinweise zeigen nur, welche Ergänzungen spätere Empfehlungen noch genauer machen könnten.</p></div><div className="wk-analysis-summary"><div><span>Hauptkategorie</span><strong>{catalog.categories.find((item) => item.key === state.spot.primaryCategory)?.label}</strong></div><div><span>Ausdrückliche Angaben</span><strong>{resolved.length}</strong></div><div><span>Nachvollziehbare Ableitungen</span><strong>{deriveFits(resolved).length}</strong></div></div><section><h2>Das ist bereits besonders nützlich</h2>{useful.length ? <div className="wk-friendly-tags">{useful.map((item) => <span key={item.definition.id}>{guidedLabel(item.definition)}</span>)}</div> : <p>Noch keine inhaltlichen Angaben ausgewählt. Der Spot bleibt trotzdem gültig gespeichert.</p>}</section><section><h2>Hilfreiche Ergänzungen</h2>{suggestions.length ? <ul>{suggestions.map((item) => <li key={item}>{item}</li>)}</ul> : <p>Für den ersten Teststand sind die wichtigsten Bereiche abgedeckt.</p>}</section><div className="wk-analysis-alerts"><section><h2>Widersprüche</h2><p>{conflicts.length ? conflicts.map((item) => guidedLabel(item.definition)).join(" · ") : "Keine Widersprüche erkannt."}</p></section><section><h2>Möglicherweise veraltet</h2><p>{expired.length ? expired.map((item) => guidedLabel(item.definition)).join(" · ") : "Keine abgelaufenen Angaben erkannt."}</p></section></div><section className="wk-engine-readable"><div><h2>So wird der Spot aktuell übergeben</h2><p>{snapshot.facts.length} aufgelöste Fakten, {snapshot.directFits.length} direkt angegebene Fits und {snapshot.derivedFits.length} abgeleitete Fits. Keine Abo-, Payment- oder privaten Quelldaten.</p></div><button type="button" onClick={onOpenExpert}>Technische Vorschau öffnen →</button></section><details><summary>Vollständige menschliche Analyse anzeigen</summary><pre>{JSON.stringify(report, null, 2)}</pre></details></main>;
}
