export type NodeType="subcategory"|"feature"|"offering"|"service";
export type Row={id:string;slug:string;node_type:NodeType;parent_id:string|null;parent_label:string|null;label_de:string;label_en:string;icon:string|null;color:string|null;sort_order:number;is_active:boolean;is_owner_selectable:boolean;is_system:boolean;ml_weight:number;category_ids:string[];category_names:string[];synonyms_count:number;spots_count:number;updated_at:string};
export type Category={id:string;name:string;icon:string|null;color:string|null};
export type Synonym={id?:string;locale:"de"|"en";synonym:string;weight:number};
export type Form={id:string|null;slug:string;node_type:NodeType;parent_id:string;icon:string;color:string;sort_order:string;is_active:boolean;is_owner_selectable:boolean;is_system:boolean;ml_weight:string;label_de:string;short_label_de:string;description_de:string;label_en:string;short_label_en:string;description_en:string;category_ids:string[];synonyms:Synonym[]};
export const labels:Record<NodeType,string>={subcategory:"Unterkategorie",feature:"Feature",offering:"Angebot",service:"Service"};
export const empty:Form={id:null,slug:"",node_type:"feature",parent_id:"",icon:"",color:"",sort_order:"0",is_active:true,is_owner_selectable:true,is_system:false,ml_weight:"1.00",label_de:"",short_label_de:"",description_de:"",label_en:"",short_label_en:"",description_en:"",category_ids:[],synonyms:[]};
export function slugify(v:string){return v.trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ä/g,"ae").replace(/ö/g,"oe").replace(/ü/g,"ue").replace(/ß/g,"ss").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")}
export function toForm(d:any):Form{return{id:d.id,slug:d.slug,node_type:d.node_type,parent_id:d.parent_id??"",icon:d.icon??"",color:d.color??"",sort_order:String(d.sort_order??0),is_active:d.is_active,is_owner_selectable:d.is_owner_selectable,is_system:d.is_system,ml_weight:String(d.ml_weight??1),label_de:d.label_de??"",short_label_de:d.short_label_de??"",description_de:d.description_de??"",label_en:d.label_en??"",short_label_en:d.short_label_en??"",description_en:d.description_en??"",category_ids:d.category_ids??[],synonyms:(d.synonyms??[]).map((s:any)=>({...s,weight:Number(s.weight??1)}))}}
