import assert from "node:assert/strict";
import test from "node:test";
import { buildCurrentMoment } from "../../../decision-lab/src/n3-moment-intelligence.mjs";
import { buildMomentAwareRelevantUserProjection } from "../../../decision-lab/src/n5-6-1-moment-aware-projection.mjs";
import { buildDecisionInputPackage,buildProductCurrentMoment,buildProductProjection,mapProductDecisionToN3Input,validateDecisionInputPackage } from "../src/index.mjs";

const node=(concept,scope,affinity=.7,confidence=.82)=>({nodeKey:`${scope.kind}:${scope.key}:${concept}`,concept,scope,affinity,polarity:affinity>0?"POSITIVE":"NEGATIVE",knowledgeState:affinity>0?"POSITIVE":"NEGATIVE",confidence,evidenceDepth:{independentSessions:5,independentSpots:4,outcomes:4},evidenceComposition:{comparative:4},evidenceRefs:["basel:spot:private"],contradictions:[],trend:{direction:"STABLE"}});
const card=(userId)=>({version:"backyrd-n5-6-user-card-v1",userId,userCardHash:`${userId}`.padEnd(64,"a").slice(0,64),maturity:{state:"KNOWN"},occasionPatterns:[],nodes:[node("vibe.lively",{kind:"CONTEXT",key:"audience.friends"}),node("vibe.romantic",{kind:"CONTEXT",key:"audience.date"}),node("discovery.hidden_gem",{kind:"GLOBAL",key:"global"}),node("place_type.bar",{kind:"PLACE_TYPE",key:"bar"})]});
const source=(overrides={})=>({
  decision:{id:"11111111-1111-4111-8111-111111111111",userId:"22222222-2222-4222-8222-222222222222",city:"Basel",moodA:null,moodB:null,createdAt:"2026-08-21T18:30:00.000Z"},
  requestContext:{query:"Drinks mit Freunden",rawFreeText:"Drinks mit Freunden",preferredPlaceTypes:["bar"],audience:["friends"],strictCategoryIntent:true,model_version:"decision-v13.0"},
  userCard:card("22222222-2222-4222-8222-222222222222"),memoryConsentState:"granted",
  candidates:[
    {spotId:"33333333-3333-4333-8333-333333333333",retrievalPosition:1,status:"approved",city:"Basel",category:"Bar",productPlaceType:"bar",openNow:true,distributionEligible:true},
    {spotId:"44444444-4444-4444-8444-444444444444",retrievalPosition:2,status:"approved",city:"Basel",category:"Bar",productPlaceType:"bar",openNow:null,distributionEligible:true},
  ],
  n4BySpot:{"33333333-3333-4333-8333-333333333333":{available:true,placeType:"bar",snapshotIdentity:"n4-rich",freshness:"2026-08-20T00:00:00.000Z",concepts:{"vibe.lively":{presence:.9,confidence:.88,provenance:{evidenceId:"n4-e1"}}}}},
  ...overrides,
});

test("Product N3 V2 preserves the frozen Lab N3 as its semantic base",()=>{const value=source();const mapped=mapProductDecisionToN3Input(value);assert.deepEqual(buildProductCurrentMoment(value).frozenResult,buildCurrentMoment(mapped));});
test("N3 golden Product mappings remain the frozen Lab runtime across canonical moments",()=>{
  const cases=[
    {query:"Friday drinks with friends",audience:["friends"],preferredPlaceTypes:["bar"]},
    {query:"Solo afterwork",audience:["solo"],preferredPlaceTypes:["bar"]},
    {query:"Date evening",audience:["date"],selectedMoods:["romantisch"]},
    {query:"Family Sunday",audience:["family"]},
    {query:"Was soll ich machen?"},
    {query:"ruhig, damit wir reden können",audience:["friends"],selectedMoods:["ruhig"]},
    {query:"Drinks",preferredPlaceTypes:["bar"]},
    {query:"Friends",audience:["friends"]},
    {query:"allein",audience:["friends"]},
    {query:"new city drinks",preferredPlaceTypes:["bar"],city:"Copenhagen"},
  ];
  for(const fixture of cases){const value=source({decision:{...source().decision,city:fixture.city??"Basel"},requestContext:{model_version:"decision-v13.0",...fixture}});assert.deepEqual(buildProductCurrentMoment(value).frozenResult,buildCurrentMoment(mapProductDecisionToN3Input(value)));}
});
test("N3 preserves missing fields and resolves guided conflict by explicit authority",()=>{const value=source({requestContext:{query:"allein",audience:["friends"],preferredPlaceTypes:[]}});const moment=buildProductCurrentMoment(value).result.currentMoment;assert.equal(moment.fields.social_context.value,"friends");assert.ok(moment.contradictions.some((row)=>row.dimension==="social_context"));assert.ok(moment.unknownFields.includes("budget_orientation"));});
test("Product N5 is the frozen Lab projection and Friends differs from Date",()=>{const friends=source();const fm=buildProductCurrentMoment(friends).result.currentMoment;const fp=buildProductProjection({userCard:friends.userCard,currentMoment:fm,requestContext:friends.requestContext});assert.deepEqual(fp.raw,buildMomentAwareRelevantUserProjection({userCard:friends.userCard,currentMoment:fm,currentIntent:fp.currentIntent}));const date=source({requestContext:{query:"romantisches Date",audience:["date"],preferredPlaceTypes:["bar"]}});const dm=buildProductCurrentMoment(date).result.currentMoment;const dp=buildProductProjection({userCard:date.userCard,currentMoment:dm,requestContext:date.requestContext});assert.notDeepEqual(fp.projection.taste.map(x=>x.concept),dp.projection.taste.map(x=>x.concept));});
test("explicit quiet intent suppresses historical lively preference",()=>{const value=source({requestContext:{query:"ruhig, damit wir reden können",rawFreeText:"ruhig, damit wir reden können",preferredPlaceTypes:["bar"],audience:["friends"],strictCategoryIntent:true}});const result=buildDecisionInputPackage(value);assert.equal(result.package.n5.taste.some((row)=>row.concept==="vibe.lively"),false);assert.ok(result.n5.raw.projectionAudit.nodes.some((row)=>row.concept==="vibe.lively"&&row.reasonCode==="CURRENT_INTENT_CONFLICT"));});
test("cold user and broad request remain honest",()=>{const cold=buildDecisionInputPackage(source({userCard:null,requestContext:{query:"Drinks mit Freunden",audience:["friends"],preferredPlaceTypes:["bar"],strictCategoryIntent:true}}));assert.equal(cold.package.n5.knowledgeMode,"LOW_OR_UNKNOWN");assert.equal(cold.package.n5.taste.length,0);const broad=buildDecisionInputPackage(source({requestContext:{query:"Was soll ich machen?",preferredPlaceTypes:[],audience:[]}}));assert.equal(broad.package.n5.knowledgeMode,"LOW_OR_UNKNOWN");assert.ok(broad.package.n5.taste.length<=1);});
test("hard eligibility freezes only approved, distributed, city/category-compatible candidates",()=>{const value=source();value.candidates.push({spotId:"55555555-5555-4555-8555-555555555555",retrievalPosition:3,status:"pending",city:"Basel",category:"Bar",productPlaceType:"bar",openNow:true,distributionEligible:true});value.candidates.push({spotId:"66666666-6666-4666-8666-666666666666",retrievalPosition:4,status:"approved",city:"Copenhagen",category:"Bar",productPlaceType:"bar",openNow:true,distributionEligible:true});const result=buildDecisionInputPackage(value);assert.deepEqual(result.package.candidates.map(x=>x.spotId),[value.candidates[0].spotId,value.candidates[1].spotId]);assert.equal(result.eligibilityAudit.filter(x=>!x.eligible).length,2);});
test("explicit open-now treats closed and unknown availability as hard exclusions",()=>{const value=source({requestContext:{...source().requestContext,openNow:true}});value.candidates[0].openNow=true;value.candidates[1].openNow=null;value.candidates.push({spotId:"77777777-7777-4777-8777-777777777777",retrievalPosition:3,status:"approved",city:"Basel",category:"Bar",productPlaceType:"bar",openNow:false,distributionEligible:true});const result=buildDecisionInputPackage(value);assert.deepEqual(result.package.candidates.map(x=>x.spotId),[value.candidates[0].spotId]);assert.deepEqual(result.eligibilityAudit.filter(x=>!x.eligible).map(x=>x.reasons[0]).sort(),["CLOSED_NOW","OPENING_STATUS_UNKNOWN"]);});
test("explicit open-now may freeze an honest empty candidate set",()=>{const value=source({requestContext:{...source().requestContext,openNow:true},candidates:source().candidates.map((row)=>({...row,openNow:null}))});const result=buildDecisionInputPackage(value);assert.equal(result.package.candidateSet.count,0);assert.equal(validateDecisionInputPackage(result.package,{expectedUserId:result.package.userId}).valid,true);});
test("free-text family inference stays soft while explicit Product categories stay hard",()=>{const broad=source({requestContext:{query:"Regnerischer Tag mit meiner 4 jährigen Tochter",rawFreeText:"Regnerischer Tag mit meiner 4 jährigen Tochter",preferredPlaceTypes:[],strictCategoryIntent:false,intent:{primaryPlaceTypes:["activity","culture","outing","experience"],excludedPlaceTypes:["bar","nightlife"],mustRespectCategory:true,audience:["kids","family"]}},candidates:[{spotId:"33333333-3333-4333-8333-333333333333",retrievalPosition:1,status:"approved",city:"Basel",category:"Bar",productPlaceType:"bar",openNow:null,distributionEligible:true},{spotId:"44444444-4444-4444-8444-444444444444",retrievalPosition:2,status:"approved",city:"Basel",category:"Aktivität",productPlaceType:"activity",openNow:null,distributionEligible:true},{spotId:"55555555-5555-4555-8555-555555555555",retrievalPosition:3,status:"approved",city:"Basel",category:"Café",productPlaceType:"cafe",openNow:null,distributionEligible:true}]});const broadResult=buildDecisionInputPackage(broad);assert.deepEqual(broadResult.package.n5.currentIntent.requiredPlaceTypes,[]);assert.deepEqual(broadResult.package.candidates.map((row)=>row.spotId),[broad.candidates[1].spotId,broad.candidates[2].spotId]);assert.equal(broadResult.eligibilityAudit.every((row)=>!row.reasons.includes("REQUIRED_PLACE_TYPE_MISMATCH")),true);const explicit=source({requestContext:{query:"Bar",rawFreeText:"Bar",preferredPlaceTypes:["bar"],strictCategoryIntent:true,intent:{primaryPlaceTypes:["bar"],mustRespectCategory:true}}});assert.deepEqual(buildDecisionInputPackage(explicit).package.n5.currentIntent.requiredPlaceTypes,["bar"]);});
test("N4 rich and UNKNOWN serialize without commercial or legacy substitution",()=>{const result=buildDecisionInputPackage(source());assert.equal(result.package.candidates[0].n4.availability,"FULL");assert.equal(result.package.candidates[1].n4.availability,"UNKNOWN");assert.equal(JSON.stringify(result.package).includes("subscription"),false);assert.equal(JSON.stringify(result.package).includes("basel:spot:private"),false);});
test("Copenhagen carries portable projection without Basel trail",()=>{const value=source({decision:{...source().decision,city:"Copenhagen"},requestContext:{query:"Drinks",preferredPlaceTypes:["bar"],strictCategoryIntent:true},candidates:[{...source().candidates[0],city:"Copenhagen"}]});const result=buildDecisionInputPackage(value);assert.equal(JSON.stringify(result.package).includes("basel:spot"),false);assert.equal(result.package.n3.currentMoment.fields.city.value,"copenhagen");});
test("package replay is deterministic and validation rejects commercial injection",()=>{const left=buildDecisionInputPackage(source()).package,right=buildDecisionInputPackage(source()).package;assert.deepEqual(left,right);assert.equal(validateDecisionInputPackage(left,{expectedUserId:left.userId}).valid,true);const bad=structuredClone(left);bad.ownerPlan="premium";const body={...bad};delete body.packageHash;bad.packageHash="0".repeat(64);assert.throws(()=>validateDecisionInputPackage(bad),/forbidden|hash/);});
