"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {usePathname,useRouter,useSearchParams} from "next/navigation";
import {DateRangeSelector} from "@/components/intelligence/DateRangeSelector";
import {dateTime,number,rangeFor,type Preset} from "@/lib/intelligence";
import {supabase} from "@/lib/supabaseClient";
type UserRow={user_id:string;email:string|null;display_name:string|null;username:string|null;avatar_url:string|null;city:string|null;registered_at:string;last_active_at:string|null;activated:boolean;sessions:number;screen_views:number;spot_opens:number;decisions:number;reviews:number;platform:string|null;app_version:string|null};
type Response={summary:{registered:number;active:number;activated:number;sessions:number};users:UserRow[];total:number};
const PAGE_SIZE=50;
export default function UsersPage(){
 const pathname=usePathname(),router=useRouter(),params=useSearchParams();
 const[preset,setPreset]=useState<Preset>("month"),[data,setData]=useState<Response|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const[search,setSearch]=useState(()=>params.get("q")??"");const page=Math.max(0,Number(params.get("page")??"1")-1||0);
 useEffect(()=>{const timer=window.setTimeout(()=>{const next=new URLSearchParams(params.toString());if(search.trim())next.set("q",search.trim());else next.delete("q");next.delete("page");router.replace(next.size?`${pathname}?${next}`:pathname,{scroll:false});},300);return()=>window.clearTimeout(timer)},[pathname,router,search,params]);
 useEffect(()=>{let cancelled=false;void(async()=>{setLoading(true);setError("");const range=rangeFor(preset);const result=await supabase.rpc("admin_users_intelligence_v2",{p_from:range.from,p_to:range.to,p_limit:PAGE_SIZE,p_offset:page*PAGE_SIZE,p_search:search.trim()||null});if(cancelled)return;if(result.error){setError("Nutzerkennzahlen konnten nicht geladen werden.");setData(null)}else setData(result.data as Response);setLoading(false)})();return()=>{cancelled=true}},[page,preset,search]);
 const pages=Math.max(1,Math.ceil((data?.total??0)/PAGE_SIZE));const go=(nextPage:number)=>{const next=new URLSearchParams(params.toString());if(nextPage>0)next.set("page",String(nextPage+1));else next.delete("page");router.push(next.size?`${pathname}?${next}`:pathname)};
 return <div className="bi-page"><header className="bi-header"><div><div className="bi-eyebrow">Nutzeranalyse</div><h1>Nutzer</h1><p>Aktivierung, Nutzung und Wertbeitrag jedes einzelnen Nutzers.</p></div><DateRangeSelector value={preset} onChange={setPreset}/></header>
 {error&&<div className="bi-error">{error}</div>}{loading&&<div className="bi-state">Nutzer werden analysiert …</div>}{data&&<><section className="bi-kpiGrid"><K label="Registriert" value={data.summary.registered}/><K label="Aktiv im Zeitraum" value={data.summary.active}/><K label="Aktiviert" value={data.summary.activated}/><K label="Sitzungen" value={data.summary.sessions}/></section>
 <section className="bi-card admin-responsiveTable"><div className="bi-tableToolbar"><input className="bi-input" placeholder="Name, E-Mail, Stadt oder ID suchen …" value={search} onChange={event=>setSearch(event.target.value)}/><span>{number(data.total)} Nutzer</span></div><div className="bi-tableWrap"><table className="bi-table"><thead><tr><th>Nutzer</th><th>Status</th><th>Letzte Aktivität</th><th>Sitzungen</th><th>Ansichten</th><th>Spots</th><th>Empfehlungen</th><th>Reviews</th><th></th></tr></thead><tbody>{data.users.map(user=><tr key={user.user_id}><td data-label="Nutzer"><div className="bi-person">{user.avatar_url?<img src={user.avatar_url} alt=""/>:<i/>}<div><strong>{user.display_name||user.username||user.email||"Backyrd Nutzer"}</strong><small>{user.email||user.user_id}</small></div></div></td><td data-label="Status"><span className={`bi-badge ${user.activated?"success":"muted"}`}>{user.activated?"Aktiviert":"Nicht aktiviert"}</span></td><td data-label="Letzte Aktivität">{dateTime(user.last_active_at)}</td><td data-label="Sitzungen">{number(user.sessions)}</td><td data-label="Ansichten">{number(user.screen_views)}</td><td data-label="Spots">{number(user.spot_opens)}</td><td data-label="Empfehlungen">{number(user.decisions)}</td><td data-label="Reviews">{number(user.reviews)}</td><td data-label="Aktion"><Link className="bi-action" href={`/users/${user.user_id}?from=${encodeURIComponent(rangeFor(preset).from)}&to=${encodeURIComponent(rangeFor(preset).to)}`}>Details öffnen</Link></td></tr>)}</tbody></table></div><div className="admin-pagination"><button disabled={page===0||loading} onClick={()=>go(page-1)}>Zurück</button><span>Seite {page+1} von {pages}</span><button disabled={page+1>=pages||loading} onClick={()=>go(page+1)}>Weiter</button></div></section></>}</div>;
}
function K({label,value}:{label:string;value:number}){return <div className="bi-kpi"><span>{label}</span><strong>{number(value)}</strong><div/></div>}
