const finite = (value) => { if (!Number.isFinite(value)) throw new Error("Metric is not finite"); return value; };
const at = (values, k) => values.slice(0, Math.max(0, k));
export const eligible = (spot) => spot.observed.status === "approved" && !["quarantined", "excluded"].includes(spot.observed.distribution);
export const relevant = (value, threshold) => value >= threshold;

export function recallAt(rankedIds, relevantIds, k) {
  if (!relevantIds.length) return null;
  const found = new Set(at(rankedIds, k));
  return finite(relevantIds.filter((id) => found.has(id)).length / relevantIds.length);
}
export function precisionAt(rankedIds, relevantIds, k) { const slice = at(rankedIds, k); return slice.length ? finite(slice.filter((id) => relevantIds.includes(id)).length / slice.length) : 0; }
export function hitRateAt(rankedIds, relevantIds, k) { return at(rankedIds, k).some((id) => relevantIds.includes(id)) ? 1 : 0; }
export function dcg(gains, k) { return at(gains, k).reduce((sum, gain, index) => sum + Math.max(0, gain) / Math.log2(index + 2), 0); }
export function ndcgAt(rankedIds, utilityById, k) { const values = Object.values(utilityById); values.forEach(finite); const actual = rankedIds.map((id) => utilityById[id] ?? 0); const ideal = values.sort((a, b) => b - a); const denominator = dcg(ideal, k); return denominator ? finite(dcg(actual, k) / denominator) : null; }
export function regretAt(rankedIds, utilityById, k) { const actual = at(rankedIds, k).reduce((sum, id) => sum + (utilityById[id] ?? 0), 0); const ideal = at(Object.values(utilityById).sort((a, b) => b - a), k).reduce((a, b) => a + b, 0); return finite(Math.max(0, ideal - actual)); }
export function mrr(rankedIds, targetId) { const index = rankedIds.indexOf(targetId); return index < 0 ? 0 : 1 / (index + 1); }
export function weightedUtilityRecall(rankedIds, utilityById, k) { const positive = Object.values(utilityById).reduce((s, v) => s + Math.max(0, v), 0); return positive ? at(rankedIds, k).reduce((s, id) => s + Math.max(0, utilityById[id] ?? 0), 0) / positive : null; }
export function listQuality(rankedIds, utilityById, threshold, k) { const ids = Object.entries(utilityById).filter(([, value]) => relevant(value, threshold)).map(([id]) => id); const shown = at(rankedIds, k); const values = shown.map((id) => utilityById[id] ?? 0); return { [`recallAt${k}`]: recallAt(rankedIds, ids, k), [`precisionAt${k}`]: precisionAt(rankedIds, ids, k), [`hitRateAt${k}`]: hitRateAt(rankedIds, ids, k), [`ndcgAt${k}`]: ndcgAt(rankedIds, utilityById, k), [`regretAt${k}`]: regretAt(rankedIds, utilityById, k), top1Utility: values[0] ?? null, meanUtilityAtK: values.length ? values.reduce((a, b) => a + b, 0) / values.length : null, worstUtilityAtK: values.length ? Math.min(...values) : null };
}
export function diversityMetrics(ids, spotById, knownIds = new Set()) { const spots = ids.map((id) => spotById[id]).filter(Boolean); const unique = new Set(ids); const categories = new Set(spots.map((s) => s.category)); const duplicateRate = ids.length ? 1 - unique.size / ids.length : 0; const concentration = spots.length ? Math.max(...[...categories].map((c) => spots.filter((s) => s.category === c).length)) / spots.length : 0; return { duplicateRate, categoryConcentration: concentration, intraListCategoryDiversity: spots.length > 1 ? categories.size / spots.length : 0, noveltyAtK: spots.length ? spots.filter((s) => !knownIds.has(s.id)).length / spots.length : null };
}
export const jaccard = (a, b) => { const aa = new Set(a), bb = new Set(b), union = new Set([...aa, ...bb]); return union.size ? [...aa].filter((x) => bb.has(x)).length / union.size : 1; };
export function repetitionMetrics(sequence) { const top1 = sequence.map((ids) => ids[0]).filter(Boolean); const topK = sequence.flat(); return { repeatedTop1Rate: top1.length ? 1 - new Set(top1).size / top1.length : 0, repeatedTopKRate: topK.length ? 1 - new Set(topK).size / topK.length : 0 }; }
export function fallbackMetrics({ activated, results, eligibleIds, utilityById }) { const valid = results.filter((id) => eligibleIds.includes(id)); return { activationPrecision: activated ? 1 : null, coverage: results.length ? 1 : 0, eligibleFallbackRate: results.length ? valid.length / results.length : 1, fallbackUtility: valid.length ? valid.reduce((sum, id) => sum + (utilityById[id] ?? 0), 0) / valid.length : null, honestEmpty: eligibleIds.length === 0 && results.length === 0 }; }
export function explanationMetrics(explanations) { if (!explanations.length) return { coverage: 0, factualSupport: null, hallucinationRate: null, constraintMentionCorrectness: null }; const supported = explanations.filter((x) => x.evidence?.length && !x.unsupportedClaims?.length).length; const claims = explanations.reduce((n, x) => n + (x.claims?.length ?? 0), 0); const unsupported = explanations.reduce((n, x) => n + (x.unsupportedClaims?.length ?? 0), 0); return { coverage: explanations.filter((x) => x.evidence?.length).length / explanations.length, factualSupport: supported / explanations.length, hallucinationRate: claims ? unsupported / claims : 0, constraintMentionCorrectness: explanations.filter((x) => x.constraintCorrect !== false).length / explanations.length }; }
export function reliabilityMetrics(samples) { const valid = samples.map((x) => x.latencyMs).filter(Number.isFinite).sort((a,b) => a-b); const percentile = (p) => valid.length < 2 ? null : valid[Math.min(valid.length - 1, Math.ceil(p * valid.length) - 1)]; return { n: samples.length, min: valid[0] ?? null, median: percentile(0.5), p90: percentile(0.9), p95: percentile(0.95), p99: percentile(0.99), max: valid.at(-1) ?? null, errorRate: samples.length ? samples.filter((x) => x.error).length / samples.length : null, timeoutRate: samples.length ? samples.filter((x) => x.timeout).length / samples.length : null, calibration: "LAB_ONLY" }; }
export function outcomePotential(rankedIds, utilityById) { const probabilities = rankedIds.map((id, rank) => { const u = utilityById[id] ?? 0; const visibility = Math.exp(-0.18 * rank); return { open: visibility * (0.1 + 0.55 * u), save: visibility * 0.3 * u, like: visibility * 0.38 * u, dislike: visibility * 0.25 * (1 - u), wasHere: visibility * 0.12 * u }; }); return { label: "SYNTHETIC_OFFLINE_EXPECTATION", expected: Object.fromEntries(["open","save","like","dislike","wasHere"].map((key) => [key, probabilities.reduce((s,p) => s+p[key],0)])) }; }
