import { createHash } from "node:crypto";
import { fastEmbedding } from "./embeddings.mjs";
import { deterministicUuid } from "./random.mjs";

const q = (value) => value == null ? "null" : `'${String(value).replaceAll("'", "''")}'`;
const j = (value) => `${q(JSON.stringify(value))}::jsonb`;
const chunks = (values, size = 500) => Array.from({ length: Math.ceil(values.length / size) }, (_, index) => values.slice(index * size, (index + 1) * size));

export function productSeedSql(world, { includeEmbeddings = true } = {}) {
  const categoryIds = Object.fromEntries([...new Set(world.spots.map((spot) => spot.category))].map((category) => [category, deterministicUuid(`${world.manifest.worldId}:category`, category)]));
  const lines = ["\\set ON_ERROR_STOP on", "begin;", "set local client_min_messages = warning;", "-- Observed Product state only below. No latent value is copied into public/auth tables."];
  lines.push(`insert into decision_lab.worlds(world_id,seed,generator_version,ground_truth_version,scenario_set_version,evaluation_version,git_sha,migration_hash,engine_source_hash,embedding_mode,manifest,world_hash,generated_at) values (${q(world.manifest.worldId)}::uuid,${q(world.manifest.seed)},${q(world.manifest.generatorVersion)},${q(world.manifest.groundTruthVersion)},${q(world.manifest.scenarioSetVersion)},${q(world.manifest.evaluationVersion)},${q(world.manifest.gitSha)},${q(world.manifest.migrationHash)},${q(world.manifest.engineSourceHash)},${q(world.manifest.embeddingMode)},${j(world.manifest)},${q(world.manifest.worldHash)},${q(world.manifest.generatedAt)}::timestamptz);`);
  for (const batch of chunks(world.users)) lines.push(`insert into auth.users(instance_id,id,aud,role,email,encrypted_password,raw_app_meta_data,raw_user_meta_data,created_at,updated_at,confirmation_token,email_change,email_change_token_new,recovery_token) values\n${batch.map((user) => `('00000000-0000-0000-0000-000000000000',${q(user.id)}::uuid,'authenticated','authenticated',${q(`lab-${user.id}@synthetic.invalid`)},'',${j({ provider: "email", providers: ["email"], synthetic: true })},${j({ synthetic: true })},'2026-02-12T12:00:00Z','2026-02-12T12:00:00Z','','','','')`).join(",\n")};`);
  lines.push(`insert into public.categories(id,name) values ${Object.entries(categoryIds).map(([name, id]) => `(${q(id)}::uuid,${q(name)})`).join(",")} on conflict do nothing;`);
  // The latent Lab taxonomy retains historical `archived` as a non-public state,
  // while the current canonical Product enum supports pending/approved/rejected.
  // Persist archived fixtures as rejected; both remain identically non-eligible.
  const canonicalStatus = (status) => status === "archived" ? "rejected" : status;
  for (const batch of chunks(world.spots)) lines.push(`insert into public.spots(id,name,address,lat,lng,status,category_id,price_level,city,country,created_at,updated_at) values\n${batch.map((spot) => `(${q(spot.id)}::uuid,${q(spot.observed.name)},${q(`Synthetic address ${spot.id.slice(0, 6)}`)},${spot.observed.lat},${spot.observed.lng},${q(canonicalStatus(spot.observed.status))}::public.spot_status,${q(categoryIds[spot.category])}::uuid,${spot.observed.priceLevel ?? "null"},${q(spot.observed.city)},'Switzerland','2026-02-12T12:00:00Z','2026-08-11T12:00:00Z')`).join(",\n")};`);
  lines.push(`update public.distribution_trust_states d set automatic_state=v.state,effective_state=v.state,automatic_reason_codes=array[]::text[],reason_codes=array[]::text[],active_override_id=null,updated_at='2026-08-11T12:00:00Z' from public.safety_content_items i join (values ${world.spots.map((spot) => `(${q(spot.id)}::uuid,${q(spot.observed.distribution)})`).join(",")}) v(spot_id,state) on v.spot_id=i.entity_id where d.content_item_id=i.id and i.entity_type='spot';`);
  for (const batch of chunks(world.reviews)) lines.push(`insert into public.reviews(id,spot_id,user_id,text,mood_a,mood_b,city,created_at,updated_at) values\n${batch.map((review) => `(${q(review.id)}::uuid,${q(review.spotId)}::uuid,${q(review.userId)}::uuid,${q(review.text)},${q(review.moods[0] ?? null)},${q(review.moods[1] ?? null)},'Synthetic Basel','2026-08-11T12:00:00Z'::timestamptz + interval '${review.createdDay} days','2026-08-11T12:00:00Z')`).join(",\n")};`);
  for (const batch of chunks(world.spots)) lines.push(`insert into public.backyrd_spot_ml_documents_v1(spot_id,document_text,document_json,source_hash,document_version,created_at,updated_at) values\n${batch.map((spot) => { const text = `Spot: ${spot.observed.name}\nKategorie: ${spot.category}\nStadt: ${spot.observed.city}\nPreislevel: ${spot.observed.priceLevel ?? "unknown"}\nBeschreibung: ${spot.observed.description ?? ""}\nMoods: ${spot.observed.moods.join(", ")}`; const hash = createHash("sha256").update(text).digest("hex"); return `(${q(spot.id)}::uuid,${q(text)},${j({ name: spot.observed.name, category: spot.category, city: spot.observed.city, price_level: spot.observed.priceLevel, description: spot.observed.description, moods: spot.observed.moods })},${q(hash)},'decision-lab-observed-v1','2026-08-11T12:00:00Z','2026-08-11T12:00:00Z')`; }).join(",\n")} on conflict (spot_id) do update set document_text=excluded.document_text,document_json=excluded.document_json,source_hash=excluded.source_hash,document_version=excluded.document_version,updated_at=excluded.updated_at;`);
  if (includeEmbeddings) for (const batch of chunks(world.spots, 40)) lines.push(`insert into public.backyrd_spot_embeddings_v1(spot_id,embedding,model_name,model_dimensions,document_version,source_hash,created_at,updated_at) values\n${batch.map((spot) => { const text = `${spot.observed.name} ${spot.category} ${spot.observed.description ?? ""} ${spot.observed.moods.join(" ")}`; const hash = createHash("sha256").update(text).digest("hex"); return `(${q(spot.id)}::uuid,${q(`[${fastEmbedding(text).join(",")}]`)}::public.vector,'decision-lab-fast-feature-hash-v1',1536,'decision-lab-observed-v1',${q(hash)},'2026-08-11T12:00:00Z','2026-08-11T12:00:00Z')`; }).join(",\n")} on conflict (spot_id) do update set embedding=excluded.embedding,model_name=excluded.model_name,source_hash=excluded.source_hash,updated_at=excluded.updated_at;`);
  for (const batch of chunks(world.users)) lines.push(`insert into decision_lab.latent_users(world_id,synthetic_user_id,persona,maturity,latent_truth) values ${batch.map((user) => `(${q(world.manifest.worldId)}::uuid,${q(user.id)}::uuid,${q(user.persona)},${q(user.maturity)},${j(user.latent)})`).join(",")};`);
  for (const batch of chunks(world.spots)) lines.push(`insert into decision_lab.latent_spots(world_id,synthetic_spot_id,latent_truth) values ${batch.map((spot) => `(${q(world.manifest.worldId)}::uuid,${q(spot.id)}::uuid,${j(spot.latent)})`).join(",")};`);
  for (const batch of chunks(world.contexts)) lines.push(`insert into decision_lab.latent_contexts(world_id,context_id,latent_truth) values ${batch.map((context) => `(${q(world.manifest.worldId)}::uuid,${q(context.id)}::uuid,${j(context)})`).join(",")};`);
  for (const batch of chunks(world.decisions)) {
    lines.push(`insert into public.decision_sessions(id,user_id,city,created_at) values ${batch.map((decision) => `(${q(decision.id)}::uuid,${q(decision.userId)}::uuid,'Synthetic Basel','2026-08-11T12:00:00Z'::timestamptz + interval '${decision.day} days')`).join(",")};`);
    lines.push(`insert into public.decision_impressions(decision_id,spot_id,rank,why_this,created_at) values ${batch.map((decision) => `(${q(decision.id)}::uuid,${q(decision.shownSpotId)}::uuid,${decision.rank},'Synthetic historical exposure','2026-08-11T12:00:00Z'::timestamptz + interval '${decision.day} days')`).join(",")};`);
  }
  const eventMap = { decision_impression: "decision_impression", open: "decision_open", like: "decision_like", dislike: "decision_dislike", save: "favorite_add", was_here: "spot_detail_view" };
  for (const batch of chunks(world.interactions)) lines.push(`insert into public.backyrd_ml_events_v1(id,user_id,event_type,spot_id,decision_id,city,rank,signal_strength,context,created_at) values\n${batch.map((event) => `(${q(event.id)}::uuid,${q(event.userId)}::uuid,${q(eventMap[event.type])},${q(event.spotId)}::uuid,null,'Synthetic Basel',${event.rank},${event.type === "dislike" ? -1 : event.type === "decision_impression" ? 0.08 : 1},${j({ synthetic: true, exposed: event.exposed, context_id: event.contextId })},'2026-08-11T12:00:00Z'::timestamptz + interval '${event.day} days')`).join(",\n")};`);
  lines.push("commit;", "\\echo Decision Lab observed Product state and isolated latent truth seeded.");
  return `${lines.join("\n\n")}\n`;
}
